import { useEffect, useState, type FormEvent } from 'react';
import { Button, EmptyState, Metric, Pill, SectionTitle, Shell } from '@nexoio/ui';
import { adminApi } from './lib/api';
import './admin.css';

type Business={id:string;displayName:string;publicSlug:string;businessType:string;status:string;createdAt:string};
type Audit={id:string;action:string;entityType:string|null;createdAt:string};
type Plan={id:string;name:string;code:string;priceMonthly:string;active:boolean};
const routes=[['/','Resumo'],['/empresas','Empresas'],['/planos','Planos'],['/consumo','Consumo'],['/financeiro','Financeiro'],['/auditoria','Auditoria'],['/incidentes','Incidentes'],['/configuracoes','Configurações']] as const;

export function App(){
  const[path,setPath]=useState(location.pathname);const[businesses,setBusinesses]=useState<Business[]>([]);const[plans,setPlans]=useState<Plan[]>([]);const[audit,setAudit]=useState<Audit[]>([]);const[error,setError]=useState('');const[modal,setModal]=useState(false);
  useEffect(()=>{Promise.all([adminApi.get<{data:Business[]}>('/api/v1/admin/businesses'),adminApi.get<{data:Plan[]}>('/api/v1/admin/plans'),adminApi.get<{data:Audit[]}>('/api/v1/admin/audit')]).then(([b,p,a])=>{setBusinesses(b.data);setPlans(p.data);setAudit(a.data)}).catch(reason=>setError(reason instanceof Error?reason.message:'Falha ao carregar'));const pop=()=>setPath(location.pathname);addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);
  const go=(next:string)=>{history.pushState({},'',next);setPath(next)};const active=businesses.filter(item=>item.status==='active').length;
  const toggle=async(item:Business)=>{const status=item.status==='active'?'suspended':'active';await adminApi.patch(`/api/v1/admin/businesses/${item.id}/status`,{status});setBusinesses(all=>all.map(value=>value.id===item.id?{...value,status}:value))};
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const value=Object.fromEntries(new FormData(event.currentTarget));const result=await adminApi.post<{data:Business}>('/api/v1/admin/businesses',{displayName:String(value.displayName),publicSlug:String(value.publicSlug),businessType:String(value.businessType),email:String(value.email)||undefined});setBusinesses(all=>[result.data,...all]);setModal(false)};
  let page;if(path==='/empresas')page=<section className="panel"><SectionTitle title="Empresas da plataforma" description="Dados reais protegidos por MFA."/>{businesses.length?<table className="admin-table"><thead><tr><th>Empresa</th><th>Segmento</th><th>Status</th><th>Ação</th></tr></thead><tbody>{businesses.map(item=><tr key={item.id}><td><strong>{item.displayName}</strong><br/><small>{item.publicSlug}</small></td><td>{item.businessType}</td><td><Pill tone={item.status==='active'?'success':'warning'}>{item.status}</Pill></td><td><div className="admin-actions"><button onClick={()=>void toggle(item)}>{item.status==='active'?'Suspender':'Ativar'}</button></div></td></tr>)}</tbody></table>:<EmptyState title="Nenhuma empresa" description="Cadastre a primeira empresa."/>}</section>;
  else if(path==='/planos')page=<div className="feature-grid">{plans.map(plan=><article className="feature-card" key={plan.id}><Pill tone="brand">{plan.name}</Pill><h2>R$ {Number(plan.priceMonthly).toLocaleString('pt-BR',{minimumFractionDigits:2})}</h2><p>{plan.code}</p></article>)}</div>;
  else if(path==='/auditoria')page=<section className="panel"><SectionTitle title="Trilha de auditoria"/>{audit.map(item=><div className="activity-item" key={item.id}><div className="activity-dot"/><div><strong>{item.action}</strong><span>{item.entityType??'plataforma'} · {new Date(item.createdAt).toLocaleString('pt-BR')}</span></div></div>)}{!audit.length?<EmptyState title="Nenhum evento" description="Eventos protegidos aparecerão aqui."/>:null}</section>;
  else if(['/consumo','/financeiro','/incidentes'].includes(path))page=<section className="panel"><SectionTitle title={routes.find(([key])=>key===path)?.[1]??'Operação'}/><EmptyState title="Sem registros" description="Nenhum dado real foi registrado para esta área."/></section>;
  else if(path==='/configuracoes')page=<section className="panel"><SectionTitle title="Segurança"/><div className="switch"><div><strong>MFA obrigatório</strong><p>Exigido pelo backend para Master Admin.</p></div><input type="checkbox" checked readOnly aria-label="MFA obrigatório"/></div></section>;
  else page=<><section className="grid"><Metric label="Empresas ativas" value={String(active)}/><Metric label="Suspensas" value={String(businesses.length-active)}/><Metric label="Planos ativos" value={String(plans.filter(item=>item.active).length)}/><Metric label="Eventos" value={String(audit.length)}/></section><section className="panel"><SectionTitle title="Saúde operacional" description="API, banco e autenticação administrativa conectados."/></section></>;
  return <Shell title={routes.find(([key])=>key===path)?.[1]??'Resumo'} subtitle="Administração segura da plataforma Nexoio." nav={<nav className="admin-nav">{routes.map(([key,label])=><button key={key} className={path===key?'active':''} onClick={()=>go(key)}>{label}</button>)}</nav>} actions={<Button onClick={()=>setModal(true)}>Nova empresa</Button>}>{error?<p role="alert">{error}</p>:null}{page}{modal?<div className="admin-modal" onMouseDown={event=>event.currentTarget===event.target&&setModal(false)}><section role="dialog" aria-modal="true"><h2>Nova empresa</h2><form onSubmit={event=>void create(event)}><div className="admin-form"><label>Nome<input name="displayName" required/></label><label>Slug<input name="publicSlug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></label><label>Segmento<select name="businessType"><option value="other">Outro</option><option value="restaurant">Restaurante</option><option value="retail">Varejo</option><option value="clinic">Clínica</option></select></label><label>E-mail<input name="email" type="email"/></label></div><footer><Button type="button" ghost onClick={()=>setModal(false)}>Cancelar</Button><Button type="submit">Criar</Button></footer></form></section></div>:null}</Shell>;
}
