import { useEffect, useState, type FormEvent } from 'react';
import { Button, EmptyState, Field, Grid, Input, Modal, Pill, SectionTitle, Select, Shell, formatCurrency, formatDateTime } from '@nexoio/ui';
import { adminApi } from './lib/api';
import { AdminResourcePage, adminResourcePaths } from './AdminResourcePage';
import { BusinessMasterDetail, IncidentMasterPage, MasterDashboard, PlatformFinancePage, SupportMasterPage, TemplateMasterPage } from './AdminMasterPage';
import './admin.css';

type Business={id:string;displayName:string;publicSlug:string;businessType:string;status:string;createdAt:string};
type Audit={id:string;action:string;entityType:string|null;createdAt:string};
type Plan={id:string;name:string;code:string;priceMonthly:string;active:boolean};
const routes=[['/','Resumo'],['/empresas','Empresas'],['/planos','Planos'],['/assinaturas','Assinaturas'],['/consumo','Consumo'],['/dominios','Domínios'],['/sites','Sites'],['/usuarios','Usuários'],['/modulos','Módulos'],['/templates','Modelos'],['/suporte','Suporte'],['/financeiro','Financeiro'],['/auditoria','Auditoria'],['/incidentes','Incidentes'],['/configuracoes','Configurações']] as const;
const segmentLabels:Record<string,string>={salon:'Salão',beauty:'Estética e beleza',barbershop:'Barbearia',restaurant:'Restaurante',snackbar:'Lanchonete',retail:'Varejo',technical_assistance:'Assistência técnica',service_provider:'Prestador de serviços',gym:'Academia',studio:'Studio',clinic:'Clínica',other:'Outro'};
const statusLabel=(status:string)=>status==='active'?'Ativa':status==='suspended'?'Suspensa':status==='inactive'?'Inativa':status;

export function App(){
  const[path,setPath]=useState(location.pathname);const[businesses,setBusinesses]=useState<Business[]>([]);const[plans,setPlans]=useState<Plan[]>([]);const[audit,setAudit]=useState<Audit[]>([]);const[error,setError]=useState('');const[modal,setModal]=useState(false);const[selectedBusiness,setSelectedBusiness]=useState<string|null>(null);
  useEffect(()=>{Promise.all([adminApi.get<{data:Business[]}>('/api/v1/admin/businesses'),adminApi.get<{data:Plan[]}>('/api/v1/admin/plans'),adminApi.get<{data:Audit[]}>('/api/v1/admin/audit')]).then(([b,p,a])=>{setBusinesses(b.data);setPlans(p.data);setAudit(a.data)}).catch(reason=>setError(reason instanceof Error?reason.message:'Falha ao carregar'));const pop=()=>{setPath(location.pathname);setSelectedBusiness(null)};addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);
  const go=(next:string)=>{history.pushState({},'',next);setPath(next);setSelectedBusiness(null)};
  const toggle=async(item:Business)=>{const status=item.status==='active'?'suspended':'active';await adminApi.patch(`/api/v1/admin/businesses/${item.id}/status`,{status});setBusinesses(all=>all.map(value=>value.id===item.id?{...value,status}:value))};
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const value=Object.fromEntries(new FormData(event.currentTarget));const result=await adminApi.post<{data:Business}>('/api/v1/admin/businesses',{displayName:String(value.displayName),publicSlug:String(value.publicSlug),businessType:String(value.businessType),email:String(value.email)||undefined});setBusinesses(all=>[result.data,...all]);setModal(false)};
  let page:React.ReactNode;
  if(path==='/empresas'&&selectedBusiness)page=<BusinessMasterDetail businessId={selectedBusiness} onBack={()=>setSelectedBusiness(null)}/>;
  else if(path==='/empresas')page=<section className="panel"><SectionTitle title="Empresas da plataforma" description="Operação, plano, quota, domínio e uso por tenant."/>{businesses.length?<div className="table-shell"><table className="admin-table"><thead><tr><th>Empresa</th><th>Segmento</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{businesses.map(item=><tr key={item.id}><td><button className="admin-link" onClick={()=>setSelectedBusiness(item.id)}><strong>{item.displayName}</strong><br/><small>{item.publicSlug}</small></button></td><td>{segmentLabels[item.businessType]??item.businessType}</td><td><Pill tone={item.status==='active'?'success':'warning'}>{statusLabel(item.status)}</Pill></td><td><div className="admin-actions"><Button ghost onClick={()=>setSelectedBusiness(item.id)}>Abrir</Button><Button ghost onClick={()=>void toggle(item)}>{item.status==='active'?'Suspender':'Ativar'}</Button></div></td></tr>)}</tbody></table></div>:<EmptyState title="Nenhuma empresa" description="Cadastre a primeira empresa."/>}</section>;
  else if(path==='/planos')page=<Grid min={240}>{plans.map(plan=><article className="feature-card" key={plan.id}><Pill tone={plan.active?'success':'warning'}>{plan.active?'Ativo':'Inativo'}</Pill><h2>{plan.name}</h2><strong>{formatCurrency(plan.priceMonthly)}/mês</strong><p>{plan.code}</p></article>)}</Grid>;
  else if(path==='/templates')page=<TemplateMasterPage/>;
  else if(path==='/suporte')page=<SupportMasterPage/>;
  else if(path==='/financeiro')page=<PlatformFinancePage/>;
  else if(path==='/incidentes')page=<IncidentMasterPage/>;
  else if(path==='/auditoria')page=<section className="panel"><SectionTitle title="Trilha de auditoria" description="Histórico das ações administrativas e operacionais."/>{audit.map(item=><div className="activity-item" key={item.id}><div className="activity-dot"/><div><strong>{item.action}</strong><span>{item.entityType??'plataforma'} · {formatDateTime(item.createdAt)}</span></div></div>)}{!audit.length?<EmptyState title="Nenhum evento" description="Eventos protegidos aparecerão aqui."/>:null}</section>;
  else if(adminResourcePaths.has(path))page=<AdminResourcePage path={path}/>;
  else if(path==='/configuracoes')page=<section className="panel"><SectionTitle title="Segurança do Master" description="Políticas obrigatórias para administração da Nexoio."/><div className="switch"><div><strong>MFA obrigatório</strong><p>O backend bloqueia ações Master quando o segundo fator não está ativo.</p></div><input type="checkbox" checked readOnly aria-label="MFA obrigatório"/></div><div className="switch"><div><strong>Auditoria administrativa</strong><p>Alterações de quota, suporte, incidente, template e financeiro registram antes/depois.</p></div><Pill tone="success">Ativa</Pill></div></section>;
  else page=<MasterDashboard/>;
  return <Shell title={routes.find(([key])=>key===path)?.[1]??'Resumo'} subtitle="Administração segura da plataforma Nexoio." nav={<nav className="admin-nav">{routes.map(([key,label])=><button key={key} className={path===key?'active':''} onClick={()=>go(key)} aria-current={path===key?'page':undefined}>{label}</button>)}</nav>} actions={<Button onClick={()=>setModal(true)}>Nova empresa</Button>}>{error?<p role="alert">{error}</p>:null}{page}<Modal open={modal} title="Nova empresa" description="Crie uma empresa diretamente pela administração da plataforma." onClose={()=>setModal(false)} actions={null}><form id="admin-create-business" onSubmit={event=>void create(event)}><div className="admin-form"><Field label="Nome" required><Input name="displayName" required/></Field><Field label="Endereço público" hint="Use letras minúsculas, números e hífens." required><Input name="publicSlug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></Field><Field label="Segmento"><Select name="businessType"><option value="other">Outro</option><option value="restaurant">Restaurante</option><option value="snackbar">Lanchonete</option><option value="retail">Varejo</option><option value="salon">Salão</option><option value="barbershop">Barbearia</option><option value="technical_assistance">Assistência técnica</option><option value="service_provider">Prestador de serviços</option><option value="gym">Academia</option><option value="clinic">Clínica</option></Select></Field><Field label="E-mail"><Input name="email" type="email"/></Field></div><footer className="admin-modal-actions"><Button type="button" ghost onClick={()=>setModal(false)}>Cancelar</Button><Button type="submit">Criar empresa</Button></footer></form></Modal></Shell>;
}
