import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { useSession } from '../auth/SessionProvider';
import { ContentCard } from './ContentCard';
import { Field, Modal } from './Modal';
import { api, ApiError } from '../lib/api';

type Period={id:string;starts_on:string;ends_on:string;status:'open'|'closed';closed_at?:string|null;notes?:string|null};
type DreLine={code?:string|null;name:string;account_type:string;amount:string|number};
type Dre={basis:'cash'|'competence';from:string;to:string;lines:DreLine[];net:number};
const brl=(value:string|number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const firstDayOfMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`};
const today=()=>new Date().toISOString().slice(0,10);

export function FinanceAccountingPanel(){
  const session=useSession();const canCreate=session.permissions.has('finance.create');const canReopen=session.permissions.has('settings.update');
  const[periods,setPeriods]=useState<Period[]>([]);const[dre,setDre]=useState<Dre>({basis:'competence',from:firstDayOfMonth(),to:today(),lines:[],net:0});const[from,setFrom]=useState(firstDayOfMonth());const[to,setTo]=useState(today());const[basis,setBasis]=useState<'competence'|'cash'>('competence');const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[modal,setModal]=useState<'create'|'close'|'reopen'|null>(null);const[selected,setSelected]=useState<Period|null>(null);const[saving,setSaving]=useState(false);
  const load=useCallback(async(force=false)=>{setLoading(periods.length===0);setError('');try{const[p,d]=await Promise.all([api.get<{data:Period[]}>('/api/v1/finance/accounting-periods',{force}),api.get<{data:Dre}>(`/api/v1/finance/reports/dre?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&basis=${basis}`,{force})]);setPeriods(p.data);setDre(d.data)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar o fechamento contábil.')}finally{setLoading(false)}},[from,to,basis,periods.length]);
  useEffect(()=>{void load()},[load]);
  const totals=useMemo(()=>dre.lines.reduce((acc,line)=>{const amount=Number(line.amount||0);if(amount>=0)acc.revenue+=amount;else acc.expense+=Math.abs(amount);return acc},{revenue:0,expense:0}),[dre.lines]);
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);setError('');setNotice('');try{if(modal==='create'&&canCreate){await api.post('/api/v1/finance/accounting-periods',{startsOn:String(f.get('startsOn')||''),endsOn:String(f.get('endsOn')||''),notes:String(f.get('notes')||'')||undefined});setNotice('Período contábil criado.')}else if(modal==='close'&&selected&&canCreate){await api.post(`/api/v1/finance/accounting-periods/${selected.id}/close`,{});setNotice('Período fechado. Lançamentos retroativos passam a ser bloqueados.')}else if(modal==='reopen'&&selected&&canReopen){await api.post(`/api/v1/finance/accounting-periods/${selected.id}/reopen`,{reason:String(f.get('reason')||'').trim()});setNotice('Período reaberto com motivo auditado.')}setModal(null);setSelected(null);await load(true)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível concluir a operação contábil.')}finally{setSaving(false)}};
  const choose=(period:Period,action:'close'|'reopen')=>{setSelected(period);setNotice('');setModal(action)};
  const periodLabel=(period:Period)=>`${new Date(`${period.starts_on}T12:00:00`).toLocaleDateString('pt-BR')} — ${new Date(`${period.ends_on}T12:00:00`).toLocaleDateString('pt-BR')}`;
  return <div className="stack-lg"><ContentCard title="DRE" description="Resultado alimentado automaticamente pelo razão contábil das vendas, recebimentos, pagamentos e estornos."><div className="toolbar"><label>De <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Regime <select value={basis} onChange={e=>setBasis(e.target.value as 'competence'|'cash')}><option value="competence">Competência</option><option value="cash">Caixa</option></select></label><Button type="button" secondary onClick={()=>void load(true)}>Atualizar</Button></div>{error?<div className="auth-notice error" role="alert">{error}</div>:null}{notice?<div className="auth-notice success" role="status">{notice}</div>:null}<div className="stat-grid"><article className="metric"><p>Receitas</p><strong>{brl(totals.revenue)}</strong></article><article className="metric"><p>Despesas</p><strong>{brl(totals.expense)}</strong></article><article className="metric"><p>Resultado</p><strong>{brl(dre.net)}</strong><small>{basis==='cash'?'Regime de caixa':'Regime de competência'}</small></article></div>{loading?<div className="empty-state"><h3>Calculando DRE…</h3></div>:dre.lines.length?<div className="table-shell"><table><thead><tr><th>Conta</th><th>Tipo</th><th>Valor</th></tr></thead><tbody>{dre.lines.map((line,i)=><tr key={`${line.code||'sem'}-${i}`}><td><strong>{line.code?`${line.code} · `:''}{line.name}</strong></td><td>{line.account_type}</td><td>{brl(line.amount)}</td></tr>)}</tbody></table></div>:<EmptyState title="Sem lançamentos no período" description="As vendas e contas liquidadas passam a alimentar o razão automaticamente."/>}</ContentCard>
  <ContentCard title="Fechamento contábil" description="Períodos fechados impedem lançamentos retroativos; reaberturas exigem motivo e ficam auditadas.">{canCreate?<div className="toolbar"><Button onClick={()=>{setSelected(null);setModal('create')}}>Novo período</Button></div>:null}{periods.length?<div className="table-shell"><table><thead><tr><th>Período</th><th>Status</th><th>Fechado em</th><th></th></tr></thead><tbody>{periods.map(period=><tr key={period.id}><td><strong>{periodLabel(period)}</strong>{period.notes?<small>{period.notes}</small>:null}</td><td><Pill tone={period.status==='closed'?'success':'warning'}>{period.status==='closed'?'Fechado':'Aberto'}</Pill></td><td>{period.closed_at?new Date(period.closed_at).toLocaleString('pt-BR'):'—'}</td><td className="row-actions">{period.status==='open'&&canCreate?<button type="button" onClick={()=>choose(period,'close')}>Fechar</button>:period.status==='closed'&&canReopen?<button type="button" onClick={()=>choose(period,'reopen')}>Reabrir</button>:null}</td></tr>)}</tbody></table></div>:<EmptyState title="Nenhum período contábil" description={canCreate?'Crie o primeiro período para controlar o fechamento mensal.':'Nenhum período contábil foi criado para esta empresa.'}/>}</ContentCard>
  {canCreate?<Modal open={modal==='create'} onClose={()=>!saving&&setModal(null)} onSubmit={submit} title="Novo período contábil" submitLabel={saving?'Salvando…':'Criar período'}><Field label="Início" name="startsOn" type="date" required/><Field label="Fim" name="endsOn" type="date" required/><Field label="Observações" name="notes"/></Modal>:null}
  {canCreate?<Modal open={modal==='close'&&Boolean(selected)} onClose={()=>!saving&&(setModal(null),setSelected(null))} onSubmit={submit} title="Fechar período contábil" description={selected?periodLabel(selected):undefined} submitLabel={saving?'Fechando…':'Confirmar fechamento'}><div className="auth-notice warning">Após o fechamento, lançamentos retroativos dentro deste período serão bloqueados.</div></Modal>:null}
  {canReopen?<Modal open={modal==='reopen'&&Boolean(selected)} onClose={()=>!saving&&(setModal(null),setSelected(null))} onSubmit={submit} title="Reabrir período contábil" description={selected?periodLabel(selected):undefined} submitLabel={saving?'Reabrindo…':'Confirmar reabertura'}><Field label="Motivo da reabertura" name="reason"><textarea name="reason" minLength={5} maxLength={1000} rows={4} required placeholder="Explique por que o período precisa ser reaberto"/></Field></Modal>:null}</div>;
}
