import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from './ContentCard';
import { Field, Modal } from './Modal';
import { api, ApiError } from '../lib/api';

type Supplier={id:string;name:string;document_number?:string|null;email?:string|null;phone?:string|null;active:boolean};
type Location={id:string;name:string};
type Product={id:string;name:string};
type PurchaseItem={id:string;productId:string;variantId?:string|null;description:string;orderedQuantity:number;receivedQuantity:number;unitCost:number;total:number};
type PurchaseOrder={id:string;supplier_id?:string|null;supplier_name?:string|null;location_id:string;location_name:string;status:string;ordered_on:string;expected_on?:string|null;total:string|number;items:PurchaseItem[]};
type CostRow={location_id:string;location_name:string;product_id:string;product_name:string;variant_name?:string|null;average_cost:string|number;quantity_on_hand:string|number};
type ExpiryRow={product_name:string;location_name:string;lot_code:string;expiration_date:string;on_hand:string|number;reserved:string|number};
type DraftItem={productId:string;description:string;quantity:number;unitCost:number};

const brl=(value:string|number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export function InventoryProcurementPanel(){
  const[suppliers,setSuppliers]=useState<Supplier[]>([]);const[locations,setLocations]=useState<Location[]>([]);const[products,setProducts]=useState<Product[]>([]);const[orders,setOrders]=useState<PurchaseOrder[]>([]);const[costs,setCosts]=useState<CostRow[]>([]);const[expiry,setExpiry]=useState<ExpiryRow[]>([]);
  const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[supplierOpen,setSupplierOpen]=useState(false);const[orderOpen,setOrderOpen]=useState(false);const[receiveOrder,setReceiveOrder]=useState<PurchaseOrder|null>(null);const[saving,setSaving]=useState(false);
  const[draftItems,setDraftItems]=useState<DraftItem[]>([{productId:'',description:'',quantity:1,unitCost:0}]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[s,l,p,o,c,e]=await Promise.all([api.get<{data:Supplier[]}>('/api/v1/suppliers'),api.get<{data:Location[]}>('/api/v1/inventory/locations'),api.get<{data:Product[]}>('/api/v1/products'),api.get<{data:PurchaseOrder[]}>('/api/v1/purchase-orders'),api.get<{data:CostRow[]}>('/api/v1/inventory/costs'),api.get<{data:{items:ExpiryRow[]}}>('/api/v1/inventory/expiry-report?days=60')]);setSuppliers(s.data);setLocations(l.data);setProducts(p.data);setOrders(o.data);setCosts(c.data);setExpiry(e.data.items)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar compras e custos.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const orderedTotal=useMemo(()=>orders.filter(x=>['ordered','partial'].includes(x.status)).reduce((sum,x)=>sum+Number(x.total||0),0),[orders]);
  const createSupplier=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{await api.post('/api/v1/suppliers',{name:String(f.get('name')||''),documentNumber:String(f.get('documentNumber')||'')||undefined,email:String(f.get('email')||'')||undefined,phone:String(f.get('phone')||'')||undefined,notes:String(f.get('notes')||'')||undefined});setSupplierOpen(false);await load()}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível cadastrar o fornecedor.')}finally{setSaving(false)}};
  const createOrder=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const valid=draftItems.filter(x=>x.productId&&x.description&&x.quantity>0&&x.unitCost>=0);if(!valid.length){setError('Adicione pelo menos um item válido ao pedido.');return}setSaving(true);try{await api.post('/api/v1/purchase-orders',{supplierId:String(f.get('supplierId')||'')||undefined,locationId:String(f.get('locationId')||''),expectedOn:String(f.get('expectedOn')||'')||undefined,notes:String(f.get('notes')||'')||undefined,items:valid});setOrderOpen(false);setDraftItems([{productId:'',description:'',quantity:1,unitCost:0}]);await load()}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível criar o pedido de compra.')}finally{setSaving(false)}};
  const receive=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!receiveOrder)return;const f=new FormData(e.currentTarget);const items=receiveOrder.items.map(item=>({purchaseOrderItemId:item.id,quantity:Number(f.get(`qty-${item.id}`)||0),unitCost:Number(f.get(`cost-${item.id}`)||item.unitCost),lotCode:String(f.get(`lot-${item.id}`)||'')||undefined,expirationDate:String(f.get(`exp-${item.id}`)||'')||undefined})).filter(x=>x.quantity>0);if(!items.length){setError('Informe ao menos uma quantidade recebida.');return}setSaving(true);try{await api.post(`/api/v1/purchase-orders/${receiveOrder.id}/receive`,{notes:String(f.get('notes')||'')||undefined,items});setReceiveOrder(null);await load()}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível receber o pedido.')}finally{setSaving(false)}};
  const updateDraft=(index:number,patch:Partial<DraftItem>)=>setDraftItems(current=>current.map((item,i)=>i===index?{...item,...patch}:item));
  return <div className="stack-lg"><ContentCard title="Compras e recebimentos" description="Pedido de compra → recebimento parcial/total → lote/validade → saldo e custo automáticos."><div className="toolbar"><Button onClick={()=>setOrderOpen(true)}>Novo pedido de compra</Button><Button secondary onClick={()=>setSupplierOpen(true)}>Novo fornecedor</Button></div>{error?<div className="auth-notice error" role="alert">{error}</div>:null}{loading?<div className="empty-state"><h3>Carregando compras…</h3></div>:orders.length?<div className="table-shell"><table><thead><tr><th>Fornecedor</th><th>Local</th><th>Data</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td><strong>{order.supplier_name||'Sem fornecedor'}</strong></td><td>{order.location_name}</td><td>{new Date(`${order.ordered_on}T12:00:00`).toLocaleDateString('pt-BR')}</td><td>{brl(order.total)}</td><td><Pill tone={order.status==='received'?'success':order.status==='partial'?'warning':'brand'}>{order.status}</Pill></td><td className="row-actions">{['ordered','partial'].includes(order.status)?<button type="button" onClick={()=>setReceiveOrder(order)}>Receber</button>:null}</td></tr>)}</tbody></table></div>:<EmptyState title="Nenhum pedido de compra" description="Crie o primeiro pedido para receber mercadorias com custo e lote controlados."/>}<div className="stat-inline"><span>Em aberto</span><strong>{brl(orderedTotal)}</strong></div></ContentCard>
  <ContentCard title="Custo médio por estoque" description="Atualizado automaticamente a cada recebimento.">{costs.length?<div className="table-shell"><table><thead><tr><th>Produto</th><th>Local</th><th>Quantidade</th><th>Custo médio</th></tr></thead><tbody>{costs.map((row,i)=><tr key={`${row.location_id}-${row.product_id}-${i}`}><td><strong>{row.product_name}</strong>{row.variant_name?` · ${row.variant_name}`:''}</td><td>{row.location_name}</td><td>{Number(row.quantity_on_hand).toLocaleString('pt-BR')}</td><td>{brl(row.average_cost)}</td></tr>)}</tbody></table></div>:<EmptyState title="Sem custos calculados" description="Os custos aparecem após o primeiro recebimento de compra."/>}</ContentCard>
  <ContentCard title="Lotes próximos do vencimento" description="Produtos com validade nos próximos 60 dias; as reservas usam FEFO antes de FIFO.">{expiry.length?<div className="table-shell"><table><thead><tr><th>Produto</th><th>Lote</th><th>Validade</th><th>Local</th><th>Saldo</th></tr></thead><tbody>{expiry.map((row,i)=><tr key={`${row.lot_code}-${i}`}><td><strong>{row.product_name}</strong></td><td>{row.lot_code}</td><td>{new Date(`${row.expiration_date}T12:00:00`).toLocaleDateString('pt-BR')}</td><td>{row.location_name}</td><td>{Number(row.on_hand)-Number(row.reserved)}</td></tr>)}</tbody></table></div>:<EmptyState title="Nenhum lote vencendo" description="Não há lotes com validade dentro dos próximos 60 dias."/>}</ContentCard>
  <Modal open={supplierOpen} onClose={()=>!saving&&setSupplierOpen(false)} onSubmit={createSupplier} title="Novo fornecedor" submitLabel={saving?'Salvando…':'Salvar fornecedor'}><Field label="Nome" name="name" required/><Field label="CNPJ/CPF" name="documentNumber"/><Field label="E-mail" name="email" type="email"/><Field label="Telefone" name="phone"/><Field label="Observações" name="notes"/></Modal>
  <Modal open={orderOpen} onClose={()=>!saving&&setOrderOpen(false)} onSubmit={createOrder} title="Novo pedido de compra" submitLabel={saving?'Salvando…':'Criar pedido'}><Field label="Fornecedor" name="supplierId"><select name="supplierId"><option value="">Sem fornecedor</option>{suppliers.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Local de estoque" name="locationId" required><select name="locationId" required><option value="">Selecione</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Previsão" name="expectedOn" type="date"/><Field label="Observações" name="notes"/><div className="stack-sm"><strong>Itens</strong>{draftItems.map((item,index)=><div className="form-grid" key={index}><label>Produto<select value={item.productId} onChange={e=>{const p=products.find(x=>x.id===e.target.value);updateDraft(index,{productId:e.target.value,description:item.description||p?.name||''})}}><option value="">Selecione</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Descrição<input value={item.description} onChange={e=>updateDraft(index,{description:e.target.value})}/></label><label>Quantidade<input type="number" min="0.001" step="0.001" value={item.quantity} onChange={e=>updateDraft(index,{quantity:Number(e.target.value)})}/></label><label>Custo unitário<input type="number" min="0" step="0.01" value={item.unitCost} onChange={e=>updateDraft(index,{unitCost:Number(e.target.value)})}/></label>{draftItems.length>1?<button type="button" onClick={()=>setDraftItems(current=>current.filter((_,i)=>i!==index))}>Remover</button>:null}</div>)}<Button type="button" secondary onClick={()=>setDraftItems(current=>[...current,{productId:'',description:'',quantity:1,unitCost:0}])}>Adicionar item</Button></div></Modal>
  <Modal open={Boolean(receiveOrder)} onClose={()=>!saving&&setReceiveOrder(null)} onSubmit={receive} title="Receber pedido de compra" submitLabel={saving?'Recebendo…':'Confirmar recebimento'}>{receiveOrder?.items.map(item=>{const remaining=Math.max(0,Number(item.orderedQuantity)-Number(item.receivedQuantity));return <div className="stack-sm" key={item.id}><strong>{item.description}</strong><small>Pedido: {item.orderedQuantity} · recebido: {item.receivedQuantity} · saldo: {remaining}</small><div className="form-grid"><label>Quantidade recebida<input name={`qty-${item.id}`} type="number" min="0" max={remaining} step="0.001" defaultValue={remaining}/></label><label>Custo unitário<input name={`cost-${item.id}`} type="number" min="0" step="0.01" defaultValue={item.unitCost}/></label><Field label="Lote" name={`lot-${item.id}`}/><Field label="Validade" name={`exp-${item.id}`} type="date"/></div></div>})}<Field label="Observações do recebimento" name="notes"/></Modal></div>;
}
