import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { api, ApiError } from '../lib/api';

type Row=Record<string,unknown>&{id:string};
type Relation={endpoint:string;label:(row:Row)=>string};
type FieldConfig={name:string;label:string;type?:string;required?:boolean;options?:Array<[string,string]>;relation?:Relation};
type Config={endpoint:string;recordName:string;fields:FieldConfig[];create?:boolean;mapPayload:(form:FormData)=>unknown;titleOf:(row:Row)=>string;detailOf:(row:Row)=>string;statusOf?:(row:Row)=>string};
const text=(form:FormData,key:string)=>String(form.get(key)??'').trim();const number=(form:FormData,key:string)=>Number(form.get(key)??0);const nullable=(value:string)=>value||undefined;
const configs:Record<string,Config>={
 orders:{endpoint:'/api/v1/orders',recordName:'pedido',fields:[{name:'description',label:'Item/descrição',required:true},{name:'quantity',label:'Quantidade',type:'number',required:true},{name:'unitPrice',label:'Valor unitário',type:'number',required:true},{name:'channel',label:'Canal',options:[['counter','Balcão'],['table','Mesa'],['pickup','Retirada'],['delivery','Delivery'],['online','Online']]},{name:'customerId',label:'Cliente',relation:{endpoint:'/api/v1/customers',label:r=>String(r.name??'Cliente')}}],mapPayload:f=>({customerId:nullable(text(f,'customerId')),channel:text(f,'channel')||'counter',items:[{description:text(f,'description'),quantity:number(f,'quantity'),unitPrice:number(f,'unitPrice'),discount:0}]}),titleOf:r=>`Pedido #${String(r.id).slice(0,8)}`,detailOf:r=>`${String(r.customer_name??'Consumidor final')} · ${String(r.channel??'')} · R$ ${Number(r.total??0).toFixed(2)}`,statusOf:r=>String(r.status??'')},
 tables:{endpoint:'/api/v1/tables',recordName:'mesa',fields:[{name:'number',label:'Número/nome',required:true},{name:'seats',label:'Lugares',type:'number'}],mapPayload:f=>({number:text(f,'number'),seats:number(f,'seats')||undefined}),titleOf:r=>`Mesa ${String(r.number??'')}`,detailOf:r=>`${String(r.seats??'—')} lugares`,statusOf:r=>String(r.status??'')},
 commands:{endpoint:'/api/v1/commands',recordName:'comanda',fields:[{name:'code',label:'Código da comanda',required:true},{name:'tableId',label:'Mesa',relation:{endpoint:'/api/v1/tables',label:r=>`Mesa ${String(r.number??'')}`}},{name:'customerId',label:'Cliente',relation:{endpoint:'/api/v1/customers',label:r=>String(r.name??'Cliente')}},{name:'guestCount',label:'Pessoas',type:'number'}],mapPayload:f=>({code:text(f,'code'),tableId:nullable(text(f,'tableId')),customerId:nullable(text(f,'customerId')),guestCount:number(f,'guestCount')||1}),titleOf:r=>`Comanda ${String(r.code??'')}`,detailOf:r=>`${String(r.table_number?`Mesa ${r.table_number}`:'Sem mesa')} · ${String(r.customer_name??'Sem cliente')} · R$ ${Number(r.total??0).toFixed(2)}`,statusOf:r=>String(r.status??'')},
 kitchen:{endpoint:'/api/v1/kitchen',recordName:'ticket',fields:[],create:false,mapPayload:()=>({}),titleOf:r=>`Cozinha · ${String(r.table_number?`Mesa ${r.table_number}`:r.channel??'Pedido')}`,detailOf:r=>Array.isArray(r.items)?`${r.items.length} item(ns) · prioridade ${String(r.priority??0)}`:'Fila de preparo',statusOf:r=>String(r.status??'')},
 delivery:{endpoint:'/api/v1/delivery',recordName:'entrega',fields:[],create:false,mapPayload:()=>({}),titleOf:r=>String(r.customer_name??'Entrega'),detailOf:r=>`${String(r.courier_name??'Sem entregador')} · R$ ${Number(r.total??0).toFixed(2)}`,statusOf:r=>String(r.status??'')},
 inventory:{endpoint:'/api/v1/inventory/balances',recordName:'movimento',fields:[{name:'locationId',label:'Local de estoque',required:true,relation:{endpoint:'/api/v1/inventory/locations',label:r=>String(r.name??'Local')}},{name:'productId',label:'Produto',required:true,relation:{endpoint:'/api/v1/products',label:r=>String(r.name??'Produto')}},{name:'type',label:'Movimento',options:[['purchase','Entrada por compra'],['adjustment_in','Ajuste de entrada'],['adjustment_out','Ajuste de saída'],['return','Devolução']]},{name:'quantity',label:'Quantidade',type:'number',required:true},{name:'unitCost',label:'Custo unitário',type:'number'},{name:'notes',label:'Motivo/observação'}],mapPayload:f=>({locationId:text(f,'locationId'),productId:text(f,'productId'),type:text(f,'type'),quantity:number(f,'quantity'),unitCost:number(f,'unitCost')||undefined,notes:text(f,'notes')||undefined}),titleOf:r=>String(r.product_name??'Produto'),detailOf:r=>`${String(r.location_name??'')} · saldo ${String(r.on_hand??0)} · reservado ${String(r.reserved??0)} · disponível ${String(r.available??0)}`},
 service_orders:{endpoint:'/api/v1/service-orders',recordName:'ordem de serviço',fields:[{name:'customerId',label:'Cliente',relation:{endpoint:'/api/v1/customers',label:r=>String(r.name??'Cliente')}},{name:'subject',label:'Assunto/equipamento'},{name:'equipmentType',label:'Tipo de equipamento'},{name:'brand',label:'Marca'},{name:'model',label:'Modelo'},{name:'problemReported',label:'Problema relatado',required:true},{name:'estimatedValue',label:'Valor estimado',type:'number'}],mapPayload:f=>({customerId:nullable(text(f,'customerId')),subject:nullable(text(f,'subject')),equipmentType:nullable(text(f,'equipmentType')),brand:nullable(text(f,'brand')),model:nullable(text(f,'model')),problemReported:text(f,'problemReported'),estimatedValue:number(f,'estimatedValue')||undefined}),titleOf:r=>`OS #${String(r.number??'')}${r.subject?` · ${String(r.subject)}`:''}`,detailOf:r=>`${String(r.customer_name??'Sem cliente')} · ${String(r.problem_reported??'')}`,statusOf:r=>String(r.status??'')},
 equipment:{endpoint:'/api/v1/equipment',recordName:'equipamento',fields:[{name:'customerId',label:'Cliente',required:true,relation:{endpoint:'/api/v1/customers',label:r=>String(r.name??'Cliente')}},{name:'equipmentType',label:'Tipo',required:true},{name:'brand',label:'Marca'},{name:'model',label:'Modelo'},{name:'serialNumber',label:'Número de série'},{name:'identifier',label:'Identificação'}],mapPayload:f=>({customerId:text(f,'customerId'),equipmentType:text(f,'equipmentType'),brand:nullable(text(f,'brand')),model:nullable(text(f,'model')),serialNumber:nullable(text(f,'serialNumber')),identifier:nullable(text(f,'identifier'))}),titleOf:r=>`${String(r.equipment_type??'Equipamento')} ${String(r.brand??'')} ${String(r.model??'')}`.trim(),detailOf:r=>`${String(r.customer_name??'')} · Série: ${String(r.serial_number??'—')}`},
 parts:{endpoint:'/api/v1/service-order-parts',recordName:'peça aplicada',fields:[{name:'serviceOrderId',label:'Ordem de serviço',required:true,relation:{endpoint:'/api/v1/service-orders',label:r=>`OS #${String(r.number??'')}`}},{name:'productId',label:'Produto/peça de estoque',relation:{endpoint:'/api/v1/products',label:r=>String(r.name??'Produto')}},{name:'description',label:'Descrição',required:true},{name:'quantity',label:'Quantidade',type:'number',required:true},{name:'unitCost',label:'Custo unitário',type:'number'},{name:'unitPrice',label:'Preço cobrado',type:'number',required:true}],mapPayload:f=>({serviceOrderId:text(f,'serviceOrderId'),productId:nullable(text(f,'productId')),description:text(f,'description'),quantity:number(f,'quantity'),unitCost:number(f,'unitCost')||undefined,unitPrice:number(f,'unitPrice')}),titleOf:r=>String(r.description??'Peça'),detailOf:r=>`OS #${String(r.service_order_number??'')} · ${String(r.quantity??0)} un. · R$ ${Number(r.total??0).toFixed(2)}`},
 warranties:{endpoint:'/api/v1/warranties',recordName:'garantia',fields:[{name:'serviceOrderId',label:'Ordem de serviço',required:true,relation:{endpoint:'/api/v1/service-orders',label:r=>`OS #${String(r.number??'')}`}},{name:'customerId',label:'Cliente',relation:{endpoint:'/api/v1/customers',label:r=>String(r.name??'Cliente')}},{name:'startsOn',label:'Início',type:'date',required:true},{name:'expiresOn',label:'Validade',type:'date',required:true},{name:'coverage',label:'Cobertura'}],mapPayload:f=>({serviceOrderId:text(f,'serviceOrderId'),customerId:nullable(text(f,'customerId')),startsOn:text(f,'startsOn'),expiresOn:text(f,'expiresOn'),coverage:nullable(text(f,'coverage'))}),titleOf:r=>`Garantia OS #${String(r.service_order_number??'')}`,detailOf:r=>`${String(r.customer_name??'')} · até ${String(r.expires_on??'')}`,statusOf:r=>String(r.status??'')},
 patients:{endpoint:'/api/v1/patients',recordName:'paciente',fields:[{name:'name',label:'Nome completo',required:true},{name:'documentNumber',label:'Documento'},{name:'birthDate',label:'Nascimento',type:'date'},{name:'phone',label:'Telefone',type:'tel'},{name:'email',label:'E-mail',type:'email'},{name:'allergies',label:'Alergias/alertas'}],mapPayload:f=>({name:text(f,'name'),documentNumber:nullable(text(f,'documentNumber')),birthDate:nullable(text(f,'birthDate')),phone:nullable(text(f,'phone')),email:nullable(text(f,'email')),allergies:nullable(text(f,'allergies'))}),titleOf:r=>String(r.name??'Paciente'),detailOf:r=>`${String(r.phone??'')} · ${String(r.email??'')}`,statusOf:r=>r.active===false?'Inativo':'Ativo'},
 medical_records:{endpoint:'/api/v1/medical-records',recordName:'registro de prontuário',fields:[{name:'patientId',label:'Paciente',required:true,relation:{endpoint:'/api/v1/patients',label:r=>String(r.name??'Paciente')}},{name:'professionalId',label:'Profissional',relation:{endpoint:'/api/v1/professionals',label:r=>String(r.display_name??'Profissional')}},{name:'title',label:'Título',required:true},{name:'notes',label:'Evolução/observações',required:true}],mapPayload:f=>({patientId:text(f,'patientId'),professionalId:nullable(text(f,'professionalId')),recordType:'evolution',title:text(f,'title'),notes:text(f,'notes')}),titleOf:r=>`${String(r.patient_name??'Paciente')} · ${String(r.title??'Prontuário')}`,detailOf:r=>`${String(r.professional_name??'')} · ${new Date(String(r.created_at??Date.now())).toLocaleString('pt-BR')}`},
 procedures:{endpoint:'/api/v1/clinical-procedures/catalog',recordName:'procedimento',fields:[{name:'name',label:'Nome',required:true},{name:'description',label:'Descrição'},{name:'durationMinutes',label:'Duração (min)',type:'number'},{name:'price',label:'Valor',type:'number'},{name:'preparation',label:'Preparo necessário'}],mapPayload:f=>({name:text(f,'name'),description:nullable(text(f,'description')),durationMinutes:number(f,'durationMinutes')||undefined,price:number(f,'price'),preparation:nullable(text(f,'preparation'))}),titleOf:r=>String(r.name??'Procedimento'),detailOf:r=>`${String(r.duration_minutes??'—')} min · R$ ${Number(r.price??0).toFixed(2)}`,statusOf:r=>r.active===false?'Inativo':'Ativo'},
 plans:{endpoint:'/api/v1/membership-plans',recordName:'plano',fields:[{name:'name',label:'Nome do plano',required:true},{name:'price',label:'Valor',type:'number',required:true},{name:'billingCycle',label:'Ciclo',options:[['monthly','Mensal'],['weekly','Semanal'],['quarterly','Trimestral'],['yearly','Anual']]},{name:'durationMonths',label:'Duração (meses)',type:'number'},{name:'checkinLimit',label:'Limite de check-ins',type:'number'}],mapPayload:f=>({name:text(f,'name'),price:number(f,'price'),billingCycle:text(f,'billingCycle')||'monthly',durationMonths:number(f,'durationMonths')||undefined,checkinLimit:number(f,'checkinLimit')||undefined}),titleOf:r=>String(r.name??'Plano'),detailOf:r=>`R$ ${Number(r.price??0).toFixed(2)} · ${String(r.billing_cycle??'monthly')}`,statusOf:r=>r.active===false?'Inativo':'Ativo'},
 memberships:{endpoint:'/api/v1/membership-installments',recordName:'mensalidade',fields:[{name:'enrollmentId',label:'Matrícula',required:true,relation:{endpoint:'/api/v1/enrollments',label:r=>`${String(r.customer_name??'Aluno')} · ${String(r.plan_name??'Plano')}`}},{name:'amount',label:'Valor',type:'number',required:true},{name:'dueDate',label:'Vencimento',type:'date',required:true}],mapPayload:f=>({enrollmentId:text(f,'enrollmentId'),amount:number(f,'amount'),dueDate:text(f,'dueDate')}),titleOf:r=>String(r.customer_name??'Mensalidade'),detailOf:r=>`${String(r.plan_name??'')} · venc. ${String(r.due_date??'')} · R$ ${Number(r.amount??0).toFixed(2)}`,statusOf:r=>String(r.status??'')},
 classes:{endpoint:'/api/v1/classes',recordName:'turma',fields:[{name:'name',label:'Nome da turma',required:true},{name:'professionalId',label:'Professor',relation:{endpoint:'/api/v1/professionals',label:r=>String(r.display_name??'Profissional')}},{name:'capacity',label:'Vagas',type:'number'},{name:'startsAt',label:'Início',type:'datetime-local',required:true},{name:'endsAt',label:'Fim',type:'datetime-local',required:true}],mapPayload:f=>({name:text(f,'name'),professionalId:nullable(text(f,'professionalId')),capacity:number(f,'capacity')||undefined,startsAt:new Date(text(f,'startsAt')).toISOString(),endsAt:new Date(text(f,'endsAt')).toISOString()}),titleOf:r=>String(r.name??'Turma'),detailOf:r=>`${String(r.professional_name??'')} · ${new Date(String(r.starts_at??Date.now())).toLocaleString('pt-BR')} · ${String(r.enrolled??0)}/${String(r.capacity??'∞')}`,statusOf:r=>String(r.status??'')},
 checkin:{endpoint:'/api/v1/checkins',recordName:'check-in',fields:[{name:'enrollmentId',label:'Matrícula',required:true,relation:{endpoint:'/api/v1/enrollments',label:r=>`${String(r.customer_name??'Aluno')} · ${String(r.plan_name??'Plano')}`}},{name:'classId',label:'Turma',relation:{endpoint:'/api/v1/classes',label:r=>String(r.name??'Turma')}}],mapPayload:f=>({enrollmentId:text(f,'enrollmentId'),classId:nullable(text(f,'classId')),source:'staff'}),titleOf:r=>String(r.customer_name??'Check-in'),detailOf:r=>`${String(r.plan_name??'')} · ${String(r.class_name??'Entrada livre')} · ${new Date(String(r.checked_in_at??Date.now())).toLocaleString('pt-BR')}`},
 professionals:{endpoint:'/api/v1/professionals',recordName:'profissional',fields:[{name:'displayName',label:'Nome do profissional',required:true}],mapPayload:f=>({displayName:text(f,'displayName')}),titleOf:r=>String(r.display_name??'Profissional'),detailOf:r=>r.user_id?'Vinculado a usuário':'Cadastro profissional independente',statusOf:r=>r.active===false?'Inativo':'Ativo'},
 commissions:{endpoint:'/api/v1/commission-rules',recordName:'regra de comissão',fields:[{name:'professionalId',label:'Profissional',relation:{endpoint:'/api/v1/professionals',label:r=>String(r.display_name??'Profissional')}},{name:'itemType',label:'Aplicação',options:[['all','Tudo'],['service','Serviço'],['product','Produto']]},{name:'ratePercent',label:'Percentual',type:'number'},{name:'fixedAmount',label:'Valor fixo',type:'number'}],mapPayload:f=>({professionalId:nullable(text(f,'professionalId')),itemType:text(f,'itemType')||'all',ratePercent:number(f,'ratePercent'),fixedAmount:number(f,'fixedAmount')}),titleOf:r=>String(r.professional_name??'Regra geral'),detailOf:r=>`${Number(r.rate_percent??0).toFixed(2)}% + R$ ${Number(r.fixed_amount??0).toFixed(2)} · ${String(r.item_type??'all')}`,statusOf:r=>r.active===false?'Inativa':'Ativa'},
 suppliers:{endpoint:'/api/v1/suppliers',recordName:'fornecedor',fields:[{name:'name',label:'Nome/Razão social',required:true},{name:'documentNumber',label:'CNPJ/CPF'},{name:'phone',label:'Telefone',type:'tel'},{name:'email',label:'E-mail',type:'email'}],mapPayload:f=>({name:text(f,'name'),documentNumber:nullable(text(f,'documentNumber')),phone:nullable(text(f,'phone')),email:nullable(text(f,'email'))}),titleOf:r=>String(r.name??'Fornecedor'),detailOf:r=>`${String(r.document_number??'')} · ${String(r.phone??'')} · ${String(r.email??'')}`},
};

export const OPERATIONAL_MODULES=new Set(Object.keys(configs));
export function OperationalModulePage({moduleKey,title,description}:{moduleKey:string;title:string;description:string}){
 const config=configs[moduleKey];const[items,setItems]=useState<Row[]>([]);const[relations,setRelations]=useState<Record<string,Row[]>>({});const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 const relationFields=useMemo(()=>config?.fields.filter(field=>field.relation)??[],[config]);
 const load=useCallback(async()=>{if(!config)return;setLoading(true);setError('');try{const main=await api.get<{data:Row[]}>(config.endpoint);setItems(main.data);const unique=[...new Map(relationFields.map(field=>[field.relation!.endpoint,field.relation!])).entries()];const values=await Promise.all(unique.map(([endpoint])=>api.get<{data:Row[]}>(endpoint)));setRelations(Object.fromEntries(unique.map(([endpoint],index)=>[endpoint,values[index]?.data??[]])))}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar este módulo.')}finally{setLoading(false)}},[config,relationFields]);
 useEffect(()=>{void load()},[load]);
 if(!config)return <><PageHeader title={title} description={description}/><EmptyState title="Módulo em migração" description="Este módulo ainda não possui adaptador operacional."/></>;
 const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError('');try{await api.post(config.endpoint,config.mapPayload(new FormData(event.currentTarget)));setOpen(false);await load()}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível salvar.')}finally{setSaving(false)}};
 return <><PageHeader title={title} description={description} action={config.create===false?undefined:<Button onClick={()=>setOpen(true)}>Novo {config.recordName}</Button>}/>{error?<div className="auth-notice error" role="alert">{error} <button onClick={()=>void load()}>Tentar novamente</button></div>:null}<ContentCard title={title} description="Dados persistidos em entidades próprias, sem module_records.">{loading?<div className="empty-state"><h3>Carregando…</h3></div>:items.length?<div className="table-shell"><table><thead><tr><th>Identificação</th><th>Detalhes</th><th>Status</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{config.titleOf(item)}</strong></td><td>{config.detailOf(item)}</td><td>{config.statusOf?<Pill tone="brand">{config.statusOf(item)}</Pill>:'—'}</td></tr>)}</tbody></table></div>:<EmptyState title={`Nenhum ${config.recordName}`} description={config.create===false?'Os registros aparecem automaticamente pelo fluxo operacional.':`Cadastre o primeiro ${config.recordName}.`} action={config.create===false?undefined:<Button onClick={()=>setOpen(true)}>Novo {config.recordName}</Button>}/>}</ContentCard><Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={submit} title={`Novo ${config.recordName}`} submitLabel={saving?'Salvando…':'Salvar'}>{config.fields.map(field=><Field key={field.name} label={field.label} name={field.name} type={field.type} required={field.required}>{field.options?<select name={field.name} required={field.required}>{field.required?null:<option value="">Selecione</option>}{field.options.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>:field.relation?<select name={field.name} required={field.required}><option value="">Selecione</option>{(relations[field.relation.endpoint]??[]).map(row=><option value={row.id} key={row.id}>{field.relation!.label(row)}</option>)}</select>:undefined}</Field>)}</Modal></>;
}
