import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { api, ApiError } from '../lib/api';

type Row=Record<string,unknown>&{id:string};
type Relation={endpoint:string;label:(row:Row)=>string};
type FieldConfig={name:string;label:string;type?:string;required?:boolean;options?:Array<[string,string]>;relation?:Relation};
type Config={endpoint:string;recordName:string;fields:FieldConfig[];create?:boolean;mapPayload:(form:FormData)=>unknown;titleOf:(row:Row)=>string;detailOf:(row:Row)=>string;statusOf?:(row:Row)=>string;filter?:(row:Row)=>boolean;submit?:(form:FormData)=>Promise<unknown>};
const text=(form:FormData,key:string)=>String(form.get(key)??'').trim();const num=(form:FormData,key:string)=>Number(form.get(key)??0);const nullable=(value:string)=>value||undefined;
const configs:Record<string,Config>={
 categories:{endpoint:'/api/v1/categories',recordName:'categoria',fields:[{name:'name',label:'Nome',required:true},{name:'description',label:'Descrição'},{name:'sortOrder',label:'Ordem',type:'number'}],mapPayload:f=>({name:text(f,'name'),description:nullable(text(f,'description')),sortOrder:num(f,'sortOrder')}),titleOf:r=>String(r.name??'Categoria'),detailOf:r=>String(r.description??'Sem descrição'),statusOf:r=>r.active===false?'Inativa':'Ativa'},
 variations:{endpoint:'/api/v1/variations',recordName:'variação',fields:[{name:'productId',label:'Produto',required:true,relation:{endpoint:'/api/v1/products',label:r=>String(r.name??'Produto')}},{name:'name',label:'Variação',required:true},{name:'sku',label:'SKU'},{name:'barcode',label:'Código de barras'},{name:'salePrice',label:'Preço de venda',type:'number'},{name:'costPrice',label:'Custo',type:'number'}],mapPayload:f=>({productId:text(f,'productId'),name:text(f,'name'),sku:nullable(text(f,'sku')),barcode:nullable(text(f,'barcode')),salePrice:num(f,'salePrice')||undefined,costPrice:num(f,'costPrice')||undefined,attributes:{}}),titleOf:r=>`${String(r.product_name??'Produto')} · ${String(r.name??'Variação')}`,detailOf:r=>`${String(r.sku??'Sem SKU')} · R$ ${Number(r.sale_price??0).toFixed(2)}`,statusOf:r=>r.active===false?'Inativa':'Ativa'},
 addons:{endpoint:'/api/v1/addons',recordName:'adicional',fields:[{name:'name',label:'Nome',required:true},{name:'price',label:'Preço',type:'number'}],mapPayload:f=>({name:text(f,'name'),price:num(f,'price')}),titleOf:r=>String(r.name??'Adicional'),detailOf:r=>`R$ ${Number(r.price??0).toFixed(2)}`,statusOf:r=>r.active===false?'Inativo':'Ativo'},
 combos:{endpoint:'/api/v1/combos',recordName:'combo',fields:[{name:'name',label:'Nome',required:true},{name:'description',label:'Descrição'},{name:'salePrice',label:'Preço',type:'number',required:true},{name:'productId',label:'Produto do combo',required:true,relation:{endpoint:'/api/v1/products',label:r=>String(r.name??'Produto')}},{name:'quantity',label:'Quantidade',type:'number',required:true}],mapPayload:f=>({name:text(f,'name'),description:nullable(text(f,'description')),salePrice:num(f,'salePrice'),items:[{productId:text(f,'productId'),quantity:num(f,'quantity')||1}]}),titleOf:r=>String(r.name??'Combo'),detailOf:r=>`${String(r.description??'')} · R$ ${Number(r.sale_price??0).toFixed(2)}`,statusOf:r=>r.active===false?'Inativo':'Ativo'},
 coupons:{endpoint:'/api/v1/coupons',recordName:'cupom',fields:[{name:'code',label:'Código',required:true},{name:'discountType',label:'Tipo',options:[['percent','Percentual'],['fixed','Valor fixo']]},{name:'discountValue',label:'Desconto',type:'number',required:true},{name:'minimumAmount',label:'Compra mínima',type:'number'},{name:'expiresAt',label:'Validade',type:'datetime-local'}],mapPayload:f=>({code:text(f,'code'),discountType:text(f,'discountType')||'percent',discountValue:num(f,'discountValue'),minimumAmount:num(f,'minimumAmount')||undefined,expiresAt:text(f,'expiresAt')?new Date(text(f,'expiresAt')).toISOString():undefined}),titleOf:r=>String(r.code??'Cupom'),detailOf:r=>`${String(r.discount_type??'')} · ${Number(r.discount_value??0).toFixed(2)} · usos ${String(r.usage_count??0)}`,statusOf:r=>r.active===false?'Inativo':'Ativo'},
 delivery_fees:{endpoint:'/api/v1/delivery-fees',recordName:'região de entrega',fields:[{name:'name',label:'Região',required:true},{name:'neighborhood',label:'Bairro'},{name:'postalCodePrefix',label:'Prefixo CEP'},{name:'fee',label:'Taxa',type:'number',required:true},{name:'minimumAmount',label:'Pedido mínimo',type:'number'},{name:'estimatedMinutes',label:'Prazo (min)',type:'number'}],mapPayload:f=>({name:text(f,'name'),neighborhood:nullable(text(f,'neighborhood')),postalCodePrefix:nullable(text(f,'postalCodePrefix')),fee:num(f,'fee'),minimumAmount:num(f,'minimumAmount')||undefined,estimatedMinutes:num(f,'estimatedMinutes')||undefined}),titleOf:r=>String(r.name??'Região'),detailOf:r=>`${String(r.neighborhood??r.postal_code_prefix??'')} · R$ ${Number(r.fee??0).toFixed(2)} · ${String(r.estimated_minutes??'—')} min`,statusOf:r=>r.active===false?'Inativa':'Ativa'},
 quotes:{endpoint:'/api/v1/quotes',recordName:'orçamento',fields:[{name:'customerId',label:'Cliente',relation:{endpoint:'/api/v1/customers',label:r=>String(r.name??'Cliente')}},{name:'serviceOrderId',label:'OS',relation:{endpoint:'/api/v1/service-orders',label:r=>`OS #${String(r.number??'')}`}},{name:'title',label:'Título',required:true},{name:'description',label:'Item/serviço',required:true},{name:'quantity',label:'Quantidade',type:'number',required:true},{name:'unitPrice',label:'Valor unitário',type:'number',required:true},{name:'discount',label:'Desconto',type:'number'},{name:'validUntil',label:'Validade',type:'date'}],mapPayload:f=>({customerId:nullable(text(f,'customerId')),serviceOrderId:nullable(text(f,'serviceOrderId')),title:text(f,'title'),discount:num(f,'discount'),validUntil:nullable(text(f,'validUntil')),items:[{itemType:'labor',description:text(f,'description'),quantity:num(f,'quantity')||1,unitPrice:num(f,'unitPrice')}]}),titleOf:r=>`Orçamento #${String(r.number??'')} · ${String(r.title??'')}`,detailOf:r=>`${String(r.customer_name??'Sem cliente')} · R$ ${Number(r.total??0).toFixed(2)}`,statusOf:r=>String(r.status??'')},
 business_hours:{endpoint:'/api/v1/business-hours',recordName:'horário',fields:[{name:'weekday',label:'Dia',options:[['0','Domingo'],['1','Segunda'],['2','Terça'],['3','Quarta'],['4','Quinta'],['5','Sexta'],['6','Sábado']]},{name:'opensAt',label:'Abre',type:'time'},{name:'closesAt',label:'Fecha',type:'time'},{name:'breakStartsAt',label:'Início intervalo',type:'time'},{name:'breakEndsAt',label:'Fim intervalo',type:'time'},{name:'closed',label:'Situação',options:[['false','Aberto'],['true','Fechado']]}],mapPayload:f=>({opensAt:nullable(text(f,'opensAt')),closesAt:nullable(text(f,'closesAt')),breakStartsAt:nullable(text(f,'breakStartsAt')),breakEndsAt:nullable(text(f,'breakEndsAt')),closed:text(f,'closed')==='true'}),submit:f=>api.put(`/api/v1/business-hours/${text(f,'weekday')}`,{opensAt:nullable(text(f,'opensAt')),closesAt:nullable(text(f,'closesAt')),breakStartsAt:nullable(text(f,'breakStartsAt')),breakEndsAt:nullable(text(f,'breakEndsAt')),closed:text(f,'closed')==='true'}),titleOf:r=>['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'][Number(r.weekday??0)]??'Dia',detailOf:r=>r.closed?'Fechado':`${String(r.opens_at??'—')} às ${String(r.closes_at??'—')}`,statusOf:r=>r.closed?'Fechado':'Aberto'},
 insurance:{endpoint:'/api/v1/insurance',recordName:'convênio',fields:[{name:'name',label:'Nome',required:true},{name:'code',label:'Código'},{name:'rules',label:'Regras/observações'}],mapPayload:f=>({name:text(f,'name'),code:nullable(text(f,'code')),rules:nullable(text(f,'rules'))}),titleOf:r=>String(r.name??'Convênio'),detailOf:r=>`${String(r.code??'')} · ${String(r.rules??'')}`,statusOf:r=>r.active===false?'Inativo':'Ativo'},
 notices:{endpoint:'/api/v1/notices',recordName:'aviso',fields:[{name:'title',label:'Título',required:true},{name:'message',label:'Mensagem',required:true},{name:'audience',label:'Público',options:[['all','Todos'],['students','Alunos'],['team','Equipe']]},{name:'publish',label:'Publicar agora',options:[['true','Sim'],['false','Não']]}],mapPayload:f=>({title:text(f,'title'),message:text(f,'message'),audience:text(f,'audience')||'all',publish:text(f,'publish')==='true'}),titleOf:r=>String(r.title??'Aviso'),detailOf:r=>String(r.message??''),statusOf:r=>String(r.status??'')},
 teachers:{endpoint:'/api/v1/professionals',recordName:'professor',fields:[{name:'displayName',label:'Nome',required:true}],mapPayload:f=>({displayName:text(f,'displayName')}),titleOf:r=>String(r.display_name??'Professor'),detailOf:r=>r.user_id?'Vinculado a usuário':'Cadastro profissional',statusOf:r=>r.active===false?'Inativo':'Ativo'},
 students:{endpoint:'/api/v1/enrollments',recordName:'matrícula',fields:[{name:'customerId',label:'Aluno/cliente',required:true,relation:{endpoint:'/api/v1/customers',label:r=>String(r.name??'Cliente')}},{name:'planId',label:'Plano',required:true,relation:{endpoint:'/api/v1/membership-plans',label:r=>String(r.name??'Plano')}},{name:'startsOn',label:'Início',type:'date',required:true},{name:'nextDueDate',label:'Próximo vencimento',type:'date'}],mapPayload:f=>({customerId:text(f,'customerId'),planId:text(f,'planId'),startsOn:text(f,'startsOn'),nextDueDate:nullable(text(f,'nextDueDate'))}),titleOf:r=>String(r.customer_name??'Aluno'),detailOf:r=>`${String(r.plan_name??'Plano')} · próximo venc. ${String(r.next_due_date??'—')}`,statusOf:r=>String(r.status??'')},
 pickup:{endpoint:'/api/v1/orders',recordName:'pedido para retirada',fields:[],create:false,mapPayload:()=>({}),filter:r=>String(r.channel)==='pickup',titleOf:r=>`Retirada #${String(r.id).slice(0,8)}`,detailOf:r=>`${String(r.customer_name??'Consumidor final')} · R$ ${Number(r.total??0).toFixed(2)}`,statusOf:r=>String(r.status??'')},
 menu:{endpoint:'/api/v1/products',recordName:'item de cardápio',fields:[],create:false,mapPayload:()=>({}),titleOf:r=>String(r.name??'Produto'),detailOf:r=>`R$ ${Number(r.sale_price??0).toFixed(2)}`,statusOf:r=>r.active===false?'Inativo':'Ativo'},
};
export const SECONDARY_OPERATIONAL_MODULES=new Set(Object.keys(configs));

export function SecondaryOperationalModulePage({moduleKey,title,description}:{moduleKey:string;title:string;description:string}){
 const config=configs[moduleKey];const[items,setItems]=useState<Row[]>([]),[relations,setRelations]=useState<Record<string,Row[]>>({}),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const relationFields=useMemo(()=>config?.fields.filter(x=>x.relation)??[],[config]);
 const load=useCallback(async()=>{if(!config)return;setLoading(true);setError('');try{const main=await api.get<{data:Row[]}>(config.endpoint);setItems(config.filter?main.data.filter(config.filter):main.data);const unique=[...new Map(relationFields.map(field=>[field.relation!.endpoint,field.relation!])).entries()];const values=await Promise.all(unique.map(([endpoint])=>api.get<{data:Row[]}>(endpoint)));setRelations(Object.fromEntries(unique.map(([endpoint],index)=>[endpoint,values[index]?.data??[]])))}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar o módulo.')}finally{setLoading(false)}},[config,relationFields]);
 useEffect(()=>{void load()},[load]);if(!config)return <><PageHeader title={title} description={description}/><EmptyState title="Módulo indisponível" description="Não há adaptador operacional para este recurso."/></>;
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);setSaving(true);setError('');try{if(config.submit)await config.submit(form);else await api.post(config.endpoint,config.mapPayload(form));setOpen(false);await load()}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível salvar.')}finally{setSaving(false)}};
 return <><PageHeader title={title} description={description} action={config.create===false?undefined:<Button onClick={()=>setOpen(true)}>Novo {config.recordName}</Button>}/>{error?<div className="auth-notice error">{error}</div>:null}<ContentCard title={title} description="Recurso operacional persistido em entidade própria.">{loading?<div className="empty-state"><h3>Carregando…</h3></div>:items.length?<div className="table-shell"><table><thead><tr><th>Identificação</th><th>Detalhes</th><th>Status</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{config.titleOf(item)}</strong></td><td>{config.detailOf(item)}</td><td>{config.statusOf?<Pill tone="brand">{config.statusOf(item)}</Pill>:'—'}</td></tr>)}</tbody></table></div>:<EmptyState title={`Nenhum ${config.recordName}`} description="Os dados aparecerão aqui quando cadastrados." action={config.create===false?undefined:<Button onClick={()=>setOpen(true)}>Novo {config.recordName}</Button>}/>}</ContentCard><Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={submit} title={`Novo ${config.recordName}`} submitLabel={saving?'Salvando…':'Salvar'}>{config.fields.map(field=><Field key={field.name} label={field.label} name={field.name} type={field.type} required={field.required}>{field.options?<select name={field.name} required={field.required}>{field.options.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>:field.relation?<select name={field.name} required={field.required}><option value="">Selecione</option>{(relations[field.relation.endpoint]??[]).map(row=><option key={row.id} value={row.id}>{field.relation!.label(row)}</option>)}</select>:undefined}</Field>)}</Modal></>;
}
