import { and, eq } from 'drizzle-orm';
import { Hono } from 'hono';
import { businessDomains, businessPublicProfiles, businesses, createDb, moduleRecords, products, services } from '@nexoio/db';

type Env={Bindings:{DATABASE_URL:string}};
type Section={type:'hero'|'about'|'services'|'benefits'|'gallery'|'testimonials'|'location'|'faq'|'contact';title?:string;text?:string;items?:Array<{title:string;text?:string;price?:string;image?:string}>};
type Theme={product?:'landing_page'|'professional_site'|'store_system';template?:string;sections?:Section[]};
type Seo={title?:string;description?:string};
const app=new Hono<Env>();
const reserved=new Set(['nexoio.com.br','www.nexoio.com.br','app.nexoio.com.br','admin.nexoio.com.br','api.nexoio.com.br','app-staging.nexoio.com.br','admin-staging.nexoio.com.br','api-staging.nexoio.com.br']);
const escape=(value:string)=>value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]!));
const safeUrl=(value:string|undefined)=>{try{const url=new URL(value??'');return ['https:','http:'].includes(url.protocol)?url.toString():''}catch{return''}};
const renderItems=(items:Section['items']=[])=>`<div class="cards">${items.map(item=>`<article>${item.image?`<img src="${escape(safeUrl(item.image))}" alt="">`:''}<h3>${escape(item.title)}</h3>${item.text?`<p>${escape(item.text)}</p>`:''}${item.price?`<strong>${escape(item.price)}</strong>`:''}</article>`).join('')}</div>`;
const renderSection=(section:Section)=>`<section id="${section.type}" class="section section-${section.type}"><div class="wrap"><span>${escape(section.type==='about'?'Sobre':section.type==='services'?'Serviços':section.type==='benefits'?'Benefícios':section.type==='gallery'?'Galeria':section.type==='testimonials'?'Depoimentos':section.type==='location'?'Localização':section.type==='faq'?'Perguntas frequentes':'Contato')}</span>${section.title?`<h2>${escape(section.title)}</h2>`:''}${section.text?`<p>${escape(section.text)}</p>`:''}${renderItems(section.items)}</div></section>`;

app.get('*',async c=>{
  const host=new URL(c.req.url).hostname.toLowerCase();if(reserved.has(host))return c.notFound();const db=createDb(c.env.DATABASE_URL);const suffix=host.endsWith('.staging.nexoio.com.br')?'.staging.nexoio.com.br':'.nexoio.com.br';let businessId:string|undefined;
  if(host.endsWith(suffix)){const slug=host.slice(0,-suffix.length);if(!/^[a-z0-9-]+$/.test(slug))return c.notFound();businessId=(await db.select({id:businesses.id}).from(businesses).where(and(eq(businesses.publicSlug,slug),eq(businesses.status,'active'))).limit(1))[0]?.id}else{businessId=(await db.select({id:businessDomains.businessId}).from(businessDomains).where(and(eq(businessDomains.hostname,host),eq(businessDomains.verificationStatus,'verified'))).limit(1))[0]?.id}
  if(!businessId)return c.notFound();const site=(await db.select({name:businesses.displayName,segment:businesses.businessType,primary:businesses.primaryColor,phone:businesses.whatsapp,headline:businessPublicProfiles.headline,description:businessPublicProfiles.description,whatsapp:businessPublicProfiles.whatsappUrl,address:businessPublicProfiles.addressJson,theme:businessPublicProfiles.themeJson,seo:businessPublicProfiles.seoJson}).from(businesses).innerJoin(businessPublicProfiles,eq(businessPublicProfiles.businessId,businesses.id)).where(and(eq(businesses.id,businessId),eq(businessPublicProfiles.published,true))).limit(1))[0];if(!site)return c.notFound();
  const [productRows,serviceRows,menuRows]=await Promise.all([db.select({title:products.name,text:products.description,price:products.salePrice}).from(products).where(and(eq(products.businessId,businessId),eq(products.active,true))).limit(24),db.select({title:services.name,text:services.description,price:services.price}).from(services).where(and(eq(services.businessId,businessId),eq(services.active,true))).limit(24),db.select({title:moduleRecords.name,text:moduleRecords.details,data:moduleRecords.dataJson}).from(moduleRecords).where(and(eq(moduleRecords.businessId,businessId),eq(moduleRecords.moduleCode,site.segment==='restaurant'||site.segment==='snackbar'?'menu':'promotions'))).limit(24)]);const theme=(site.theme??{})as Theme;const seo=(site.seo??{})as Seo;const title=escape(seo.title??site.name);const headline=escape(site.headline??site.name);const description=escape(seo.description??site.description??'Conheça nossos serviços e fale com nossa equipe.');const color=/^#[0-9a-f]{6}$/i.test(site.primary??'')?site.primary!:'#6548e8';const whatsapp=safeUrl(site.whatsapp??(site.phone?`https://wa.me/${site.phone.replace(/\D/g,'')}`:''));const publicItems=(site.segment==='restaurant'||site.segment==='snackbar'?menuRows:site.segment==='salon'||site.segment==='beauty'||site.segment==='barbershop'||site.segment==='service_provider'||site.segment==='clinic'?serviceRows:productRows).map(item=>({title:item.title,text:item.text??undefined,price:'price'in item&&item.price?`R$ ${Number(item.price).toLocaleString('pt-BR',{minimumFractionDigits:2})}`:undefined}));const configured=theme.sections?.filter(section=>section.type!=='hero').map(section=>section.type==='services'&&!section.items?.length?{...section,items:publicItems}:section);const sections=configured??[{type:'about',title:'Sobre nós',text:site.description??'Atendimento próximo, profissional e feito para você.'} satisfies Section,{type:'contact',title:'Vamos conversar?',text:'Entre em contato para tirar dúvidas ou solicitar atendimento.'} satisfies Section];
  c.header('cache-control','public, max-age=300, s-maxage=900');c.header('content-security-policy',"default-src 'none'; style-src 'unsafe-inline'; img-src https: data:; connect-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'");
  return c.html(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><style>:root{--brand:${color};--ink:#17151f;--muted:#6f6978}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font:16px/1.6 system-ui;color:var(--ink);background:#fbfaff}a{text-decoration:none;color:inherit}.wrap{width:min(1120px,calc(100% - 40px));margin:auto}header{padding:22px 0;position:absolute;inset:0 0 auto;z-index:2}nav{display:flex;justify-content:space-between;align-items:center}.brand{font-weight:900;font-size:20px}.button{display:inline-flex;padding:13px 19px;border-radius:13px;background:var(--brand);color:white;font-weight:800}.hero{min-height:82vh;display:grid;align-items:center;padding:120px 0 70px;background:radial-gradient(circle at 85% 15%,color-mix(in srgb,var(--brand) 24%,white),transparent 32%),#f7f5ff}.hero span,.section span{text-transform:uppercase;letter-spacing:.16em;font-size:11px;font-weight:900;color:var(--brand)}h1{font-size:clamp(3rem,8vw,6.5rem);line-height:.98;letter-spacing:-.065em;max-width:900px;margin:18px 0}h2{font-size:clamp(2rem,5vw,3.6rem);letter-spacing:-.05em;margin:12px 0}.hero p,.section>.wrap>p{font-size:1.15rem;color:var(--muted);max-width:720px}.actions{display:flex;gap:12px;margin-top:28px}.section{padding:82px 0}.section:nth-child(even){background:white}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:28px}.cards article{border:1px solid #e8e4ef;border-radius:20px;padding:22px;background:white}.cards img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:13px}.cards h3{margin:14px 0 6px}.cards p{color:var(--muted)}footer{padding:28px 0;background:#17151f;color:#aaa4b4}.footer-row{display:flex;justify-content:space-between;gap:20px}@media(max-width:720px){.cards{grid-template-columns:1fr}.hero{min-height:720px}.footer-row{display:block}}</style></head><body><header><nav class="wrap"><a class="brand" href="#">${escape(site.name)}</a>${whatsapp?`<a class="button" href="${escape(whatsapp)}" rel="noreferrer">Falar no WhatsApp</a>`:''}</nav></header><main><section class="hero"><div class="wrap"><span>${theme.product==='professional_site'?'Site profissional':theme.product==='store_system'?'Site e sistema':'Página oficial'}</span><h1>${headline}</h1><p>${escape(site.description??description)}</p><div class="actions">${whatsapp?`<a class="button" href="${escape(whatsapp)}" rel="noreferrer">Conversar agora</a>`:''}<a class="button" style="background:white;color:var(--ink);border:1px solid #e1ddec" href="#services">Ver serviços</a></div></div></section>${sections.map(renderSection).join('')}</main><footer><div class="wrap footer-row"><strong>${escape(site.name)}</strong><span>Site criado com Nexoio</span></div></footer></body></html>`);
});
export default app;
