import { and, eq, sql } from 'drizzle-orm';
import { Hono } from 'hono';
import { businessDomains,businessPublicProfiles,businesses,createDb,products,services } from '@nexoio/db';
import { publicSiteCsp,renderPublicSite,type PublicItem,type PublicSection,type PublicTheme } from '@nexoio/site-renderer';
import { publicInteractionRoutes } from './interactions';

type Env={Bindings:{DATABASE_URL:string}};
const app=new Hono<Env>();
const reserved=new Set(['nexoio.com.br','www.nexoio.com.br','app.nexoio.com.br','admin.nexoio.com.br','api.nexoio.com.br','app-staging.nexoio.com.br','admin-staging.nexoio.com.br','api-staging.nexoio.com.br']);
const money=(value:string|null|undefined)=>value?Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):undefined;
const rows=(r:any)=>r?.rows??r??[];
async function resolveBusiness(c:any){const host=new URL(c.req.url).hostname.toLowerCase();if(reserved.has(host))return null;const db=createDb(c.env.DATABASE_URL);if(host.endsWith('.nexoio.com.br')){const label=host.slice(0,-'.nexoio.com.br'.length);const slug=label.endsWith('-staging')?label.slice(0,-8):label;if(!/^[a-z0-9-]+$/.test(slug))return null;return (await db.select({id:businesses.id}).from(businesses).where(and(eq(businesses.publicSlug,slug),eq(businesses.status,'active'))).limit(1))[0]?.id??null;}return (await db.select({id:businessDomains.businessId}).from(businessDomains).where(and(eq(businessDomains.hostname,host),eq(businessDomains.verificationStatus,'verified'))).limit(1))[0]?.id??null;}
async function loadSite(c:any,businessId:string){const db=createDb(c.env.DATABASE_URL);const site=(await db.select({name:businesses.displayName,segment:businesses.businessType,primary:businesses.primaryColor,phone:businesses.whatsapp,headline:businessPublicProfiles.headline,description:businessPublicProfiles.description,whatsapp:businessPublicProfiles.whatsappUrl,instagram:businessPublicProfiles.instagramUrl,address:businessPublicProfiles.addressJson,theme:businessPublicProfiles.themeJson,seo:businessPublicProfiles.seoJson}).from(businesses).innerJoin(businessPublicProfiles,eq(businessPublicProfiles.businessId,businesses.id)).where(and(eq(businesses.id,businessId),eq(businessPublicProfiles.published,true))).limit(1))[0];if(!site)return null;const [productRows,serviceRows,integrationRows]=await Promise.all([db.select({id:products.id,title:products.name,text:products.description,price:products.salePrice}).from(products).where(and(eq(products.businessId,businessId),eq(products.active,true))).limit(60),db.select({id:services.id,title:services.name,text:services.description,price:services.price}).from(services).where(and(eq(services.businessId,businessId),eq(services.active,true))).limit(60),db.execute(sql`select google_analytics_id,meta_pixel_id,google_maps_url,whatsapp_url,instagram_url from public_site_integrations where business_id=${businessId}::uuid limit 1`)]);return {site,products:productRows.map(i=>({id:i.id,title:i.title,text:i.text??undefined,price:money(i.price)})),services:serviceRows.map(i=>({id:i.id,title:i.title,text:i.text??undefined,price:money(i.price)})),integration:(rows(integrationRows)[0]??{}) as any};}
function addressText(value:unknown){if(typeof value==='string')return value;if(value&&typeof value==='object'){const v=value as Record<string,unknown>;return String(v.formatted??[v.street,v.number,v.neighborhood,v.city,v.state].filter(Boolean).join(', '));}return''}
function hydrateSections(theme:PublicTheme,segment:string,products:PublicItem[],services:PublicItem[],headline:string,description:string,whatsapp:string,path:string){const pages=(theme.pages??[]).filter(p=>p.enabled);const current=pages.find(p=>(p.slug||'')===path)??(path===''?pages[0]:undefined);if(pages.length&&!current)return null;const source=current?.blocks??theme.sections??[];const dynamic=segment==='restaurant'||segment==='snackbar'?products:segment==='salon'||segment==='beauty'||segment==='barbershop'||segment==='service_provider'||segment==='clinic'?services:products;let sections=source.filter(s=>s.enabled!==false).map(s=>{if(s.items?.length)return s;if(s.type==='products'||s.type==='menu')return {...s,items:products};if(s.type==='services'||s.type==='pricing'||s.type==='plans')return {...s,items:services};if(s.type==='promotion')return {...s,items:dynamic.slice(0,8)};return s});if(!sections.some(s=>s.type==='hero'))sections=[{type:'hero',title:headline,text:description,buttonText:whatsapp?'Falar no WhatsApp':'',buttonUrl:whatsapp},...sections];if(sections.length===1)sections.push({type:'form',title:'Fale conosco',text:'Envie seus dados e nossa equipe entra em contato.'});return {sections,pages,current};}

app.route('/api',publicInteractionRoutes);
app.get('/robots.txt',async c=>{const id=await resolveBusiness(c);if(!id)return c.notFound();const origin=new URL(c.req.url).origin;return c.text(`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`,200,{'content-type':'text/plain; charset=utf-8','cache-control':'public,max-age=3600'});});
app.get('/sitemap.xml',async c=>{const id=await resolveBusiness(c);if(!id)return c.notFound();const loaded=await loadSite(c,id);if(!loaded)return c.notFound();const theme=(loaded.site.theme??{}) as PublicTheme;const origin=new URL(c.req.url).origin;const pages=(theme.pages??[]).filter(p=>p.enabled);const urls=(pages.length?pages:[{slug:''} as any]).map(p=>`<url><loc>${origin}/${String(p.slug??'').replace(/^\//,'')}</loc></url>`).join('');return c.body(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`,200,{'content-type':'application/xml; charset=utf-8','cache-control':'public,max-age=3600'});});
app.get('*',async c=>{const businessId=await resolveBusiness(c);if(!businessId)return c.notFound();const loaded=await loadSite(c,businessId);if(!loaded)return c.notFound();const {site,products,services,integration}=loaded;const theme=(site.theme??{}) as PublicTheme;if(theme.scheduledAt&&new Date(theme.scheduledAt).getTime()>Date.now())return c.notFound();const url=new URL(c.req.url),path=url.pathname.replace(/^\/+|\/+$/g,'');const whatsapp=String(integration.whatsapp_url||site.whatsapp||(site.phone?`https://wa.me/${String(site.phone).replace(/\D/g,'')}`:''));const hydrated=hydrateSections(theme,site.segment,products,services,site.headline??site.name,site.description??'',whatsapp,path);if(!hydrated)return c.notFound();const canonical=`${url.origin}${url.pathname}`;const input={name:site.name,headline:site.headline,description:site.description,primaryColor:site.primary,whatsapp,instagram:String(integration.instagram_url||site.instagram||''),address:addressText(site.address),canonicalUrl:canonical,pagePath:url.pathname,theme,seo:(site.seo??{}) as any,sections:hydrated.sections as PublicSection[],pages:hydrated.pages,services,integration:{googleAnalyticsId:integration.google_analytics_id,metaPixelId:integration.meta_pixel_id,googleMapsUrl:integration.google_maps_url,whatsappUrl:whatsapp,instagramUrl:integration.instagram_url||site.instagram}};c.header('cache-control','public,max-age=300,s-maxage=900');c.header('content-security-policy',publicSiteCsp(input));c.header('x-content-type-options','nosniff');c.header('referrer-policy','strict-origin-when-cross-origin');return c.html(renderPublicSite(input));});
export default app;
