import { relations, sql } from 'drizzle-orm';
import { bigint, boolean, char, date, index, integer, jsonb, numeric, pgTable, primaryKey, text, timestamp, unique, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
const money = (name: string) => numeric(name, { precision: 14, scale: 2 });
const quantity = (name: string) => numeric(name, { precision: 14, scale: 3 });

export const platformCompany = pgTable('platform_company', {
  id: uuid().primaryKey(), legalName: text('legal_name').notNull(), tradeName: text('trade_name').notNull(), documentType: text('document_type').notNull(), documentNumber: text('document_number').notNull().unique(), supportEmail: text('support_email'), supportPhone: text('support_phone'), addressJson: jsonb('address_json'), createdAt: createdAt(), updatedAt: updatedAt()
});

export const businesses = pgTable('businesses', {
  id: uuid().primaryKey(), legalName: text('legal_name'), displayName: text('display_name').notNull(), publicSlug: text('public_slug').notNull(), documentType: text('document_type'), documentNumber: text('document_number'), businessType: text('business_type').notNull(), status: text().notNull().default('active'), email: text(), phone: text(), whatsapp: text(), timezone: text().notNull().default('America/Campo_Grande'), locale: text().notNull().default('pt-BR'), currency: char({ length: 3 }).notNull().default('BRL'), logoFileId: uuid('logo_file_id'), primaryColor: text('primary_color'), secondaryColor: text('secondary_color'), customDomain: text('custom_domain').unique(), createdAt: createdAt(), updatedAt: updatedAt()
}, (t) => [uniqueIndex('businesses_slug_uidx').on(sql`lower(${t.publicSlug})`), index('businesses_status_idx').on(t.status)]);

export const businessUnits = pgTable('business_units', {
  id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), name: text().notNull(), code: text(), phone: text(), whatsapp: text(), addressJson: jsonb('address_json'), timezone: text(), active: boolean().notNull().default(true), createdAt: createdAt()
}, (t) => [unique().on(t.businessId, t.code), index('business_units_business_idx').on(t.businessId)]);

export const users = pgTable('users', {
  id: uuid().primaryKey(), authUserId: text('auth_user_id').notNull().unique(), name: text().notNull(), email: text(), phone: text(), status: text().notNull().default('active'), emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }), phoneVerifiedAt: timestamp('phone_verified_at', { withTimezone: true }), lastLoginAt: timestamp('last_login_at', { withTimezone: true }), platformAdmin: boolean('platform_admin').notNull().default(false), mfaEnabled: boolean('mfa_enabled').notNull().default(false), createdAt: createdAt(), updatedAt: updatedAt()
}, (t) => [uniqueIndex('users_email_uidx').on(sql`lower(${t.email})`)]);

// Better Auth owns these credential/session tables. The domain profile above is
// deliberately separate so credentials never leak into business queries.
export const authUsers = pgTable('auth_users', {
  id: text().primaryKey(), name: text().notNull(), email: text().notNull().unique(), emailVerified: boolean('email_verified').notNull().default(false), image: text(), twoFactorEnabled: boolean('two_factor_enabled').notNull().default(false), createdAt: createdAt(), updatedAt: updatedAt()
});
export const authSessions = pgTable('auth_sessions', {
  id: text().primaryKey(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), token: text().notNull().unique(), createdAt: createdAt(), updatedAt: updatedAt(), ipAddress: text('ip_address'), userAgent: text('user_agent'), userId: text('user_id').notNull().references(() => authUsers.id, { onDelete: 'cascade' })
}, (t) => [index('auth_sessions_user_idx').on(t.userId)]);
export const authAccounts = pgTable('auth_accounts', {
  id: text().primaryKey(), accountId: text('account_id').notNull(), providerId: text('provider_id').notNull(), userId: text('user_id').notNull().references(() => authUsers.id, { onDelete: 'cascade' }), accessToken: text('access_token'), refreshToken: text('refresh_token'), idToken: text('id_token'), accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }), refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }), scope: text(), password: text(), createdAt: createdAt(), updatedAt: updatedAt()
}, (t) => [index('auth_accounts_user_idx').on(t.userId)]);
export const authVerifications = pgTable('auth_verifications', {
  id: text().primaryKey(), identifier: text().notNull(), value: text().notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), createdAt: createdAt(), updatedAt: updatedAt()
}, (t) => [index('auth_verifications_identifier_idx').on(t.identifier)]);
export const authTwoFactors = pgTable('auth_two_factors', { id: text().primaryKey(), secret: text().notNull(), backupCodes: text('backup_codes').notNull(), userId: text('user_id').notNull().references(() => authUsers.id, { onDelete: 'cascade' }) }, (t) => [index('auth_two_factors_user_idx').on(t.userId)]);

export const roles = pgTable('roles', { id: uuid().primaryKey(), businessId: uuid('business_id').references(() => businesses.id), code: text().notNull(), name: text().notNull(), isSystem: boolean('is_system').notNull().default(false) }, (t) => [unique().on(t.businessId, t.code)]);
export const permissions = pgTable('permissions', { code: text().primaryKey(), description: text().notNull() });
export const rolePermissions = pgTable('role_permissions', { roleId: uuid('role_id').notNull().references(() => roles.id), permissionCode: text('permission_code').notNull().references(() => permissions.code) }, (t) => [primaryKey({ columns: [t.roleId, t.permissionCode] })]);
export const businessMemberships = pgTable('business_memberships', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), userId: uuid('user_id').notNull().references(() => users.id), roleId: uuid('role_id').notNull().references(() => roles.id), status: text().notNull().default('pending'), invitedAt: timestamp('invited_at',{withTimezone:true}), acceptedAt: timestamp('accepted_at',{withTimezone:true}), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [unique().on(t.businessId, t.userId), index('memberships_user_idx').on(t.userId)]);
export const modules = pgTable('modules', { key: text().primaryKey(), name: text().notNull(), description: text().notNull(), core: boolean().notNull().default(false), dependenciesJson: jsonb('dependencies_json').notNull().default([]), active: boolean().notNull().default(true), createdAt: createdAt() });
export const businessModules = pgTable('business_modules', { id: uuid().notNull(), businessId: uuid('business_id').notNull().references(() => businesses.id), moduleCode: text('module_code').notNull().references(() => modules.key), enabled: boolean().notNull().default(true), source: text().notNull().default('segment_default'), settingsJson: jsonb('settings_json').notNull().default({}), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [primaryKey({ columns: [t.businessId, t.moduleCode] }), unique().on(t.id)]);
export const memberLocations = pgTable('member_locations',{ membershipId:uuid('membership_id').notNull().references(()=>businessMemberships.id,{onDelete:'cascade'}),unitId:uuid('unit_id').notNull().references(()=>businessUnits.id,{onDelete:'cascade'})},t=>[primaryKey({columns:[t.membershipId,t.unitId]})]);
export const onboardingProgress = pgTable('onboarding_progress',{userId:uuid('user_id').primaryKey().references(()=>users.id,{onDelete:'cascade'}),businessId:uuid('business_id').references(()=>businesses.id),step:text().notNull().default('welcome'),dataJson:jsonb('data_json').notNull().default({}),completedAt:timestamp('completed_at',{withTimezone:true}),updatedAt:updatedAt()});
export const memberInvitations = pgTable('member_invitations',{id:uuid().primaryKey(),businessId:uuid('business_id').notNull().references(()=>businesses.id),email:text().notNull(),roleId:uuid('role_id').notNull().references(()=>roles.id),tokenHash:text('token_hash').notNull().unique(),status:text().notNull().default('pending'),invitedBy:uuid('invited_by').notNull().references(()=>users.id),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(),acceptedAt:timestamp('accepted_at',{withTimezone:true}),createdAt:createdAt()},t=>[index('invitations_email_idx').on(t.email,t.status)]);
export const platformAdmins = pgTable('platform_admins',{userId:uuid('user_id').primaryKey().references(()=>users.id),status:text().notNull().default('active'),level:text().notNull().default('admin'),mfaRequired:boolean('mfa_required').notNull().default(true),createdAt:createdAt(),updatedAt:updatedAt()});

export const customers = pgTable('customers', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), unitId: uuid('unit_id').references(() => businessUnits.id), name: text().notNull(), phone: text(), whatsapp: text(), email: text(), cpf: text(), birthDate: date('birth_date'), notes: text(), status: text().notNull().default('active'), totalSpent: money('total_spent').notNull().default('0'), firstPurchaseAt: timestamp('first_purchase_at', { withTimezone: true }), lastPurchaseAt: timestamp('last_purchase_at', { withTimezone: true }), lastServiceAt: timestamp('last_service_at', { withTimezone: true }), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [index('customers_business_idx').on(t.businessId), index('customers_business_name_idx').on(t.businessId, t.name), index('customers_business_phone_idx').on(t.businessId, t.phone), index('customers_business_email_idx').on(t.businessId, t.email)]);
export const customerTags = pgTable('customer_tags', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), name: text().notNull(), color: text() }, (t) => [unique().on(t.businessId, t.name)]);
export const customerTagLinks = pgTable('customer_tag_links', { customerId: uuid('customer_id').notNull().references(() => customers.id), tagId: uuid('tag_id').notNull().references(() => customerTags.id), businessId: uuid('business_id').notNull().references(() => businesses.id) }, (t) => [primaryKey({ columns: [t.customerId, t.tagId] })]);

export const products = pgTable('products', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), sku: text(), barcode: text(), name: text().notNull(), description: text(), salePrice: money('sale_price').notNull().default('0'), costPrice: money('cost_price'), stockControlEnabled: boolean('stock_control_enabled').notNull().default(false), minimumStock: quantity('minimum_stock'), active: boolean().notNull().default(true), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [index('products_business_idx').on(t.businessId), unique().on(t.businessId, t.sku)]);
export const services = pgTable('services', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), name: text().notNull(), description: text(), price: money('price').notNull().default('0'), durationMinutes: integer('duration_minutes'), active: boolean().notNull().default(true), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [index('services_business_idx').on(t.businessId)]);
export const professionals = pgTable('professionals', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), userId: uuid('user_id').references(() => users.id), displayName: text('display_name').notNull(), active: boolean().notNull().default(true), createdAt: createdAt() }, (t) => [index('professionals_business_idx').on(t.businessId)]);
export const professionalServices = pgTable('professional_services', { businessId: uuid('business_id').notNull().references(() => businesses.id), professionalId: uuid('professional_id').notNull().references(() => professionals.id), serviceId: uuid('service_id').notNull().references(() => services.id) }, (t) => [primaryKey({ columns: [t.professionalId, t.serviceId] })]);
export const appointments = pgTable('appointments', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), unitId: uuid('unit_id').references(() => businessUnits.id), customerId: uuid('customer_id').references(() => customers.id), professionalId: uuid('professional_id').references(() => professionals.id), serviceId: uuid('service_id').references(() => services.id), startsAt: timestamp('starts_at', { withTimezone: true }).notNull(), endsAt: timestamp('ends_at', { withTimezone: true }).notNull(), status: text().notNull(), notes: text(), createdBy: uuid('created_by').references(() => users.id), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [index('appointments_business_start_idx').on(t.businessId, t.startsAt), index('appointments_professional_time_idx').on(t.businessId, t.professionalId, t.startsAt, t.endsAt)]);

export const sales = pgTable('sales', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), unitId: uuid('unit_id').references(() => businessUnits.id), customerId: uuid('customer_id').references(() => customers.id), sellerUserId: uuid('seller_user_id').references(() => users.id), status: text().notNull(), subtotal: money('subtotal').notNull(), discount: money('discount').notNull().default('0'), total: money('total').notNull(), notes: text(), createdAt: createdAt(), completedAt: timestamp('completed_at', { withTimezone: true }), cancelledAt: timestamp('cancelled_at', { withTimezone: true }), cancelledBy: uuid('cancelled_by').references(() => users.id), cancellationReason: text('cancellation_reason') }, (t) => [index('sales_business_created_idx').on(t.businessId, t.createdAt)]);
export const saleItems = pgTable('sale_items', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), saleId: uuid('sale_id').notNull().references(() => sales.id), itemType: text('item_type').notNull(), productId: uuid('product_id').references(() => products.id), serviceId: uuid('service_id').references(() => services.id), description: text().notNull(), quantity: quantity('quantity').notNull(), unitPrice: money('unit_price').notNull(), discount: money('discount').notNull().default('0'), total: money('total').notNull() }, (t) => [index('sale_items_sale_idx').on(t.businessId, t.saleId)]);
export const salePayments = pgTable('sale_payments', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), saleId: uuid('sale_id').notNull().references(() => sales.id), method: text().notNull(), amount: money('amount').notNull(), status: text().notNull(), provider: text(), externalReference: text('external_reference'), paidAt: timestamp('paid_at', { withTimezone: true }), createdAt: createdAt() }, (t) => [index('sale_payments_sale_idx').on(t.businessId, t.saleId), unique().on(t.provider, t.externalReference)]);
export const cashSessions = pgTable('cash_sessions', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), unitId: uuid('unit_id').references(() => businessUnits.id), openedBy: uuid('opened_by').notNull().references(() => users.id), closedBy: uuid('closed_by').references(() => users.id), openingAmount: money('opening_amount').notNull().default('0'), closingAmount: money('closing_amount'), status: text().notNull(), openedAt: timestamp('opened_at', { withTimezone: true }).notNull().defaultNow(), closedAt: timestamp('closed_at', { withTimezone: true }) }, (t) => [index('cash_sessions_business_idx').on(t.businessId, t.status)]);
export const cashMovements = pgTable('cash_movements', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), cashSessionId: uuid('cash_session_id').notNull().references(() => cashSessions.id), movementType: text('movement_type').notNull(), amount: money('amount').notNull(), referenceType: text('reference_type'), referenceId: uuid('reference_id'), description: text(), createdBy: uuid('created_by').notNull().references(() => users.id), createdAt: createdAt() }, (t) => [index('cash_movements_session_idx').on(t.businessId, t.cashSessionId)]);
export const inventoryMovements = pgTable('inventory_movements', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), unitId: uuid('unit_id').references(() => businessUnits.id), productId: uuid('product_id').notNull().references(() => products.id), movementType: text('movement_type').notNull(), quantity: quantity('quantity').notNull(), referenceType: text('reference_type'), referenceId: uuid('reference_id'), createdBy: uuid('created_by').references(() => users.id), createdAt: createdAt() }, (t) => [index('inventory_product_idx').on(t.businessId, t.productId, t.createdAt)]);

export const suppliers = pgTable('suppliers', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), name: text().notNull(), documentNumber: text('document_number'), phone: text(), email: text(), createdAt: createdAt() }, (t) => [index('suppliers_business_idx').on(t.businessId)]);
export const purchaseOrders = pgTable('purchase_orders', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), supplierId: uuid('supplier_id').references(() => suppliers.id), status: text().notNull().default('draft'), total: money('total').notNull().default('0'), orderedAt: timestamp('ordered_at', { withTimezone: true }), receivedAt: timestamp('received_at', { withTimezone: true }), createdAt: createdAt() }, (t) => [index('purchase_orders_business_idx').on(t.businessId)]);
export const purchaseOrderItems = pgTable('purchase_order_items', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), purchaseOrderId: uuid('purchase_order_id').notNull().references(() => purchaseOrders.id), productId: uuid('product_id').notNull().references(() => products.id), quantity: quantity('quantity').notNull(), unitCost: money('unit_cost').notNull(), total: money('total').notNull() });
export const payables = pgTable('payables', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), supplierId: uuid('supplier_id').references(() => suppliers.id), description: text().notNull(), amount: money('amount').notNull(), dueDate: date('due_date').notNull(), status: text().notNull(), paidAt: timestamp('paid_at', { withTimezone: true }), createdAt: createdAt() }, (t) => [index('payables_business_due_idx').on(t.businessId, t.dueDate)]);
export const receivables = pgTable('receivables', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), customerId: uuid('customer_id').references(() => customers.id), description: text().notNull(), amount: money('amount').notNull(), dueDate: date('due_date').notNull(), status: text().notNull(), receivedAt: timestamp('received_at', { withTimezone: true }), createdAt: createdAt() }, (t) => [index('receivables_business_due_idx').on(t.businessId, t.dueDate)]);
export const leads = pgTable('leads', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), name: text(), phone: text(), email: text(), source: text(), pipelineStage: text('pipeline_stage').notNull(), assignedUserId: uuid('assigned_user_id').references(() => users.id), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [index('leads_business_stage_idx').on(t.businessId, t.pipelineStage)]);
export const crmActivities = pgTable('crm_activities', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), leadId: uuid('lead_id').references(() => leads.id), customerId: uuid('customer_id').references(() => customers.id), activityType: text('activity_type').notNull(), notes: text(), dueAt: timestamp('due_at', { withTimezone: true }), completedAt: timestamp('completed_at', { withTimezone: true }), createdBy: uuid('created_by').references(() => users.id), createdAt: createdAt() }, (t) => [index('crm_activities_business_due_idx').on(t.businessId, t.dueAt)]);
export const campaigns = pgTable('campaigns', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), name: text().notNull(), channel: text().notNull(), status: text().notNull().default('draft'), contentJson: jsonb('content_json').notNull().default({}), scheduledAt: timestamp('scheduled_at', { withTimezone: true }), createdAt: createdAt() });
export const serviceOrders = pgTable('service_orders', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), customerId: uuid('customer_id').references(() => customers.id), number: bigint({ mode: 'number' }).notNull(), subject: text(), equipmentType: text('equipment_type'), brand: text(), model: text(), serialNumber: text('serial_number'), problemReported: text('problem_reported'), diagnosis: text(), solution: text(), status: text().notNull(), estimatedValue: money('estimated_value'), finalValue: money('final_value'), openedAt: timestamp('opened_at', { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp('completed_at', { withTimezone: true }) }, (t) => [unique().on(t.businessId, t.number)]);

export const businessPublicProfiles = pgTable('business_public_profiles', { businessId: uuid('business_id').primaryKey().references(() => businesses.id), headline: text(), description: text(), instagramUrl: text('instagram_url'), facebookUrl: text('facebook_url'), whatsappUrl: text('whatsapp_url'), addressJson: jsonb('address_json'), themeJson: jsonb('theme_json').notNull().default({}), seoJson: jsonb('seo_json').notNull().default({}), published: boolean().notNull().default(false), updatedAt: updatedAt() });
export const businessDomains = pgTable('business_domains', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), hostname: text().notNull().unique(), verificationStatus: text('verification_status').notNull().default('pending'), sslStatus: text('ssl_status').notNull().default('pending'), createdAt: createdAt() });
export const files = pgTable('files', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), bucket: text().notNull(), objectKey: text('object_key').notNull(), originalName: text('original_name'), mimeType: text('mime_type'), sizeBytes: bigint('size_bytes', { mode: 'number' }), checksumSha256: text('checksum_sha256'), visibility: text().notNull().default('private'), uploadedBy: uuid('uploaded_by').references(() => users.id), createdAt: createdAt() }, (t) => [unique().on(t.bucket, t.objectKey), index('files_business_idx').on(t.businessId)]);
export const notifications = pgTable('notifications', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), userId: uuid('user_id').references(() => users.id), channel: text().notNull(), template: text().notNull(), payload: jsonb().notNull(), status: text().notNull().default('pending'), sentAt: timestamp('sent_at', { withTimezone: true }), createdAt: createdAt() });
export const auditLogs = pgTable('audit_logs', { id: uuid().primaryKey(), businessId: uuid('business_id').references(() => businesses.id), actorUserId: uuid('actor_user_id').references(() => users.id), action: text().notNull(), entityType: text('entity_type'), entityId: uuid('entity_id'), requestId: text('request_id'), ipHash: text('ip_hash'), userAgent: text('user_agent'), beforeJson: jsonb('before_json'), afterJson: jsonb('after_json'), createdAt: createdAt() }, (t) => [index('audit_business_created_idx').on(t.businessId, t.createdAt)]);
export const idempotencyKeys = pgTable('idempotency_keys', { key: text().notNull(), businessId: uuid('business_id').notNull().references(() => businesses.id), operation: text().notNull(), requestHash: text('request_hash'), responseStatus: integer('response_status'), responseBody: jsonb('response_body'), createdAt: createdAt(), expiresAt: timestamp('expires_at', { withTimezone: true }) }, (t) => [primaryKey({ columns: [t.businessId, t.key] })]);
export const webhookEvents = pgTable('webhook_events', { id: uuid().primaryKey(), provider: text().notNull(), externalEventId: text('external_event_id').notNull(), eventType: text('event_type').notNull(), payload: jsonb().notNull(), status: text().notNull().default('pending'), receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(), processedAt: timestamp('processed_at', { withTimezone: true }) }, (t) => [unique().on(t.provider, t.externalEventId)]);

export const plans = pgTable('plans', { id: uuid().primaryKey(), code: text().notNull().unique(), name: text().notNull(), priceMonthly: money('price_monthly').notNull().default('0'), active: boolean().notNull().default(true), createdAt: createdAt() });
export const planFeatures = pgTable('plan_features', { planId: uuid('plan_id').notNull().references(() => plans.id), featureCode: text('feature_code').notNull(), limitValue: bigint('limit_value', { mode: 'number' }), enabled: boolean().notNull().default(true) }, (t) => [primaryKey({ columns: [t.planId, t.featureCode] })]);
export const subscriptions = pgTable('subscriptions', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), planId: uuid('plan_id').notNull().references(() => plans.id), status: text().notNull(), currentPeriodStart: timestamp('current_period_start', { withTimezone: true }), currentPeriodEnd: timestamp('current_period_end', { withTimezone: true }), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [unique().on(t.businessId)]);
export const usageCounters = pgTable('usage_counters', { businessId: uuid('business_id').notNull().references(() => businesses.id), metric: text().notNull(), period: date().notNull(), value: bigint({ mode: 'number' }).notNull().default(0) }, (t) => [primaryKey({ columns: [t.businessId, t.metric, t.period] })]);
export const featureFlags = pgTable('feature_flags', { key: text().primaryKey(), enabled: boolean().notNull().default(false), configJson: jsonb('config_json').notNull().default({}) });
export const businessFeatureFlags = pgTable('business_feature_flags', { businessId: uuid('business_id').notNull().references(() => businesses.id), key: text().notNull().references(() => featureFlags.key), enabled: boolean().notNull(), configJson: jsonb('config_json').notNull().default({}) }, (t) => [primaryKey({ columns: [t.businessId, t.key] })]);

export const privacyPolicyVersions = pgTable('privacy_policy_versions', { id: uuid().primaryKey(), version: text().notNull().unique(), content: text().notNull(), effectiveAt: timestamp('effective_at', { withTimezone: true }).notNull(), createdAt: createdAt() });
export const termsVersions = pgTable('terms_versions', { id: uuid().primaryKey(), version: text().notNull().unique(), content: text().notNull(), effectiveAt: timestamp('effective_at', { withTimezone: true }).notNull(), createdAt: createdAt() });
export const userConsents = pgTable('user_consents', { id: uuid().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), documentType: text('document_type').notNull(), documentVersion: text('document_version').notNull(), ipHash: text('ip_hash'), acceptedAt: timestamp('accepted_at', { withTimezone: true }).notNull().defaultNow() });
export const businessConsents = pgTable('business_consents', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), actorUserId: uuid('actor_user_id').notNull().references(() => users.id), documentType: text('document_type').notNull(), documentVersion: text('document_version').notNull(), acceptedAt: timestamp('accepted_at', { withTimezone: true }).notNull().defaultNow() });
export const dataExportRequests = pgTable('data_export_requests', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), requestedBy: uuid('requested_by').notNull().references(() => users.id), status: text().notNull().default('pending'), completedAt: timestamp('completed_at', { withTimezone: true }), createdAt: createdAt() });
export const dataDeletionRequests = pgTable('data_deletion_requests', { id: uuid().primaryKey(), businessId: uuid('business_id').notNull().references(() => businesses.id), requestedBy: uuid('requested_by').notNull().references(() => users.id), status: text().notNull().default('pending'), legalHoldReason: text('legal_hold_reason'), completedAt: timestamp('completed_at', { withTimezone: true }), createdAt: createdAt() });

export const businessRelations = relations(businesses, ({ many, one }) => ({ units: many(businessUnits), memberships: many(businessMemberships), customers: many(customers), publicProfile: one(businessPublicProfiles) }));
