import type {ButtonHTMLAttributes,HTMLAttributes,InputHTMLAttributes,ReactNode,SelectHTMLAttributes,TextareaHTMLAttributes} from 'react';

export type IconName='search'|'plus'|'close'|'menu'|'chevronDown'|'chevronRight'|'check'|'warning'|'info'|'error'|'calendar'|'clock'|'user'|'users'|'settings'|'home'|'chart'|'cash'|'box'|'store'|'globe'|'edit'|'trash'|'filter'|'more'|'upload'|'download';
const paths:Record<IconName,string>={search:'M21 21l-4.35-4.35m1.35-5.65a7 7 0 11-14 0 7 7 0 0114 0z',plus:'M12 5v14M5 12h14',close:'M6 6l12 12M18 6L6 18',menu:'M4 7h16M4 12h16M4 17h16',chevronDown:'M7 10l5 5 5-5',chevronRight:'M10 7l5 5-5 5',check:'M5 12l4 4L19 6',warning:'M12 9v4m0 4h.01M10.3 4.3L2.6 17.7A2 2 0 004.3 21h15.4a2 2 0 001.7-3.3L13.7 4.3a2 2 0 00-3.4 0z',info:'M12 8h.01M11 12h1v4h1M12 21a9 9 0 100-18 9 9 0 000 18z',error:'M8 8l8 8M16 8l-8 8M12 21a9 9 0 100-18 9 9 0 000 18z',calendar:'M7 3v3m10-3v3M4 9h16M5 5h14a1 1 0 011 1v14H4V6a1 1 0 011-1z',clock:'M12 7v5l3 2M12 21a9 9 0 100-18 9 9 0 000 18z',user:'M12 12a4 4 0 100-8 4 4 0 000 8zm-7 9a7 7 0 0114 0',users:'M9 11a4 4 0 100-8 4 4 0 000 8zm6 10a6 6 0 00-12 0m13-10a3 3 0 100-6m5 11a5 5 0 00-3-4.6',settings:'M12 15.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7zm7.4-3.5a7.8 7.8 0 00-.1-1l2-1.6-2-3.5-2.5 1a8 8 0 00-1.7-1L14.7 3h-4l-.4 2.9a8 8 0 00-1.7 1L6.1 5.9l-2 3.5 2 1.6a8 8 0 000 2L4.1 14.6l2 3.5 2.5-1a8 8 0 001.7 1l.4 2.9h4l.4-2.9a8 8 0 001.7-1l2.5 1 2-3.5-2-1.6c.1-.3.1-.7.1-1z',home:'M3 11l9-8 9 8v10h-6v-6H9v6H3z',chart:'M4 20V10m5 10V4m5 16v-7m5 7V7',cash:'M3 6h18v12H3zM7 10h.01M17 14h.01M12 15a3 3 0 100-6 3 3 0 000 6z',box:'M4 7l8-4 8 4-8 4-8-4zm0 0v10l8 4 8-4V7m-8 4v10',store:'M4 10h16l-2-6H6l-2 6zm1 0v10h14V10m-9 10v-6h4v6',globe:'M12 21a9 9 0 100-18 9 9 0 000 18zm0 0c2 0 3.5-4 3.5-9S14 3 12 3 8.5 7 8.5 12 10 21 12 21zm-8-9h16',edit:'M4 20h4l11-11-4-4L4 16v4zm9-13l4 4',trash:'M4 7h16M9 7V4h6v3m-9 0l1 14h10l1-14M10 11v6m4-6v6',filter:'M4 5h16l-6 7v6l-4 2v-8L4 5z',more:'M5 12h.01M12 12h.01M19 12h.01',upload:'M12 16V4m0 0L7 9m5-5l5 5M5 20h14',download:'M12 4v12m0 0l5-5m-5 5l-5-5M5 20h14'};
export function Icon({name,size=20,className=''}:{name:IconName;size?:number;className?:string}){return <svg className={`nx-icon ${className}`.trim()} width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden><path d={paths[name]}/></svg>}

export function Card({children,className='',...props}:{children:ReactNode;className?:string}&HTMLAttributes<HTMLElement>){return <section className={`nx-card ${className}`.trim()} {...props}>{children}</section>}
export function Stack({children,gap=16,className=''}:{children:ReactNode;gap?:number;className?:string}){return <div className={`nx-stack ${className}`.trim()} style={{gap}}>{children}</div>}
export function Inline({children,gap=8,className=''}:{children:ReactNode;gap?:number;className?:string}){return <div className={`nx-inline ${className}`.trim()} style={{gap}}>{children}</div>}
export function Grid({children,min=240,className=''}:{children:ReactNode;min?:number;className?:string}){return <div className={`nx-grid ${className}`.trim()} style={{gridTemplateColumns:`repeat(auto-fit,minmax(min(${min}px,100%),1fr))`}}>{children}</div>}

export function Field({label,hint,error,required,children}:{label:string;hint?:string;error?:string;required?:boolean;children:ReactNode}){return <label className={`nx-field ${error?'has-error':''}`}><span className="nx-field-label">{label}{required?<b aria-hidden> *</b>:null}</span>{children}{error?<span className="nx-field-error" role="alert">{error}</span>:hint?<span className="nx-field-hint">{hint}</span>:null}</label>}
export function Input(props:InputHTMLAttributes<HTMLInputElement>){return <input className={`nx-input ${props.className??''}`.trim()} {...props}/>}
export function TextArea(props:TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea className={`nx-input nx-textarea ${props.className??''}`.trim()} {...props}/>}
export function Select(props:SelectHTMLAttributes<HTMLSelectElement>){return <select className={`nx-input nx-select ${props.className??''}`.trim()} {...props}/>}
export function SearchInput({value,onChange,placeholder='Buscar…'}:{value:string;onChange:(value:string)=>void;placeholder?:string}){return <div className="nx-search"><Icon name="search" size={18}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} aria-label={placeholder}/></div>}
export function Switch({checked,onChange,label}:{checked:boolean;onChange:(checked:boolean)=>void;label:string}){return <label className="nx-switch"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span aria-hidden/><b>{label}</b></label>}

export function IconButton({icon,label,...props}:{icon:IconName;label:string}&ButtonHTMLAttributes<HTMLButtonElement>){return <button type="button" className={`nx-icon-button ${props.className??''}`.trim()} aria-label={label} title={label} {...props}><Icon name={icon}/></button>}
export function Toolbar({children,className=''}:{children:ReactNode;className?:string}){return <div className={`nx-toolbar ${className}`.trim()}>{children}</div>}
export function FilterBar({children}:{children:ReactNode}){return <div className="nx-filterbar">{children}</div>}
export function Divider(){return <hr className="nx-divider"/>}

export function Modal({open,title,description,children,actions,onClose}:{open:boolean;title:string;description?:string;children?:ReactNode;actions?:ReactNode;onClose:()=>void}){if(!open)return null;return <div className="nx-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="nx-modal" role="dialog" aria-modal="true" aria-labelledby="nx-modal-title"><header><div><h2 id="nx-modal-title">{title}</h2>{description?<p>{description}</p>:null}</div><IconButton icon="close" label="Fechar" onClick={onClose}/></header><div className="nx-modal-body">{children}</div>{actions?<footer>{actions}</footer>:null}</div></div>}
export function Drawer({open,title,children,onClose}:{open:boolean;title:string;children:ReactNode;onClose:()=>void}){return <div className={`nx-drawer-wrap ${open?'open':''}`} aria-hidden={!open}><button className="nx-drawer-backdrop" aria-label="Fechar painel" onClick={onClose}/><aside className="nx-drawer" role="dialog" aria-modal="true"><header><h2>{title}</h2><IconButton icon="close" label="Fechar" onClick={onClose}/></header><div>{children}</div></aside></div>}
export function Tooltip({text,children}:{text:string;children:ReactNode}){return <span className="nx-tooltip" data-tooltip={text}>{children}</span>}

export function Page({children,className=''}:{children:ReactNode;className?:string}){return <div className={`nx-page ${className}`.trim()}>{children}</div>}
export function PageHeader({title,description,eyebrow,actions}:{title:string;description?:string;eyebrow?:string;actions?:ReactNode}){return <header className="nx-page-header"><div>{eyebrow?<span className="nx-eyebrow">{eyebrow}</span>:null}<h1>{title}</h1>{description?<p>{description}</p>:null}</div>{actions?<div className="nx-page-actions">{actions}</div>:null}</header>}
export function PageSection({title,description,actions,children}:{title?:string;description?:string;actions?:ReactNode;children:ReactNode}){return <section className="nx-page-section">{title||actions?<header><div>{title?<h2>{title}</h2>:null}{description?<p>{description}</p>:null}</div>{actions}</header>:null}{children}</section>}
export function ResponsiveStack({children}:{children:ReactNode}){return <div className="nx-responsive-stack">{children}</div>}

export function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="nx-table-shell"><table className="nx-table"><thead><tr>{headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
export function StatusBadge({label,tone='neutral'}:{label:string;tone?:'neutral'|'success'|'warning'|'danger'|'info'|'brand'}){return <span className={`nx-status ${tone}`}>{label}</span>}
export function ProgressBar({value,label}:{value:number;label?:string}){const safe=Math.max(0,Math.min(100,value));return <div className="nx-progress" aria-label={label} role="progressbar" aria-valuenow={safe} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${safe}%`}}/></div>}
export function Pagination({page,totalPages,onChange}:{page:number;totalPages:number;onChange:(page:number)=>void}){if(totalPages<=1)return null;return <nav className="nx-pagination" aria-label="Paginação"><button disabled={page<=1} onClick={()=>onChange(page-1)}>Anterior</button><span>Página {page} de {totalPages}</span><button disabled={page>=totalPages} onClick={()=>onChange(page+1)}>Próxima</button></nav>}
export function Stepper({steps,current}:{steps:string[];current:number}){return <ol className="nx-stepper">{steps.map((step,index)=><li className={index<current?'done':index===current?'active':''} key={step}><span>{index<current?<Icon name="check" size={14}/>:index+1}</span><b>{step}</b></li>)}</ol>}
