import { useMemo, useState, type ChangeEvent, type ReactNode } from 'react';
import { Button, Modal } from './index';
import { Icon, Input, SearchInput } from './experience';

export function ButtonGroup({children,label='Ações'}:{children:ReactNode;label?:string}){return <div className="nx-button-group" role="group" aria-label={label}>{children}</div>}
export function SegmentedControl<T extends string>({items,value,onChange,label}:{items:Array<{value:T;label:string}>;value:T;onChange:(value:T)=>void;label:string}){return <div className="nx-segmented" role="radiogroup" aria-label={label}>{items.map(item=><button type="button" role="radio" aria-checked={value===item.value} className={value===item.value?'active':''} onClick={()=>onChange(item.value)} key={item.value}>{item.label}</button>)}</div>}
export function Checkbox({checked,onChange,label,disabled=false}:{checked:boolean;onChange:(value:boolean)=>void;label:string;disabled?:boolean}){return <label className="nx-choice"><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><span aria-hidden/><b>{label}</b></label>}
export function Radio({checked,onChange,label,name,value}:{checked:boolean;onChange:()=>void;label:string;name:string;value:string}){return <label className="nx-choice radio"><input type="radio" checked={checked} name={name} value={value} onChange={onChange}/><span aria-hidden/><b>{label}</b></label>}
export function Slider({value,min=0,max=100,step=1,onChange,label}:{value:number;min?:number;max?:number;step?:number;onChange:(value:number)=>void;label:string}){return <label className="nx-slider"><span><b>{label}</b><output>{value}</output></span><input type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></label>}
export function ColorPicker({value,onChange,label='Cor'}:{value:string;onChange:(value:string)=>void;label?:string}){return <label className="nx-color"><span>{label}</span><input type="color" value={value} onChange={e=>onChange(e.target.value)}/><code>{value.toUpperCase()}</code></label>}
export function DatePicker({value,onChange,label='Data'}:{value:string;onChange:(value:string)=>void;label?:string}){return <label className="nx-date"><span>{label}</span><Input type="date" value={value} onChange={e=>onChange(e.target.value)}/></label>}
export function TimePicker({value,onChange,label='Horário'}:{value:string;onChange:(value:string)=>void;label?:string}){return <label className="nx-date"><span>{label}</span><Input type="time" value={value} onChange={e=>onChange(e.target.value)}/></label>}
export function DateRangePicker({start,end,onChange}:{start:string;end:string;onChange:(range:{start:string;end:string})=>void}){return <div className="nx-date-range"><DatePicker label="De" value={start} onChange={value=>onChange({start:value,end})}/><DatePicker label="Até" value={end} onChange={value=>onChange({start,end:value})}/></div>}
export function FileUpload({label='Selecionar arquivo',accept,onChange,multiple=false}:{label?:string;accept?:string;multiple?:boolean;onChange:(files:File[])=>void}){const id=useMemo(()=>`file-${Math.random().toString(36).slice(2)}`,[]);const change=(event:ChangeEvent<HTMLInputElement>)=>onChange(Array.from(event.target.files??[]));return <label className="nx-upload" htmlFor={id}><Icon name="upload"/><span><b>{label}</b><small>Escolha no seu dispositivo</small></span><input id={id} type="file" accept={accept} multiple={multiple} onChange={change}/></label>}
export function ImageUpload(props:Omit<Parameters<typeof FileUpload>[0],'accept'>){return <FileUpload {...props} accept="image/png,image/jpeg,image/webp,image/avif"/>}

export function Avatar({name,imageUrl,size=38}:{name:string;imageUrl?:string|null;size?:number}){const initials=name.trim().split(/\s+/).slice(0,2).map(part=>part[0]?.toUpperCase()).join('')||'NX';return <span className="nx-avatar" style={{width:size,height:size}} aria-label={name}>{imageUrl?<img src={imageUrl} alt=""/>:<span>{initials}</span>}</span>}
export function AvatarGroup({people,max=4}:{people:Array<{name:string;imageUrl?:string|null}>;max?:number}){const shown=people.slice(0,max);const remaining=people.length-shown.length;return <div className="nx-avatar-group">{shown.map(person=><Avatar key={person.name} {...person}/>) }{remaining>0?<span className="nx-avatar-more">+{remaining}</span>:null}</div>}
export function Breadcrumb({items}:{items:Array<{label:string;href?:string}>}){return <nav className="nx-breadcrumb" aria-label="Caminho da página"><ol>{items.map((item,index)=><li key={`${item.label}-${index}`}>{item.href?<a href={item.href}>{item.label}</a>:<span aria-current="page">{item.label}</span>}</li>)}</ol></nav>}
export function Banner({title,description,action,tone='info'}:{title:string;description?:string;action?:ReactNode;tone?:'info'|'success'|'warning'|'danger'}){return <div className={`nx-banner ${tone}`} role={tone==='danger'?'alert':'status'}><Icon name={tone==='success'?'check':tone==='warning'?'warning':tone==='danger'?'error':'info'}/><div><strong>{title}</strong>{description?<p>{description}</p>:null}</div>{action?<div className="nx-banner-action">{action}</div>:null}</div>}
export function Loading({label='Carregando…',size='md'}:{label?:string;size?:'sm'|'md'|'lg'}){return <div className={`nx-loading ${size}`} role="status"><span aria-hidden/><b>{label}</b></div>}
export function ConfirmDialog({open,title,description,confirmLabel='Confirmar',cancelLabel='Cancelar',danger=false,onConfirm,onClose}:{open:boolean;title:string;description:string;confirmLabel?:string;cancelLabel?:string;danger?:boolean;onConfirm:()=>void;onClose:()=>void}){return <Modal open={open} title={title} description={description} onClose={onClose} actions={<><Button ghost onClick={onClose}>{cancelLabel}</Button><Button className={danger?'danger':''} onClick={onConfirm}>{confirmLabel}</Button></>}/>} 
export function Dropdown({label,children}:{label:string;children:ReactNode}){return <details className="nx-dropdown"><summary>{label}<Icon name="chevronDown" size={16}/></summary><div className="nx-dropdown-menu">{children}</div></details>}
export function Timeline({items}:{items:Array<{title:string;description?:string;time?:string;status?:'done'|'current'|'pending'}>}){return <ol className="nx-timeline">{items.map((item,index)=><li className={item.status??'pending'} key={`${item.title}-${index}`}><span aria-hidden>{item.status==='done'?<Icon name="check" size={13}/>:null}</span><div><strong>{item.title}</strong>{item.description?<p>{item.description}</p>:null}{item.time?<time>{item.time}</time>:null}</div></li>)}</ol>}
export function ChartContainer({title,description,legend,children}:{title:string;description?:string;legend?:ReactNode;children:ReactNode}){return <section className="nx-chart"><header><div><h3>{title}</h3>{description?<p>{description}</p>:null}</div>{legend}</header><div className="nx-chart-body">{children}</div></section>}

type Command={id:string;label:string;description?:string;keywords?:string;action:()=>void};
export function CommandPalette({open,onClose,commands}:{open:boolean;onClose:()=>void;commands:Command[]}){const[query,setQuery]=useState('');const filtered=commands.filter(command=>`${command.label} ${command.description??''} ${command.keywords??''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));return <Modal open={open} title="Ações rápidas" description="Busque uma página ou ação da Nexoio." onClose={onClose}><div className="nx-command"><SearchInput value={query} onChange={setQuery} placeholder="Buscar ação…"/><div>{filtered.length?filtered.map(command=><button type="button" key={command.id} onClick={()=>{command.action();onClose()}}><span><strong>{command.label}</strong>{command.description?<small>{command.description}</small>:null}</span><Icon name="chevronRight"/></button>):<p>Nenhuma ação encontrada.</p>}</div></div></Modal>}

export function DataTable<T extends Record<string,unknown>>({rows,columns,empty='Nenhum registro encontrado.'}:{rows:T[];columns:Array<{key:keyof T;label:string;render?:(value:T[keyof T],row:T)=>ReactNode}>;empty?:string}){if(!rows.length)return <div className="nx-table-empty">{empty}</div>;return <div className="nx-table-shell"><table className="nx-table"><thead><tr>{columns.map(column=><th key={String(column.key)}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id??index)}>{columns.map(column=><td key={String(column.key)}>{column.render?column.render(row[column.key],row):String(row[column.key]??'—')}</td>)}</tr>)}</tbody></table></div>}
