import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { api, ApiError } from '../lib/api';
import './restaurant-operations.css';
import './cash-reference.css';

type Movement={id:string;movement_type:string;amount:string;description:string|null;created_at:string};
type Session={id:string;opening_amount:string;opened_at:string;opened_by_name:string;movements:Movement[]};
type RestaurantAccount={account_type:'command'|'table';account_id:string;label:string;table_id:string|null;table_number:string|null;opened_at:string;total:number|string;paid:number|string;due:number|string};
const brl=(value:string|number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const incomingTypes=['sale','supply','income'];const outgoingTypes=['withdrawal','expense'];
export function CashPage(){
 const[session,setSession]=useState<Session|null>(null);const[accounts,setAccounts]=useState<RestaurantAccount[]>([]);const[modal,setModal]=useState<'open'|'movement'|'close'|'receive'|null>(null);const[selected,setSelected]=useState<RestaurantAccount|null>(null);const[error,setError]=useState('');const[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{try{setError('');const[response,restaurant]=await Promise.all([api.get<{data:Session|null}>('/api/v1/cash/current'),api.get<{data:RestaurantAccount[]}>('/api/v1/restaurant/accounts').catch(()=>({data:[]}))]);setSession(response.data);setAccounts(restaurant.data)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar o caixa.')}},[]);useEffect(()=>{void load()},[load]);
 const totals=useMemo(()=>{const movements=session?.movements??[];const incoming=movements.filter(x=>incomingTypes.includes(x.movement_type)).reduce((s,x)=>s+Number(x.amount),0);const outgoing=movements.filter(x=>outgoingTypes.includes(x.movement_type)).reduce((s,x)=>s+Number(x.amount),0);return{incoming,outgoing,expected:Number(session?.opening_amount??0)+incoming-outgoing}},[session]);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);setSaving(true);setError('');try{if(modal==='open')await api.post('/api/v1/cash/open',{openingAmount:Number(form.get('amount')??0)});else if(modal==='movement'&&session)await api.post(`/api/v1/cash/${session.id}/movements`,{type:String(form.get('type')),amount:Number(form.get('amount')??0),description:String(form.get('description')??'')});else if(modal==='close'&&session)await api.post(`/api/v1/cash/${session.id}/close`,{closingAmount:Number(form.get('amount')??0)});else if(modal==='receive'&&selected){const endpoint=selected.account_type==='command'?`/api/v1/restaurant/commands/${selected.account_id}/pay`:`/api/v1/restaurant/tables/${selected.account_id}/pay`;await api.post(endpoint,{method:String(form.get('method')??'dinheiro'),amount:Number(form.get('amount')??0)});}setModal(null);setSelected(null);await load()}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível concluir a operação.')}finally{setSaving(false)}};
 const receive=(account:RestaurantAccount)=>{setSelected(account);setModal('receive')};const report=()=>{history.pushState({},'','/financeiro');window.dispatchEvent(new PopStateEvent('popstate'))};
 return <><PageHeader title="Caixa" description="Receba mesas, comandas, vendas e acompanhe a sessão do caixa." action={session?<div className="row-actions"><Button ghost onClick={report}>Ver relatório</Button><Button ghost onClick={()=>setModal('movement')}>Movimentar</Button><Button onClick={()=>setModal('close')}>Fechar caixa</Button></div>:<Button onClick={()=>setModal('open')}>Abrir caixa</Button>}/>
 <section className="cash-reference-grid"><article><span>Status</span><strong className={session?'cash-open':'cash-closed'}>◉ {session?'Aberto':'Fechado'}</strong>{session?<small>Operador: {session.opened_by_name}<br/>Aberto em: {new Date(session.opened_at).toLocaleString('pt-BR')}</small>:<small>Nenhuma sessão ativa</small>}</article><article><span>Saldo inicial</span><strong>{brl(session?.opening_amount??0)}</strong></article><article><span>Entradas</span><strong>{brl(totals.incoming)}</strong><small>Saldo esperado: {brl(totals.expected)}</small></article><article><span>Saídas</span><strong>{brl(totals.outgoing)}</strong></article></section>
 {error?<div className="auth-notice error" role="alert">{error}</div>:null}{accounts.length?<ContentCard title="Contas do restaurante" description="Mesas e comandas com saldo pendente aparecem automaticamente aqui."><div className="cash-restaurant-accounts">{accounts.map(a=><article key={`${a.account_type}-${a.account_id}`}><div><span>{a.account_type==='command'?'Comanda':'Mesa'}</span><strong>{a.label}</strong>{a.table_number&&a.account_type==='command'?<small>Mesa {a.table_number}</small>:null}</div><div><small>Pago {brl(a.paid)}</small><strong>{brl(a.due)}</strong><Button onClick={()=>receive(a)}>Receber</Button></div></article>)}</div></ContentCard>:null}
 <ContentCard title="Sessão atual" description="Movimentos do caixa em operação.">{session?<div className="table-shell"><table><thead><tr><th>Data</th><th>Descrição</th><th>Tipo</th><th>Valor</th></tr></thead><tbody>{session.movements.length?session.movements.map(x=>{const out=outgoingTypes.includes(x.movement_type);return <tr key={x.id}><td>{new Date(x.created_at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</td><td><strong>{x.description||x.movement_type}</strong></td><td>{x.movement_type}</td><td className={out?'cash-value-out':'cash-value-in'}>{out?'-':'+'} {brl(x.amount)}</td></tr>}):<tr><td colSpan={4}>Nenhuma movimentação nesta sessão.</td></tr>}</tbody></table></div>:<div className="merchant-empty"><Pill tone="warning">Caixa fechado</Pill><h3>Abra o caixa para começar</h3><Button onClick={()=>setModal('open')}>Abrir caixa</Button></div>}</ContentCard>
 <Modal open={modal!==null} onClose={()=>!saving&&(setModal(null),setSelected(null))} onSubmit={submit} title={modal==='open'?'Abrir caixa':modal==='close'?'Fechar caixa':modal==='receive'?`Receber ${selected?.label??'conta'}`:'Nova movimentação'} submitLabel={saving?'Salvando…':modal==='receive'?'Confirmar pagamento':'Confirmar'}>{modal==='open'?<Field label="Saldo inicial" name="amount"><input name="amount" type="number" min="0" step="0.01" required/></Field>:modal==='close'?<Field label="Valor contado no caixa" name="amount"><input name="amount" type="number" min="0" step="0.01" required/></Field>:modal==='receive'?<><div className="restaurant-payment-summary"><span>Saldo da conta</span><strong>{brl(selected?.due??0)}</strong></div><Field label="Forma de pagamento" name="method"><select name="method" defaultValue="dinheiro"><option value="dinheiro">Dinheiro</option><option value="pix">Pix</option><option value="cartao_debito">Cartão de débito</option><option value="cartao_credito">Cartão de crédito</option><option value="outro">Outro</option></select></Field><Field label="Valor" name="amount"><input name="amount" type="number" min="0.01" max={Number(selected?.due??0)} step="0.01" defaultValue={Number(selected?.due??0).toFixed(2)} required/></Field></>:<><Field label="Tipo" name="type"><select name="type"><option value="supply">Suprimento</option><option value="withdrawal">Sangria</option><option value="income">Entrada</option><option value="expense">Saída</option></select></Field><Field label="Valor" name="amount"><input name="amount" type="number" min="0.01" step="0.01" required/></Field><Field label="Descrição" name="description" required/></>}</Modal></>;
}
