import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api, ApiError } from '../lib/api';

type Movement={id:string;movement_type:string;amount:string;description:string|null;created_at:string};
type Session={id:string;opening_amount:string;opened_at:string;opened_by_name:string;movements:Movement[]};
const brl=(value:string|number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function CashPage(){
  const[session,setSession]=useState<Session|null>(null);const[modal,setModal]=useState<'open'|'movement'|'close'|null>(null);const[error,setError]=useState('');const[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{try{setError('');const response=await api.get<{data:Session|null}>('/api/v1/cash/current');setSession(response.data)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar o caixa.')}},[]);
  useEffect(()=>{void load()},[load]);
  const totals=useMemo(()=>{const movements=session?.movements??[];const incoming=movements.filter(x=>['sale','supply','income'].includes(x.movement_type)).reduce((s,x)=>s+Number(x.amount),0);const outgoing=movements.filter(x=>['withdrawal','expense'].includes(x.movement_type)).reduce((s,x)=>s+Number(x.amount),0);return{incoming,outgoing,expected:Number(session?.opening_amount??0)+incoming-outgoing}},[session]);
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);setSaving(true);setError('');try{if(modal==='open'){await api.post('/api/v1/cash/open',{openingAmount:Number(form.get('amount')??0)})}else if(modal==='movement'&&session){await api.post(`/api/v1/cash/${session.id}/movements`,{type:String(form.get('type')),amount:Number(form.get('amount')??0),description:String(form.get('description')??'')})}else if(modal==='close'&&session){await api.post(`/api/v1/cash/${session.id}/close`,{closingAmount:Number(form.get('amount')??0)})}setModal(null);await load()}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível concluir a operação.')}finally{setSaving(false)}};
  return <><PageHeader title="Caixa" description="Abertura, sangria, suprimento e fechamento persistidos com auditoria." action={session?<div className="row-actions"><Button ghost onClick={()=>setModal('movement')}>Movimentar</Button><Button onClick={()=>setModal('close')}>Fechar caixa</Button></div>:<Button onClick={()=>setModal('open')}>Abrir caixa</Button>}/><StatGrid items={[{label:'Status',value:session?'Aberto':'Fechado',tone:session?'positive':'warning'},{label:'Saldo inicial',value:brl(session?.opening_amount??0)},{label:'Entradas',value:brl(totals.incoming)},{label:'Saldo esperado',value:brl(totals.expected)}]}/>{error?<div className="auth-notice error" role="alert">{error}</div>:null}<ContentCard title="Sessão atual" description={session?`Aberta por ${session.opened_by_name} em ${new Date(session.opened_at).toLocaleString('pt-BR')}`:'Nenhuma sessão de caixa aberta para você.'}>{session?<div className="money-list">{session.movements.length?session.movements.map(x=><div key={x.id}><span>{x.description||x.movement_type}<small> · {new Date(x.created_at).toLocaleString('pt-BR')}</small></span><strong>{['withdrawal','expense'].includes(x.movement_type)?'-':'+'} {brl(x.amount)}</strong></div>):<p>Nenhuma movimentação nesta sessão.</p>}</div>:<div className="merchant-empty"><Pill tone="warning">Caixa fechado</Pill><h3>Abra o caixa para começar</h3><Button onClick={()=>setModal('open')}>Abrir caixa</Button></div>}</ContentCard><Modal open={modal!==null} onClose={()=>!saving&&setModal(null)} onSubmit={submit} title={modal==='open'?'Abrir caixa':modal==='close'?'Fechar caixa':'Nova movimentação'} submitLabel={saving?'Salvando…':'Confirmar'}>{modal==='open'?<Field label="Saldo inicial" name="amount" type="number" required/>:modal==='close'?<Field label="Valor contado no caixa" name="amount" type="number" required/>:<><Field label="Tipo" name="type"><select name="type"><option value="supply">Suprimento</option><option value="withdrawal">Sangria</option><option value="income">Entrada</option><option value="expense">Saída</option></select></Field><Field label="Valor" name="amount" type="number" required/><Field label="Descrição" name="description" required/></>}</Modal></>;
}
