import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api } from '../lib/api';

type Customer={id:string;name:string;phone:string|null;email:string|null;cpf:string|null;birthDate:string|null;status:string;createdAt:string};
export function CustomersPage(){
 const[items,setItems]=useState<Customer[]>([]),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async(q='')=>{setLoading(true);try{const suffix=q.trim()?`?q=${encodeURIComponent(q.trim())}&limit=100`:'?limit=100';setItems((await api.get<{data:Customer[]}>(`/api/v1/customers${suffix}`)).data);setError('')}catch(e:any){setError(e.message||'Não foi possível carregar os clientes.')}finally{setLoading(false)}};
 useEffect(()=>{const t=setTimeout(()=>void load(query),250);return()=>clearTimeout(t)},[query]);
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api.post('/api/v1/customers',{name:String(f.get('name')||''),phone:String(f.get('phone')||'')||undefined,email:String(f.get('email')||'')||undefined,cpf:String(f.get('cpf')||'')||undefined,birthDate:String(f.get('birthDate')||'')||undefined});setOpen(false);await load(query)}catch(x:any){setError(x.message||'Não foi possível cadastrar o cliente.')}};
 const stats=useMemo(()=>{const now=new Date(),month=now.getMonth(),year=now.getFullYear();const active=items.filter(x=>x.status==='active').length;const recent=items.filter(x=>{const d=new Date(x.createdAt);return d.getMonth()===month&&d.getFullYear()===year}).length;const birthdays=items.filter(x=>x.birthDate&&Number(x.birthDate.slice(5,7))===month+1).length;return{active,recent,birthdays}},[items]);
 return <><PageHeader title="Clientes" description="Cadastre, pesquise e acompanhe sua base real de clientes." action={<Button onClick={()=>setOpen(true)}>Novo cliente</Button>}/><StatGrid items={[{label:'Clientes ativos',value:String(stats.active)},{label:'Novos no mês',value:String(stats.recent)},{label:'Base carregada',value:String(items.length)},{label:'Aniversariantes',value:String(stats.birthdays)}]}/><ContentCard title="Base de clientes" description="Dados salvos no banco da empresa atual." action={<div className="toolbar"><input aria-label="Buscar cliente" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente..."/></div>}>{error?<div className="restaurant-error">{error}</div>:null}{loading&&!items.length?<div className="merchant-empty"><h3>Carregando clientes…</h3></div>:items.length?<div className="table-shell"><table><thead><tr><th>Cliente</th><th>Contato</th><th>CPF</th><th>Cadastro</th><th>Status</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.name}</strong><br/><small>{x.email||'Sem e-mail'}</small></td><td>{x.phone||'—'}</td><td>{x.cpf||'—'}</td><td>{new Date(x.createdAt).toLocaleDateString('pt-BR')}</td><td><Pill tone={x.status==='active'?'success':'warning'}>{x.status==='active'?'Ativo':x.status}</Pill></td></tr>)}</tbody></table></div>:<EmptyState title="Nenhum cliente encontrado" description="Crie o primeiro cliente ou altere a busca." action={<Button onClick={()=>setOpen(true)}>Novo cliente</Button>}/>}<div className="card-footer"><Pill>{items.length} clientes</Pill></div></ContentCard><Modal open={open} onClose={()=>setOpen(false)} onSubmit={create} title="Novo cliente" description="O cliente ficará disponível em agenda, vendas e demais fluxos."><Field label="Nome" name="name" required/><Field label="Telefone" name="phone" type="tel"/><Field label="E-mail" name="email" type="email"/><Field label="CPF" name="cpf"/><Field label="Data de nascimento" name="birthDate" type="date"/></Modal></>;
}
