import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api, ApiError } from '../lib/api';

type Account={id:string;kind:'payable'|'receivable';description:string;amount:string;settled_amount:string;due_date:string;status:string;notes?:string|null};
type Summary={payable_open:string;receivable_open:string;cash_net:string;commissions_pending:string};
const brl=(value:string|number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export function FinancePage(){
  const[items,setItems]=useState<Account[]>([]);const[summary,setSummary]=useState<Summary>({payable_open:'0',receivable_open:'0',cash_net:'0',commissions_pending:'0'});const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[accounts,stats]=await Promise.all([api.get<{data:Account[]}>('/api/v1/finance/accounts'),api.get<{data:Summary}>('/api/v1/finance/summary')]);setItems(accounts.data);setSummary(stats.data)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar o financeiro.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);setSaving(true);setError('');try{const kind=String(form.get('kind'));const payload={description:String(form.get('description')??''),amount:Number(form.get('amount')??0),dueDate:String(form.get('dueDate')??''),notes:String(form.get('notes')??'')};await api.post(kind==='receivable'?'/api/v1/finance/receivables':'/api/v1/finance/payables',payload);setOpen(false);await load()}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível salvar a conta.')}finally{setSaving(false)}};
  const settle=async(item:Account)=>{const remaining=Math.max(0,Number(item.amount)-Number(item.settled_amount));if(remaining<=0)return;const value=prompt(`Valor para ${item.kind==='receivable'?'receber':'pagar'} (saldo ${brl(remaining)}):`,String(remaining));if(value===null)return;const amount=Number(value.replace(',','.'));if(!Number.isFinite(amount)||amount<=0)return;try{await api.post(`/api/v1/finance/${item.kind==='receivable'?'receivables':'payables'}/${item.id}/settle`,{amount});await load()}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível liquidar a conta.')}};
  const overdue=useMemo(()=>items.filter(x=>!['paid','received','cancelled'].includes(x.status)&&new Date(`${x.due_date}T23:59:59`).getTime()<Date.now()).length,[items]);
  return <><PageHeader title="Financeiro" description="Contas a pagar e receber persistidas, auditáveis e separadas por empresa." action={<Button onClick={()=>setOpen(true)}>Nova conta</Button>}/><StatGrid items={[{label:'A receber',value:brl(summary.receivable_open)},{label:'A pagar',value:brl(summary.payable_open)},{label:'Caixa líquido',value:brl(summary.cash_net)},{label:'Vencidas',value:String(overdue),tone:overdue?'warning':undefined}]}/>{error?<div className="auth-notice error" role="alert">{error}</div>:null}<ContentCard title="Contas" description="Liquidações parciais e totais são registradas no backend.">{loading?<div className="empty-state"><h3>Carregando…</h3></div>:items.length?<div className="table-shell"><table><thead><tr><th>Descrição</th><th>Tipo</th><th>Vencimento</th><th>Total</th><th>Em aberto</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=>{const remaining=Math.max(0,Number(x.amount)-Number(x.settled_amount));return <tr key={x.id}><td><strong>{x.description}</strong></td><td><Pill tone={x.kind==='receivable'?'success':'danger'}>{x.kind==='receivable'?'Receber':'Pagar'}</Pill></td><td>{new Date(`${x.due_date}T12:00:00`).toLocaleDateString('pt-BR')}</td><td>{brl(x.amount)}</td><td>{brl(remaining)}</td><td>{x.status}</td><td className="row-actions">{remaining>0?<button onClick={()=>void settle(x)}>{x.kind==='receivable'?'Receber':'Pagar'}</button>:null}</td></tr>})}</tbody></table></div>:<EmptyState title="Nenhuma conta" description="Cadastre a primeira conta a pagar ou receber."/>}</ContentCard><Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={create} title="Nova conta" submitLabel={saving?'Salvando…':'Salvar'}><Field label="Descrição" name="description" required/><Field label="Valor" name="amount" type="number" required/><Field label="Tipo" name="kind"><select name="kind"><option value="receivable">Conta a receber</option><option value="payable">Conta a pagar</option></select></Field><Field label="Vencimento" name="dueDate" type="date" required/><Field label="Observações" name="notes"/></Modal></>;
}
