import { useEffect, useState } from 'react';
import { Button, Pill } from '@nexoio/ui';
import { useSession } from '../auth/SessionProvider';
import { ContentCard } from '../components/ContentCard';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api } from '../lib/api';

type Dashboard={salesToday:number;revenueToday:number;appointmentsToday:number;newCustomersToday:number;activeOrders:number;occupiedTables:number;cashOpen:boolean};
const brl=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function OverviewPage(){
 const session=useSession(),segment=session.activeBusiness?.segment??'other';
 const[data,setData]=useState<Dashboard>({salesToday:0,revenueToday:0,appointmentsToday:0,newCustomersToday:0,activeOrders:0,occupiedTables:0,cashOpen:false}),[error,setError]=useState('');
 useEffect(()=>{let alive=true;const load=async()=>{try{const r=await api.get<{data:Dashboard}>('/api/v1/dashboard');if(alive){setData(r.data);setError('')}}catch(e:any){if(alive)setError(e.message||'Não foi possível carregar os indicadores.')}};void load();const t=setInterval(()=>void load(),20000);return()=>{alive=false;clearInterval(t)}},[]);
 const navigate=(path:string)=>{history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'))};
 const restaurant=['restaurant','snackbar'].includes(segment),appointmentBased=['salon','beauty','barbershop','clinic','studio'].includes(segment);
 const primary=restaurant?{label:'Novo pedido',path:'/pedidos'}:appointmentBased?{label:'Novo agendamento',path:'/agenda'}:{label:'Nova venda',path:'/vendas'};
 const stats=restaurant?[{label:'Pedidos ativos',value:String(data.activeOrders),note:'Operação agora'},{label:'Faturamento hoje',value:brl(data.revenueToday),note:`${data.salesToday} vendas`},{label:'Mesas ocupadas',value:String(data.occupiedTables),note:'Atendimento local'},{label:'Caixa',value:data.cashOpen?'Aberto':'Fechado',note:'Sessão atual',tone:data.cashOpen?'positive' as const:'warning' as const}]:[{label:'Agenda hoje',value:String(data.appointmentsToday),note:'Atendimentos'},{label:'Faturamento hoje',value:brl(data.revenueToday),note:`${data.salesToday} vendas`},{label:'Clientes novos',value:String(data.newCustomersToday),note:'Hoje'},{label:'Caixa',value:data.cashOpen?'Aberto':'Fechado',note:'Sessão atual',tone:data.cashOpen?'positive' as const:'warning' as const}];
 const actions=restaurant?[['Novo pedido','/pedidos'],['Comandas','/comandas'],['Cozinha','/cozinha'],['Caixa','/caixa']]:appointmentBased?[['Novo agendamento','/agenda'],['Novo cliente','/clientes'],['Serviços','/servicos'],['Caixa','/caixa']]:[['Nova venda','/vendas'],['Novo cliente','/clientes'],['Produtos','/produtos'],['Financeiro','/financeiro']];
 return <><PageHeader title="Visão geral" description="Indicadores reais da operação da empresa." action={<Button onClick={()=>navigate(primary.path)}>{primary.label}</Button>}/><StatGrid items={stats}/>{error?<div className="restaurant-error">{error}</div>:null}<div className="merchant-two-columns"><ContentCard title="Operação agora" description="O que merece atenção neste momento."><div className="merchant-empty"><Pill tone={data.activeOrders||data.appointmentsToday?'brand':'success'}>{restaurant?`${data.activeOrders} pedidos ativos`:`${data.appointmentsToday} agendamentos hoje`}</Pill><h3>{restaurant?(data.activeOrders?'Há pedidos em andamento':'Operação sem pedidos pendentes'):(data.appointmentsToday?'Agenda com atendimentos':'Agenda livre hoje')}</h3><p>Os números desta tela vêm do banco e são atualizados automaticamente.</p></div></ContentCard><ContentCard title="Atalhos rápidos" description="Ações principais para sua operação."><div className="quick-actions">{actions.map(([label,path])=><button key={path} onClick={()=>navigate(path)}>{label}</button>)}</div></ContentCard></div><ContentCard title="Resumo do dia" description="Consolidação da atividade registrada."><div className="activity-list"><div><span className="activity-dot"/><p><strong>{brl(data.revenueToday)} faturados hoje</strong><small>{data.salesToday} vendas · {data.newCustomersToday} novos clientes · caixa {data.cashOpen?'aberto':'fechado'}</small></p><time>Atual</time></div></div></ContentCard></>;
}
