import { Button, Pill } from '@nexoio/ui';
import { useSession } from '../auth/SessionProvider';
import { ContentCard } from '../components/ContentCard';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';

type DashboardConfig={primary:{label:string;path:string};stats:Array<{label:string;value:string;note:string;tone?:'positive'|'warning'|'neutral'}>;focus:{title:string;description:string;empty:string};actions:Array<{label:string;path:string}>};
const configs:Record<string,DashboardConfig>={
  restaurant:{primary:{label:'Novo pedido',path:'/pedidos'},stats:[{label:'Pedidos hoje',value:'0',note:'Aguardando movimento'},{label:'Faturamento',value:'R$ 0,00',note:'Hoje'},{label:'Em preparo',value:'0',note:'Cozinha'},{label:'Mesas ocupadas',value:'0',note:'Atendimento no local'}],focus:{title:'Operação agora',description:'Pedidos em preparo, mesas e entregas que precisam de atenção.',empty:'Nenhum pedido em andamento'},actions:[{label:'Novo pedido',path:'/pedidos'},{label:'Abrir comandas',path:'/comandas'},{label:'Ver cozinha',path:'/cozinha'},{label:'Abrir caixa',path:'/caixa'}]},
  snackbar:{primary:{label:'Novo pedido',path:'/pedidos'},stats:[{label:'Pedidos hoje',value:'0',note:'Aguardando movimento'},{label:'Faturamento',value:'R$ 0,00',note:'Hoje'},{label:'Em preparo',value:'0',note:'Cozinha'},{label:'Delivery',value:'0',note:'Pedidos ativos'}],focus:{title:'Operação agora',description:'Pedidos, retirada e delivery em andamento.',empty:'Nenhum pedido em andamento'},actions:[{label:'Novo pedido',path:'/pedidos'},{label:'Ver cozinha',path:'/cozinha'},{label:'Delivery',path:'/delivery'},{label:'Abrir caixa',path:'/caixa'}]},
  salon:{primary:{label:'Novo agendamento',path:'/agenda'},stats:[{label:'Agenda hoje',value:'0',note:'Atendimentos'},{label:'Faturamento',value:'R$ 0,00',note:'Hoje'},{label:'Profissionais',value:'0',note:'Em atendimento'},{label:'Comissões',value:'R$ 0,00',note:'Período atual'}],focus:{title:'Agenda do dia',description:'Próximos clientes e horários dos profissionais.',empty:'Nenhum atendimento agendado'},actions:[{label:'Novo agendamento',path:'/agenda'},{label:'Novo cliente',path:'/clientes'},{label:'Registrar venda',path:'/vendas'},{label:'Ver comissões',path:'/comissoes'}]},
  beauty:{primary:{label:'Novo agendamento',path:'/agenda'},stats:[{label:'Agenda hoje',value:'0',note:'Atendimentos'},{label:'Faturamento',value:'R$ 0,00',note:'Hoje'},{label:'Profissionais',value:'0',note:'Disponíveis'},{label:'Clientes novos',value:'0',note:'Este mês'}],focus:{title:'Agenda do dia',description:'Próximos atendimentos e disponibilidade.',empty:'Nenhum atendimento agendado'},actions:[{label:'Novo agendamento',path:'/agenda'},{label:'Novo cliente',path:'/clientes'},{label:'Serviços',path:'/servicos'},{label:'Abrir caixa',path:'/caixa'}]},
  barbershop:{primary:{label:'Novo agendamento',path:'/agenda'},stats:[{label:'Agenda hoje',value:'0',note:'Atendimentos'},{label:'Faturamento',value:'R$ 0,00',note:'Hoje'},{label:'Barbeiros',value:'0',note:'Em atendimento'},{label:'Comissões',value:'R$ 0,00',note:'Período atual'}],focus:{title:'Agenda do dia',description:'Próximos clientes e horários dos barbeiros.',empty:'Nenhum atendimento agendado'},actions:[{label:'Novo agendamento',path:'/agenda'},{label:'Novo cliente',path:'/clientes'},{label:'Registrar venda',path:'/vendas'},{label:'Ver comissões',path:'/comissoes'}]},
  retail:{primary:{label:'Nova venda',path:'/vendas'},stats:[{label:'Vendas hoje',value:'R$ 0,00',note:'Faturamento'},{label:'Itens vendidos',value:'0',note:'Hoje'},{label:'Estoque baixo',value:'0',note:'Produtos'},{label:'Clientes novos',value:'0',note:'Este mês'}],focus:{title:'Estoque e vendas',description:'Produtos que precisam de atenção e movimentações recentes.',empty:'Nenhum alerta de estoque'},actions:[{label:'Nova venda',path:'/vendas'},{label:'Novo produto',path:'/produtos'},{label:'Ver estoque',path:'/estoque'},{label:'Abrir caixa',path:'/caixa'}]},
  technical_assistance:{primary:{label:'Nova ordem de serviço',path:'/ordens-servico'},stats:[{label:'OS abertas',value:'0',note:'Em andamento'},{label:'Aguardando aprovação',value:'0',note:'Orçamentos'},{label:'Em reparo',value:'0',note:'Equipamentos'},{label:'Prontas',value:'0',note:'Para entrega'}],focus:{title:'Ordens que precisam de atenção',description:'Diagnósticos, aprovações e reparos em andamento.',empty:'Nenhuma ordem pendente'},actions:[{label:'Nova OS',path:'/ordens-servico'},{label:'Novo cliente',path:'/clientes'},{label:'Orçamentos',path:'/orcamentos'},{label:'Peças',path:'/pecas'}]},
  service_provider:{primary:{label:'Novo orçamento',path:'/orcamentos'},stats:[{label:'Orçamentos',value:'0',note:'Em aberto'},{label:'Serviços ativos',value:'0',note:'Em execução'},{label:'Agenda hoje',value:'0',note:'Compromissos'},{label:'Financeiro',value:'R$ 0,00',note:'Recebido hoje'}],focus:{title:'Serviços em andamento',description:'Orçamentos, ordens e compromissos que precisam de atenção.',empty:'Nenhum serviço em andamento'},actions:[{label:'Novo orçamento',path:'/orcamentos'},{label:'Nova OS',path:'/ordens-servico'},{label:'Novo cliente',path:'/clientes'},{label:'Agenda',path:'/agenda'}]},
  gym:{primary:{label:'Novo aluno',path:'/alunos'},stats:[{label:'Alunos ativos',value:'0',note:'Planos vigentes'},{label:'Check-ins hoje',value:'0',note:'Presenças'},{label:'Mensalidades',value:'R$ 0,00',note:'Recebidas hoje'},{label:'Aulas hoje',value:'0',note:'Programadas'}],focus:{title:'Movimento de hoje',description:'Check-ins, aulas e mensalidades que precisam de atenção.',empty:'Nenhum movimento registrado'},actions:[{label:'Novo aluno',path:'/alunos'},{label:'Registrar check-in',path:'/checkin'},{label:'Ver aulas',path:'/turmas'},{label:'Mensalidades',path:'/mensalidades'}]},
  studio:{primary:{label:'Novo aluno',path:'/alunos'},stats:[{label:'Alunos ativos',value:'0',note:'Planos vigentes'},{label:'Aulas hoje',value:'0',note:'Programadas'},{label:'Check-ins',value:'0',note:'Hoje'},{label:'Mensalidades',value:'R$ 0,00',note:'Recebidas hoje'}],focus:{title:'Agenda do studio',description:'Aulas, professores e presença dos alunos.',empty:'Nenhuma aula em andamento'},actions:[{label:'Novo aluno',path:'/alunos'},{label:'Nova aula',path:'/turmas'},{label:'Check-in',path:'/checkin'},{label:'Planos',path:'/planos'}]},
  clinic:{primary:{label:'Novo agendamento',path:'/agenda'},stats:[{label:'Pacientes hoje',value:'0',note:'Agenda'},{label:'Em atendimento',value:'0',note:'Agora'},{label:'Procedimentos',value:'0',note:'Hoje'},{label:'Financeiro',value:'R$ 0,00',note:'Recebido hoje'}],focus:{title:'Agenda clínica',description:'Próximos pacientes e atendimentos do dia.',empty:'Nenhum paciente agendado'},actions:[{label:'Novo agendamento',path:'/agenda'},{label:'Novo paciente',path:'/pacientes'},{label:'Prontuários',path:'/prontuarios'},{label:'Procedimentos',path:'/procedimentos'}]},
};
const fallback:DashboardConfig={primary:{label:'Nova venda',path:'/vendas'},stats:[{label:'Vendas hoje',value:'R$ 0,00',note:'Pronto para começar'},{label:'Agenda hoje',value:'0',note:'Sem conflitos'},{label:'Clientes novos',value:'0',note:'Este mês'},{label:'Caixa',value:'Fechado',note:'Aguardando abertura',tone:'warning'}],focus:{title:'Atividade de hoje',description:'Próximos compromissos e movimentações.',empty:'Nenhuma atividade registrada'},actions:[{label:'Novo cliente',path:'/clientes'},{label:'Novo agendamento',path:'/agenda'},{label:'Registrar venda',path:'/vendas'},{label:'Abrir caixa',path:'/caixa'}]};

export function OverviewPage() {
  const session=useSession();const segment=session.activeBusiness?.segment??'other';const config=configs[segment]??fallback;
  const navigate = (path: string) => { history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); };
  return <>
    <PageHeader title="Visão geral" description="Acompanhe o que precisa de atenção no seu negócio." action={<Button onClick={() => navigate(config.primary.path)}>{config.primary.label}</Button>} />
    <StatGrid items={config.stats} />
    <div className="merchant-two-columns">
      <ContentCard title={config.focus.title} description={config.focus.description}><div className="merchant-empty"><Pill tone="brand">Hoje</Pill><h3>{config.focus.empty}</h3><p>Os dados operacionais aparecerão aqui conforme sua equipe usar a Nexoio.</p></div></ContentCard>
      <ContentCard title="Atalhos rápidos" description="Ações mais importantes para este tipo de negócio."><div className="quick-actions">{config.actions.map(action=><button key={action.path} onClick={() => navigate(action.path)}>{action.label}</button>)}</div></ContentCard>
    </div>
    <ContentCard title="Atividade recente" description="Últimas movimentações da empresa."><div className="activity-list"><div><span className="activity-dot"/><p><strong>Ambiente preparado</strong><small>A estrutura do seu segmento está pronta para receber dados reais.</small></p><time>Agora</time></div></div></ContentCard>
  </>;
}
