import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api } from '../lib/api';

type Product={id:string;name:string;sku:string|null;barcode:string|null;salePrice:string;costPrice:string|null;stockControlEnabled:boolean;minimumStock:string|null;active:boolean};
export function ProductsPage(){
 const[items,setItems]=useState<Product[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{setItems((await api.get<{data:Product[]}>('/api/v1/products')).data);setError('')}catch(e:any){setError(e.message||'Não foi possível carregar produtos.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api.post('/api/v1/products',{name:String(f.get('name')||''),sku:String(f.get('sku')||'')||undefined,barcode:String(f.get('barcode')||'')||undefined,salePrice:Number(f.get('salePrice')||0),costPrice:f.get('costPrice')?Number(f.get('costPrice')):undefined,stockControlEnabled:Boolean(f.get('stockControlEnabled')),minimumStock:f.get('minimumStock')?Number(f.get('minimumStock')):undefined});setOpen(false);await load()}catch(x:any){setError(x.message||'Não foi possível criar o produto.')}};
 const disable=async(id:string)=>{if(!confirm('Desativar este produto?'))return;try{await api.delete(`/api/v1/products/${id}`);await load()}catch(x:any){setError(x.message||'Não foi possível desativar o produto.')}};
 const active=items.filter(x=>x.active).length,controlled=items.filter(x=>x.stockControlEnabled).length;
 return <><PageHeader title="Produtos" description="Catálogo real de produtos, preços e regras de estoque." action={<Button onClick={()=>setOpen(true)}>Novo produto</Button>}/><StatGrid items={[{label:'Produtos ativos',value:String(active)},{label:'Controle de estoque',value:String(controlled)},{label:'Inativos',value:String(items.length-active)},{label:'Total cadastrado',value:String(items.length)}]}/><ContentCard title="Catálogo de produtos" description="Os itens abaixo são lidos diretamente do banco da empresa.">{error?<div className="restaurant-error">{error}</div>:null}{loading&&!items.length?<div className="merchant-empty"><h3>Carregando produtos…</h3></div>:items.length?<div className="table-shell"><table><thead><tr><th>Produto</th><th>SKU</th><th>Preço</th><th>Estoque</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.sku||'—'}</td><td>{Number(x.salePrice).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td>{x.stockControlEnabled?<Pill tone="brand">Controlado</Pill>:<Pill>Sem controle</Pill>}</td><td><Pill tone={x.active?'success':'warning'}>{x.active?'Ativo':'Inativo'}</Pill></td><td className="row-actions">{x.active?<button onClick={()=>void disable(x.id)}>Desativar</button>:null}</td></tr>)}</tbody></table></div>:<EmptyState title="Nenhum produto cadastrado" description="Cadastre o primeiro produto real da empresa." action={<Button onClick={()=>setOpen(true)}>Novo produto</Button>}/>}</ContentCard><Modal open={open} onClose={()=>setOpen(false)} onSubmit={create} title="Novo produto" submitLabel="Cadastrar produto"><Field label="Nome" name="name" required/><Field label="SKU" name="sku"/><Field label="Código de barras" name="barcode"/><Field label="Preço de venda" name="salePrice" type="number" required/><Field label="Preço de custo" name="costPrice" type="number"/><Field label="Estoque mínimo" name="minimumStock" type="number"/><label className="nx-field"><span className="nx-field-label">Controle de estoque</span><input name="stockControlEnabled" type="checkbox" value="1"/></label></Modal></>;
}
