import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api, ApiError } from '../lib/api';

type Product={id:string;name:string;sku?:string|null;barcode?:string|null;description?:string|null;salePrice:string|number;costPrice?:string|number|null;stockControlEnabled:boolean;minimumStock?:string|number|null;active?:boolean};
type Balance={product_id:string;on_hand:string|number;reserved:string|number;available?:string|number};
const brl=(value:number|string|undefined|null)=>Number(value??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export function ProductsPage(){
 const[items,setItems]=useState<Product[]>([]);const[balances,setBalances]=useState<Balance[]>([]);const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 const load=useCallback(async(force=false)=>{setLoading(items.length===0);setError('');try{const products=await api.get<{data:Product[]}>('/api/v1/products',{force});setItems(products.data);const inventory=await api.get<{data:Balance[]}>('/api/v1/inventory/balances',{force}).catch(()=>({data:[]}));setBalances(inventory.data)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar os produtos.')}finally{setLoading(false)}},[items.length]);
 useEffect(()=>{void load()},[load]);
 const stockByProduct=useMemo(()=>{const map=new Map<string,{onHand:number;reserved:number}>();for(const b of balances){const current=map.get(b.product_id)??{onHand:0,reserved:0};current.onHand+=Number(b.on_hand??0);current.reserved+=Number(b.reserved??0);map.set(b.product_id,current)}return map},[balances]);
 const controlled=items.filter(x=>x.stockControlEnabled);const low=controlled.filter(x=>{const s=stockByProduct.get(x.id);return (s?.onHand??0)-(s?.reserved??0)<=Number(x.minimumStock??0)}).length;const unavailable=controlled.filter(x=>{const s=stockByProduct.get(x.id);return (s?.onHand??0)-(s?.reserved??0)<=0}).length;const inventoryValue=items.reduce((sum,x)=>sum+(stockByProduct.get(x.id)?.onHand??0)*Number(x.costPrice??0),0);
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);setError('');try{await api.post('/api/v1/products',{name:String(f.get('name')??'').trim(),sku:String(f.get('sku')??'').trim()||undefined,barcode:String(f.get('barcode')??'').trim()||undefined,description:String(f.get('description')??'').trim()||undefined,salePrice:Number(f.get('salePrice')??0),costPrice:String(f.get('costPrice')??'')===''?undefined:Number(f.get('costPrice')),stockControlEnabled:f.get('stockControlEnabled')==='on',minimumStock:String(f.get('minimumStock')??'')===''?undefined:Number(f.get('minimumStock'))});setOpen(false);await load(true)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível criar o produto.')}finally{setSaving(false)}};
 return <><PageHeader title="Produtos" description="Catálogo único usado por vendas, estoque, cardápio e demais operações." action={<Button onClick={()=>setOpen(true)}>Novo produto</Button>}/><StatGrid items={[{label:'Produtos cadastrados',value:String(items.length)},{label:'Estoque baixo',value:String(low),tone:low?'warning':undefined},{label:'Sem estoque',value:String(unavailable),tone:unavailable?'warning':undefined},{label:'Custo em estoque',value:brl(inventoryValue)}]}/>{error?<div className="auth-notice error" role="alert">{error} <button onClick={()=>void load(true)}>Tentar novamente</button></div>:null}<ContentCard title="Catálogo de produtos" description="O saldo não é digitado aqui: entradas, compras e ajustes são registrados no módulo Estoque." action={<button onClick={()=>void load(true)}>Atualizar</button>}>{loading?<div className="empty-state"><h3>Carregando produtos…</h3></div>:items.length?<div className="table-shell"><table><thead><tr><th>Produto</th><th>SKU / código</th><th>Venda</th><th>Estoque disponível</th><th>Controle</th></tr></thead><tbody>{items.map(x=>{const stock=stockByProduct.get(x.id);const available=(stock?.onHand??0)-(stock?.reserved??0);return <tr key={x.id}><td><strong>{x.name}</strong><br/><small>{x.description||'—'}</small></td><td>{x.sku||x.barcode||'—'}</td><td>{brl(x.salePrice)}</td><td>{x.stockControlEnabled?<Pill tone={available<=Number(x.minimumStock??0)?'warning':'success'}>{available.toLocaleString('pt-BR')}</Pill>:'—'}</td><td>{x.stockControlEnabled?'Estoque físico':'Sem controle'}</td></tr>})}</tbody></table></div>:<EmptyState title="Nenhum produto cadastrado" description="Cadastre o produto aqui e faça o saldo inicial pelo Estoque." action={<Button onClick={()=>setOpen(true)}>Novo produto</Button>}/>}</ContentCard><Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={create} title="Novo produto" description="O produto será persistido no Neon e ficará disponível em todos os módulos habilitados." submitLabel={saving?'Salvando…':'Salvar produto'}><Field label="Nome" name="name" required/><Field label="SKU" name="sku"/><Field label="Código de barras" name="barcode"/><Field label="Descrição" name="description"/><Field label="Preço de venda" name="salePrice" type="number" required/><Field label="Custo" name="costPrice" type="number"/><Field label="Estoque mínimo" name="minimumStock" type="number"/><label className="nx-field"><span className="nx-field-label">Controle de estoque</span><span className="menu-stock-toggle"><input name="stockControlEnabled" type="checkbox"/><span>Reservar e baixar saldo físico quando este produto for vendido</span></span></label></Modal></>}
