import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { api } from '../lib/api';
import { Field, Modal } from '../components/Modal';
import './restaurant.css';

type Product={id:string;name:string;description:string|null;salePrice:string;sku:string|null;active:boolean};
type Order={id:string;status:string;createdAt:string;items:Array<{id:string;productId:string|null;description:string;quantity:string;unitPrice:string;total:string}>;tab:null|{id:string;code:string;channel:string;total:string;fulfillmentJson?:Record<string,unknown>;table?:{code:string}|null}};
const brl=(v:unknown)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const age=(iso:string)=>Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/60000));
const label:Record<string,string>={sent:'Recebido',preparing:'Em preparo',ready:'Pronto',served:'Finalizado',cancelled:'Cancelado'};
const tone=(s:string)=>s==='ready'||s==='served'?'green':s==='preparing'?'amber':s==='cancelled'?'gray':'red';

export function MenuPage(){
 const [items,setItems]=useState<Product[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Product|null>(null),[error,setError]=useState('');
 const load=async()=>{try{setItems((await api.get<{data:Product[]}>('/api/v1/products')).data);setError('')}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),body={name:String(f.get('name')||''),description:String(f.get('description')||''),salePrice:Number(f.get('salePrice')||0),sku:String(f.get('sku')||'')||undefined,active:true};try{if(editing)await api.patch(`/api/v1/products/${editing.id}`,body);else await api.post('/api/v1/products',body);setOpen(false);setEditing(null);await load()}catch(x:any){setError(x.message)}};
 const disable=async(id:string)=>{if(!confirm('Desativar este item do cardápio?'))return;await api.delete(`/api/v1/products/${id}`);await load()};
 return <><div className="restaurant-head"><div><small>NEXOIO</small><h1>Cardápio</h1><p>Itens, preços e disponibilidade reais do catálogo.</p></div><button className="primary-action" onClick={()=>{setEditing(null);setOpen(true)}}>Novo item</button></div>
 <section className="restaurant-panel"><h2>Itens do Cardápio</h2><p>O cardápio usa os produtos reais cadastrados na empresa.</p>{error?<div className="restaurant-error">{error}</div>:null}<div className="menu-grid">{items.map(p=><article key={p.id} className="menu-card"><div className="menu-thumb">{p.name.slice(0,1).toUpperCase()}</div><div className="menu-body"><small>{p.sku||'SEM SKU'}</small><h3>{p.name}</h3><p>{p.description||'Sem descrição'}</p><div className="menu-bottom"><strong>{brl(p.salePrice)}</strong><span className={`status-chip ${p.active?'green':'gray'}`}>● {p.active?'Ativo':'Inativo'}</span></div><div className="operation-actions"><button onClick={()=>{setEditing(p);setOpen(true)}}>Editar</button>{p.active?<button onClick={()=>void disable(p.id)}>Desativar</button>:null}</div></div></article>)}</div>{!items.length?<div className="restaurant-empty">Nenhum item cadastrado.</div>:null}</section>
 <Modal open={open} title={editing?'Editar item':'Novo item'} submitLabel={editing?'Salvar':'Criar item'} onClose={()=>{setOpen(false);setEditing(null)}} onSubmit={submit}><Field label="Nome" name="name" required><input name="name" required defaultValue={editing?.name||''}/></Field><Field label="Descrição" name="description"><input name="description" defaultValue={editing?.description||''}/></Field><Field label="Preço" name="salePrice" type="number"><input name="salePrice" type="number" step="0.01" required defaultValue={editing?.salePrice||''}/></Field><Field label="Código/SKU" name="sku"><input name="sku" defaultValue={editing?.sku||''}/></Field></Modal></>;
}

function FulfillmentPage({channel,title,buttonLabel}:{channel:'pickup'|'delivery';title:string;buttonLabel:string}){
 const [orders,setOrders]=useState<Order[]>([]),[products,setProducts]=useState<Product[]>([]),[open,setOpen]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{const [o,p]=await Promise.all([api.get<{data:Order[]}>('/api/v1/restaurant/orders'),api.get<{data:Product[]}>('/api/v1/products')]);setOrders(o.data.filter(x=>x.tab?.channel===channel));setProducts(p.data.filter(x=>x.active));setError('')}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load();const t=setInterval(()=>void load(),15000);return()=>clearInterval(t)},[]);
 const groups=useMemo(()=>({received:orders.filter(o=>o.status==='sent'),preparing:orders.filter(o=>o.status==='preparing'),ready:orders.filter(o=>o.status==='ready'),done:orders.filter(o=>o.status==='served')}),[orders]);
 const setStatus=async(id:string,status:string)=>{try{await api.patch(`/api/v1/restaurant/orders/${id}/status`,{status});await load()}catch(e:any){setError(e.message)}};
 const assign=async(tabId:string)=>{const courier=prompt('Nome do entregador');if(!courier)return;await api.patch(`/api/v1/restaurant/tabs/${tabId}/fulfillment`,{courierName:courier,deliveryStatus:'assigned'});await load()};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),product=products.find(p=>p.id===String(f.get('productId')));if(!product)return;try{const tab=(await api.post<{data:{id:string}}>('/api/v1/restaurant/tabs',{channel})).data;await api.patch(`/api/v1/restaurant/tabs/${tab.id}/fulfillment`,{customerName:String(f.get('customerName')||'Cliente'),phone:String(f.get('phone')||''),address:channel==='delivery'?String(f.get('address')||''):''});await api.post(`/api/v1/restaurant/tabs/${tab.id}/orders`,{items:[{productId:product.id,description:product.name,quantity:Number(f.get('quantity')||1),unitPrice:Number(product.salePrice)}]});setOpen(false);await load()}catch(x:any){setError(x.message)}};
 const meta=(o:Order)=>(o.tab?.fulfillmentJson||{}) as Record<string,unknown>;
 const card=(o:Order)=><article className={`operation-card ${tone(o.status)}`} key={o.id}><div className="operation-top"><strong>Pedido #{o.tab?.code||o.id.slice(-5)}</strong><span className={`status-chip ${tone(o.status)}`}>{label[o.status]||o.status}</span></div><p><b>Cliente:</b> {String(meta(o).customerName||'Cliente')}</p>{channel==='delivery'?<p><b>Endereço:</b> {String(meta(o).address||'Não informado')}</p>:null}<p><b>Total:</b> {brl(o.tab?.total)}</p><p>◷ {age(o.createdAt)} min</p><div className="operation-actions">{o.status==='sent'?<button onClick={()=>void setStatus(o.id,'preparing')}>Iniciar preparo</button>:null}{o.status==='preparing'?<button onClick={()=>void setStatus(o.id,'ready')}>Marcar pronto</button>:null}{o.status==='ready'&&channel==='pickup'?<button onClick={()=>void setStatus(o.id,'served')}>Entregar retirada</button>:null}{o.status==='ready'&&channel==='delivery'?<><button onClick={()=>o.tab&&void assign(o.tab.id)}>Selecionar entregador</button><button onClick={()=>void setStatus(o.id,'served')}>Confirmar entrega</button></>:null}</div></article>;
 return <><div className="restaurant-head"><div><small>NEXOIO</small><h1>{title}</h1><p>Fluxo integrado com pedidos, cozinha, comanda e venda.</p></div><button className="primary-action" onClick={()=>setOpen(true)}>{buttonLabel}</button></div>{error?<div className="restaurant-error">{error}</div>:null}
 <div className="fulfillment-columns"><section className="restaurant-panel"><h2>Recebidos</h2>{groups.received.map(card)}{!groups.received.length?<div className="restaurant-empty">Nenhum pedido.</div>:null}</section><section className="restaurant-panel"><h2>Em preparo / Cozinha</h2>{groups.preparing.map(card)}{!groups.preparing.length?<div className="restaurant-empty">Nenhum pedido.</div>:null}</section><section className="restaurant-panel"><h2>{channel==='delivery'?'Prontos / Despachar':'Prontos / Retirar'}</h2>{groups.ready.map(card)}{!groups.ready.length?<div className="restaurant-empty">Nenhum pedido.</div>:null}</section></div>
 <Modal open={open} title={buttonLabel} submitLabel="Criar pedido" onClose={()=>setOpen(false)} onSubmit={submit}><Field label="Cliente" name="customerName" required/><Field label="Telefone" name="phone"/><Field label="Produto" name="productId"><select name="productId" required><option value="">Selecione</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — {brl(p.salePrice)}</option>)}</select></Field><Field label="Quantidade" name="quantity" type="number" required/>{channel==='delivery'?<Field label="Endereço" name="address" required/>:null}</Modal></>;
}

export function PickupPage(){return <FulfillmentPage channel="pickup" title="Gestão de Retiradas" buttonLabel="Novo pedido para retirada"/>}
export function DeliveryPage(){return <FulfillmentPage channel="delivery" title="Gestão de Entregas" buttonLabel="Nova entrega"/>}
