import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState } from '@nexoio/ui';
import { PageHeader } from '../components/PageHeader';
import { Field, Modal } from '../components/Modal';
import { api, ApiError } from '../lib/api';
import './restaurant-operations.css';

type Order={id:string;channel:string;status:string;subtotal:number|string;discount:number|string;total:number|string;payment_status?:string;fulfillment_status?:string;customer_name?:string|null;table_number?:string|null;created_at?:string;items?:Array<{id:string;description:string;quantity:number;unitPrice?:number|string;unit_price?:number|string;total:number|string;status?:string}>};
type TableRow={id:string;number:string;status:string};
type Product={id:string;name:string;description?:string|null;salePrice?:string|number;sale_price?:string|number;stockControlEnabled?:boolean;stock_control_enabled?:boolean;minimumStock?:string|number|null;minimum_stock?:string|number|null;sku?:string|null};
type Ticket={id:string;order_id:string;status:string;priority:number;station?:string|null;table_number?:string|null;channel:string;queued_at?:string;items:Array<{description:string;quantity:number;notes?:string|null;status?:string}>};
type Delivery={id:string;order_id:string;status:string;customer_name?:string|null;recipient_name?:string|null;recipient_phone?:string|null;courier_name?:string|null;address_json?:Record<string,unknown>|null;total:number|string;created_at?:string};
const brl=(v:number|string|undefined)=>Number(v??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const minutes=(d?:string)=>d?`${Math.max(0,Math.floor((Date.now()-new Date(d).getTime())/60000))} min`:'agora';
const fail=(e:unknown,fallback:string)=>e instanceof ApiError?e.message:fallback;
const nav=(path:string)=>{history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'))};

export function RestaurantOrdersPage(){
 const[orders,setOrders]=useState<Order[]>([]),[tables,setTables]=useState<TableRow[]>([]);const[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[o,t]=await Promise.all([api.get<{data:Order[]}>('/api/v1/orders'),api.get<{data:TableRow[]}>('/api/v1/tables')]);setOrders(o.data);setTables(t.data)}catch(e){setError(fail(e,'Não foi possível carregar os pedidos.'))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{const tableId=String(f.get('tableId')||'');await api.post('/api/v1/orders',{channel:String(f.get('channel')||'counter'),tableId:tableId||undefined,items:[{description:String(f.get('description')||''),quantity:Number(f.get('quantity')||1),unitPrice:Number(f.get('unitPrice')||0),discount:0}]});setOpen(false);await load()}catch(err){setError(fail(err,'Não foi possível criar o pedido.'))}finally{setSaving(false)}};
 const kitchen=async(id:string)=>{try{await api.post(`/api/v1/orders/${id}/kitchen`,{});await load()}catch(e){setError(fail(e,'Não foi possível enviar para a cozinha.'))}};
 const close=async(id:string)=>{try{await api.post(`/api/v1/orders/${id}/close`,{});await load()}catch(e){setError(fail(e,'Não foi possível fechar o pedido.'))}};
 const active=orders.filter(o=>!['closed','cancelled'].includes(o.status));
 const tone=(o:Order)=>o.fulfillment_status==='ready'||o.status==='closed'?'green':o.fulfillment_status==='preparing'||o.status==='confirmed'?'yellow':o.channel==='delivery'?'blue':'red';
 return <><PageHeader title="Pedidos" description="Pedidos de salão, retirada e delivery." action={<Button onClick={()=>setOpen(true)}>Novo pedido</Button>}/>{error?<div className="auth-notice error">{error}</div>:null}{loading?<div className="restaurant-loading">Carregando pedidos…</div>:active.length?<section className="restaurant-order-grid">{active.map((o,i)=><article key={o.id} className={`order-board-card tone-${tone(o)}`}><div className="order-board-tags"><span>{tone(o)==='red'?'Urgente':tone(o)==='yellow'?'Atenção':tone(o)==='green'?'Pronto':'Normal'}</span><b>{o.fulfillment_status||o.status}</b></div><h2>#{String(o.id).slice(-4).toUpperCase()}</h2><p>◷ {minutes(o.created_at)} | Status: <strong>{o.fulfillment_status||o.status}</strong></p><p>{o.table_number?`Mesa ${o.table_number}`:o.channel==='pickup'?'Retirada (Balcão)':o.channel==='delivery'?'Delivery':'Balcão'}{o.customer_name?` | ${o.customer_name}`:''}</p><div className="order-items-mini">{(o.items||[]).slice(0,3).map(x=><span key={x.id}>{x.quantity}× {x.description}</span>)}</div><div className="order-board-footer"><strong>{brl(o.total)}</strong><div>{!['confirmed'].includes(o.status)&&o.fulfillment_status!=='preparing'&&o.fulfillment_status!=='ready'?<button onClick={()=>void kitchen(o.id)}>Iniciar preparo</button>:null}{o.payment_status==='paid'?<button onClick={()=>void close(o.id)}>Finalizar</button>:null}</div></div></article>)}</section>:<EmptyState title="Nenhum pedido em aberto" description="Crie o primeiro pedido para iniciar a operação." action={<Button onClick={()=>setOpen(true)}>Novo pedido</Button>}/>}<Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={create} title="Novo pedido"><Field label="Canal" name="channel"><select name="channel" defaultValue="table"><option value="table">Mesa</option><option value="counter">Balcão</option><option value="pickup">Retirada</option><option value="delivery">Delivery</option></select></Field><Field label="Mesa" name="tableId"><select name="tableId" defaultValue=""><option value="">Sem mesa</option>{tables.filter(t=>t.status!=='unavailable').map(t=><option key={t.id} value={t.id}>Mesa {t.number}</option>)}</select></Field><Field label="Item" name="description" required/><Field label="Quantidade" name="quantity"><input name="quantity" type="number" min="1" step="1" defaultValue="1" required/></Field><Field label="Preço unitário" name="unitPrice"><input name="unitPrice" type="number" min="0" step="0.01" required/></Field>{saving?<div className="auth-notice">Criando pedido…</div>:null}</Modal></>;
}

export function RestaurantMenuPage(){
 const[items,setItems]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[filter,setFilter]=useState('Todos');
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get<{data:Product[]}>('/api/v1/products');setItems(r.data)}catch(e){setError(fail(e,'Não foi possível carregar o cardápio.'))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{await api.post('/api/v1/products',{name:String(f.get('name')||''),sku:String(f.get('sku')||'')||undefined,description:String(f.get('description')||'')||undefined,salePrice:Number(f.get('salePrice')||0),stockControlEnabled:true,minimumStock:Number(f.get('minimumStock')||0)});setOpen(false);await load()}catch(err){setError(fail(err,'Não foi possível criar o item.'))}finally{setSaving(false)}};
 const visible=filter==='Todos'?items:items.filter(x=>(x.name||'').toLowerCase().includes(filter.toLowerCase()));
 return <><PageHeader title="Cardápio" description="Itens, preços e disponibilidade." action={<Button onClick={()=>setOpen(true)}>Novo item</Button>}/><section className="menu-panel"><div className="menu-panel-head"><h2>Itens do Cardápio</h2><div className="restaurant-toolbar"><button className={filter==='Todos'?'active':''} onClick={()=>setFilter('Todos')}>Todos</button><button onClick={()=>setFilter('Bebida')}>Bebidas</button><button onClick={()=>setFilter('Porção')}>Porções</button><button onClick={()=>setFilter('Sobremesa')}>Sobremesas</button></div></div>{error?<div className="auth-notice error">{error}</div>:null}{loading?<div className="restaurant-loading">Carregando cardápio…</div>:visible.length?<div className="menu-card-grid">{visible.map((p,i)=><article className="menu-item-card" key={p.id}><div className="menu-thumb">{(p.name||'?').slice(0,2).toUpperCase()}</div><div><small>{p.sku||`C${String(i+1).padStart(2,'0')}`}</small><h3>{p.name}</h3><p>{p.description||'Item do cardápio'}</p></div><div className="menu-price-row"><strong>{brl(p.salePrice??p.sale_price)}</strong><span className="menu-active">● Ativo</span></div></article>)}</div>:<EmptyState title="Nenhum item no cardápio" description="Cadastre produtos para montar o cardápio."/>}</section><Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={create} title="Novo item"><Field label="Nome" name="name" required/><Field label="SKU" name="sku"/><Field label="Descrição" name="description"/><Field label="Preço" name="salePrice"><input name="salePrice" type="number" min="0" step="0.01" required/></Field><Field label="Estoque mínimo" name="minimumStock"><input name="minimumStock" type="number" min="0" step="1" defaultValue="0"/></Field></Modal></>;
}

export function RestaurantKitchenPage(){
 const[tickets,setTickets]=useState<Ticket[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);try{const r=await api.get<{data:Ticket[]}>('/api/v1/kitchen');setTickets(r.data)}catch(e){setError(fail(e,'Não foi possível carregar a cozinha.'))}finally{setLoading(false)}},[]);useEffect(()=>{void load();const id=setInterval(()=>void load(),30000);return()=>clearInterval(id)},[load]);const move=async(t:Ticket,status:'preparing'|'ready'|'completed')=>{try{await api.patch(`/api/v1/kitchen/${t.id}`,{status});await load()}catch(e){setError(fail(e,'Não foi possível atualizar o preparo.'))}};
 return <><PageHeader title="Cozinha" description="Fila de preparo e tickets em tempo real." action={<Button ghost onClick={()=>void load()}>Atualizar</Button>}/>{error?<div className="auth-notice error">{error}</div>:null}{loading?<div className="restaurant-loading">Carregando cozinha…</div>:tickets.length?<section className="kitchen-board">{(['queued','preparing','ready'] as const).map(status=><div key={status} className="kitchen-column"><h2>{status==='queued'?'Recebidos':status==='preparing'?'Em preparo':'Prontos'}</h2>{tickets.filter(t=>t.status===status).map(t=><article key={t.id} className={`kitchen-ticket ${status}`}><strong>Pedido #{String(t.order_id).slice(-4).toUpperCase()}</strong><span>{t.table_number?`Mesa ${t.table_number}`:t.channel}</span><div>{t.items.map((x,i)=><p key={i}><b>{x.quantity}×</b> {x.description}{x.notes?<small>{x.notes}</small>:null}</p>)}</div><button onClick={()=>void move(t,status==='queued'?'preparing':status==='preparing'?'ready':'completed')}>{status==='queued'?'Iniciar preparo':status==='preparing'?'Marcar pronto':'Concluir'}</button></article>)}</div>)}</section>:<EmptyState title="Cozinha sem pedidos" description="Os tickets enviados para preparo aparecerão aqui."/>}</>;
}

export function RestaurantPickupPage(){
 const[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);try{const r=await api.get<{data:Order[]}>('/api/v1/orders');setOrders(r.data.filter(o=>o.channel==='pickup'&&!['closed','cancelled'].includes(o.status)))}catch(e){setError(fail(e,'Não foi possível carregar as retiradas.'))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const advance=async(o:Order)=>{try{if(o.fulfillment_status==='ready'){if(o.payment_status!=='paid')throw new Error('Pagamento pendente');await api.post(`/api/v1/orders/${o.id}/close`,{})}else await api.post(`/api/v1/orders/${o.id}/kitchen`,{});await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível avançar a retirada.')}};
 return <><PageHeader title="Gestão de Retiradas" description="Pedidos de balcão organizados por etapa." action={<Button onClick={()=>nav('/pedidos')}>Novo pedido para retirada</Button>}/>{error?<div className="auth-notice error">{error}</div>:null}{loading?<div className="restaurant-loading">Carregando retiradas…</div>:orders.length?<section className="pickup-grid">{orders.map(o=>{const ready=o.fulfillment_status==='ready',prep=o.fulfillment_status==='preparing';return <article key={o.id} className={`pickup-card ${ready?'ready':prep?'preparing':'waiting'}`}><span className="pickup-state">● {ready?'Pronto':prep?'Em preparo':'Aguardando preparo'}</span><h2>R{String(o.id).slice(-3).toUpperCase()}</h2><p>CLIENTE: <b>{o.customer_name||'Consumidor'}</b></p><p>◷ {ready?'Pronto para retirada':minutes(o.created_at)}</p><button onClick={()=>void advance(o)}>{ready?'Avançar retirada':prep?'Visualizar detalhes':'Priorizar preparo'}</button><footer><strong>{brl(o.total)}</strong><span>{o.table_number?`Mesa ${o.table_number}`:'Balcão'}</span></footer></article>})}</section>:<EmptyState title="Nenhuma retirada em andamento" description="Pedidos de retirada aparecerão aqui."/>}</>;
}

export function RestaurantDeliveryPage(){
 const[items,setItems]=useState<Delivery[]>([]),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);const load=useCallback(async()=>{setLoading(true);try{const[d,o]=await Promise.all([api.get<{data:Delivery[]}>('/api/v1/delivery'),api.get<{data:Order[]}>('/api/v1/orders')]);setItems(d.data);setOrders(o.data.filter(x=>!['closed','cancelled'].includes(x.status)))}catch(e){setError(fail(e,'Não foi possível carregar as entregas.'))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const move=async(d:Delivery,status:string)=>{try{await api.patch(`/api/v1/delivery/${d.id}/status`,{status});await load()}catch(e){setError(fail(e,'Não foi possível atualizar a entrega.'))}};const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{const orderId=String(f.get('orderId')||'');await api.post(`/api/v1/orders/${orderId}/delivery`,{address:{line1:String(f.get('address')||'')},recipientName:String(f.get('recipientName')||'')||undefined,recipientPhone:String(f.get('phone')||'')||undefined,deliveryFee:Number(f.get('fee')||0)});setOpen(false);await load()}catch(err){setError(fail(err,'Não foi possível criar a entrega.'))}finally{setSaving(false)}};
 const groups=[{key:'waiting',title:'Pedidos Recebidos'},{key:'preparing',title:'Em Preparo / Cozinha'},{key:'ready',title:'Prontos / Despachar'}];
 return <><PageHeader title="Gestão de Entregas" description="Acompanhe pedidos, preparo e despacho." action={<Button onClick={()=>setOpen(true)}>Nova entrega</Button>}/>{error?<div className="auth-notice error">{error}</div>:null}{loading?<div className="restaurant-loading">Carregando entregas…</div>:<section className="delivery-board">{groups.map(g=><div className={`delivery-column ${g.key}`} key={g.key}><h2>{g.title}</h2>{items.filter(d=>g.key==='waiting'?d.status==='waiting':g.key==='preparing'?['preparing'].includes(d.status):['ready','dispatched'].includes(d.status)).map(d=><article key={d.id}><h3>Pedido #{String(d.order_id).slice(-4).toUpperCase()}</h3><p>Cliente: {d.customer_name||d.recipient_name||'—'}</p><p>Endereço: {String((d.address_json||{}).line1||'—')}</p><p>Total: {brl(d.total)}</p><button onClick={()=>void move(d,d.status==='waiting'?'preparing':d.status==='preparing'?'ready':d.status==='ready'?'dispatched':'delivered')}>{d.status==='waiting'?'Associar / preparar':d.status==='preparing'?'Marcar pronto':d.status==='ready'?'Despachar':'Marcar entregue'}</button></article>)}</div>)}</section>}<Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={create} title="Nova entrega"><Field label="Pedido" name="orderId"><select name="orderId" required defaultValue=""><option value="" disabled>Selecione</option>{orders.map(o=><option key={o.id} value={o.id}>#{String(o.id).slice(-4)} — {brl(o.total)}</option>)}</select></Field><Field label="Destinatário" name="recipientName"/><Field label="Telefone" name="phone"/><Field label="Endereço" name="address" required/><Field label="Taxa de entrega" name="fee"><input name="fee" type="number" min="0" step="0.01" defaultValue="0"/></Field></Modal></>;
}
