import { useCallback, useEffect, useState } from 'react';
import { Button, EmptyState } from '@nexoio/ui';
import { PageHeader } from '../components/PageHeader';
import { api, ApiError } from '../lib/api';
import './restaurant-operations.css';

type Order={id:string;channel:string;status:string;total:number|string;payment_status?:string;fulfillment_status?:string;customer_name?:string|null;table_number?:string|null;created_at?:string};
type Ticket={id:string;order_id:string;status:string;priority:number;station?:string|null;table_number?:string|null;channel:string;queued_at?:string;items:Array<{description:string;quantity:number;notes?:string|null;status?:string}>};
type Delivery={id:string;order_id:string;status:string;customer_name?:string|null;recipient_name?:string|null;recipient_phone?:string|null;courier_name?:string|null;address_json?:Record<string,unknown>|null;total:number|string;payment_status?:string;created_at?:string};
const brl=(v:number|string|undefined)=>Number(v??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const minutes=(d?:string)=>d?`${Math.max(0,Math.floor((Date.now()-new Date(d).getTime())/60000))} min`:'agora';
const fail=(e:unknown,fallback:string)=>e instanceof ApiError?e.message:fallback;
const nav=(path:string)=>{history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'))};

export function RestaurantKitchenPage(){
 const[tickets,setTickets]=useState<Ticket[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await api.get<{data:Ticket[]}>('/api/v1/kitchen');setTickets(r.data)}catch(e){setError(fail(e,'Não foi possível carregar a cozinha.'))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const id=setInterval(()=>void load(),30000);return()=>clearInterval(id)},[load]);
 const move=async(t:Ticket,status:'preparing'|'ready'|'completed')=>{try{await api.patch(`/api/v1/kitchen/${t.id}`,{status});await load()}catch(e){setError(fail(e,'Não foi possível atualizar o preparo.'))}};
 return <><PageHeader title="Cozinha" description="Cada envio do atendimento vira um ticket independente para preparo." action={<Button ghost onClick={()=>void load()}>Atualizar</Button>}/>{error?<div className="auth-notice error">{error}</div>:null}{loading?<div className="restaurant-loading">Carregando cozinha…</div>:tickets.length?<section className="kitchen-board">{(['queued','preparing','ready'] as const).map(status=><div key={status} className="kitchen-column"><h2>{status==='queued'?'Recebidos':status==='preparing'?'Em preparo':'Prontos'}</h2>{tickets.filter(t=>t.status===status).map(t=><article key={t.id} className={`kitchen-ticket ${status}`}><strong>Pedido #{String(t.order_id).slice(-4).toUpperCase()}</strong><span>{t.table_number?`Mesa ${t.table_number}`:t.channel==='pickup'?'Retirada':t.channel==='delivery'?'Delivery':'Balcão'}</span><div>{t.items.map((x,i)=><p key={`${t.id}-${i}`}><b>{x.quantity}×</b> {x.description}{x.notes?<small>{x.notes}</small>:null}</p>)}</div><button onClick={()=>void move(t,status==='queued'?'preparing':status==='preparing'?'ready':'completed')}>{status==='queued'?'Iniciar preparo':status==='preparing'?'Marcar pronto':'Concluir preparo'}</button></article>)}</div>)}</section>:<EmptyState title="Cozinha sem pedidos" description="Os pedidos enviados dos atendimentos aparecerão aqui."/>}</>;
}

export function RestaurantPickupPage(){
 const[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await api.get<{data:Order[]}>('/api/v1/orders');setOrders(r.data.filter(o=>o.channel==='pickup'&&!['closed','cancelled'].includes(o.status)))}catch(e){setError(fail(e,'Não foi possível carregar as retiradas.'))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const action=async(o:Order)=>{if(o.fulfillment_status==='ready'&&o.payment_status!=='paid'){nav(`/caixa?orderId=${o.id}`);return}if(o.fulfillment_status==='ready'&&o.payment_status==='paid'){try{await api.post(`/api/v1/orders/${o.id}/close`,{});await load()}catch(e){setError(fail(e,'Não foi possível concluir a retirada.'))}return}if(o.fulfillment_status==='preparing'){nav('/cozinha');return}try{await api.post(`/api/v1/orders/${o.id}/kitchen`,{});await load()}catch(e){setError(fail(e,'Não foi possível enviar a retirada para preparo.'))}};
 return <><PageHeader title="Gestão de Retiradas" description="Retirada nasce em uma tela própria, passa pela cozinha e segue para recebimento." action={<Button onClick={()=>nav('/atendimento?channel=pickup&from=retirada')}>Nova retirada</Button>}/>{error?<div className="auth-notice error">{error}</div>:null}{loading?<div className="restaurant-loading">Carregando retiradas…</div>:orders.length?<section className="pickup-grid">{orders.map(o=>{const ready=o.fulfillment_status==='ready',prep=o.fulfillment_status==='preparing';const label=ready?(o.payment_status==='paid'?'Entregar e finalizar':'Receber no caixa'):prep?'Acompanhar cozinha':'Enviar para cozinha';return <article key={o.id} className={`pickup-card ${ready?'ready':prep?'preparing':'waiting'}`}><span className="pickup-state">● {ready?'Pronto':prep?'Em preparo':'Aguardando preparo'}</span><h2>R{String(o.id).slice(-3).toUpperCase()}</h2><p>CLIENTE: <b>{o.customer_name||'Consumidor'}</b></p><p>◷ {ready?'Pronto para retirada':minutes(o.created_at)}</p><button onClick={()=>void action(o)}>{label}</button><footer><strong>{brl(o.total)}</strong><span>{o.payment_status==='paid'?'Pago':'Pagamento pendente'}</span></footer></article>})}</section>:<EmptyState title="Nenhuma retirada em andamento" description="Crie a próxima retirada diretamente pelo cardápio." action={<Button onClick={()=>nav('/atendimento?channel=pickup&from=retirada')}>Nova retirada</Button>}/>}</>;
}

export function RestaurantDeliveryPage(){
 const[items,setItems]=useState<Delivery[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const d=await api.get<{data:Delivery[]}>('/api/v1/delivery');setItems(d.data.filter(x=>x.status!=='cancelled'&&x.status!=='delivered'))}catch(e){setError(fail(e,'Não foi possível carregar as entregas.'))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const move=async(d:Delivery,status:string)=>{try{await api.patch(`/api/v1/delivery/${d.id}/status`,{status});await load()}catch(e){setError(fail(e,'Não foi possível atualizar a entrega.'))}};
 const groups=[{key:'waiting',title:'Pedidos recebidos'},{key:'preparing',title:'Em preparo / cozinha'},{key:'ready',title:'Prontos / entrega'}];
 return <><PageHeader title="Gestão de Entregas" description="O pedido, endereço e taxa são criados juntos; aqui você acompanha preparo e despacho." action={<Button onClick={()=>nav('/atendimento?channel=delivery&from=delivery')}>Novo delivery</Button>}/>{error?<div className="auth-notice error">{error}</div>:null}{loading?<div className="restaurant-loading">Carregando entregas…</div>:items.length?<section className="delivery-board">{groups.map(g=><div className={`delivery-column ${g.key}`} key={g.key}><h2>{g.title}</h2>{items.filter(d=>g.key==='waiting'?d.status==='waiting':g.key==='preparing'?d.status==='preparing':['ready','dispatched'].includes(d.status)).map(d=><article key={d.id}><h3>Pedido #{String(d.order_id).slice(-4).toUpperCase()}</h3><p>Cliente: {d.customer_name||d.recipient_name||'—'}</p><p>Endereço: {String((d.address_json||{}).line1||'—')}</p><p>Total: <strong>{brl(d.total)}</strong></p><p>{d.payment_status==='paid'?'Pago':'Pagamento pendente'}</p>{d.status==='ready'&&d.payment_status!=='paid'?<button onClick={()=>nav(`/caixa?orderId=${d.order_id}`)}>Receber no caixa</button>:<button onClick={()=>void move(d,d.status==='waiting'?'preparing':d.status==='preparing'?'ready':d.status==='ready'?'dispatched':'delivered')}>{d.status==='waiting'?'Iniciar preparo':d.status==='preparing'?'Marcar pronto':d.status==='ready'?'Despachar':'Marcar entregue'}</button>}</article>)}</div>)}</section>:<EmptyState title="Nenhum delivery em andamento" description="Crie o próximo delivery diretamente no cardápio e informe o endereço na mesma tela." action={<Button onClick={()=>nav('/atendimento?channel=delivery&from=delivery')}>Novo delivery</Button>}/>}</>;
}
