import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { api } from '../lib/api';
import { Modal, Field } from '../components/Modal';
import './restaurant.css';

type TableRow={id:string;code:string;capacity:number;area:string|null;status:'free'|'occupied'|'closing';occupiedAt:string|null;currentTab:null|{id:string;code:string;total:string;openedAt:string;status:string}};
type TabRow={id:string;code:string;tableId:string|null;channel:string;status:string;total:string;openedAt:string;requestedClosureAt:string|null;table:null|{id:string;code:string;area:string|null}};
type TabDetail=TabRow&{subtotal:string;discount:string;orders:Array<{id:string;status:string;items:Array<{id:string;description:string;quantity:string;unitPrice:string;total:string;status:string}>}>;payments:Array<{id:string;method:string;amount:string;status:string}>};
const brl=(v:unknown)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const mins=(iso?:string|null)=>iso?Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/60000)):0;
const statusLabel:Record<string,string>={free:'Livre',occupied:'Ocupada',closing:'Fechamento',active:'Ativa',awaiting_closure:'Aguardando fechamento',payment_processing:'Pagamento processando',paid:'Paga',closed:'Finalizada',cancelled:'Cancelada'};
const tone=(status:string)=>status==='free'||status==='active'?'green':status==='closing'||status==='awaiting_closure'?'amber':status==='occupied'||status==='payment_processing'?'red':'gray';

export function TablesPage(){
 const [rows,setRows]=useState<TableRow[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[err,setErr]=useState('');
 const load=async()=>{setLoading(true);try{setRows((await api.get<{data:TableRow[]}>('/api/v1/restaurant/tables')).data)}catch(e:any){setErr(e.message||'Erro ao carregar mesas')}finally{setLoading(false)}};
 useEffect(()=>{void load();const t=setInterval(()=>void load(),15000);return()=>clearInterval(t)},[]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api.post('/api/v1/restaurant/tables',{code:f.get('code'),capacity:Number(f.get('capacity')||4),area:f.get('area')});setOpen(false);await load()}catch(x:any){setErr(x.message)}};
 return <><div className="restaurant-head"><div><small>NEXOIO</small><h1>Mesas</h1><p>Ocupação e atendimento por mesa.</p></div><button className="primary-action" onClick={()=>setOpen(true)}>Nova mesa</button></div>
 <section className="restaurant-panel"><h2>Mesas cadastradas</h2><p>Dados reais da empresa atual, sincronizados com as comandas.</p>{err?<div className="restaurant-error">{err}</div>:null}{loading&&!rows.length?<div className="restaurant-empty">Carregando mesas…</div>:null}<div className="table-grid">{rows.map(r=><article key={r.id} className={`restaurant-card ${tone(r.status)}`}><span className={`status-chip ${tone(r.status)}`}>● {statusLabel[r.status]||r.status}</span><div className="table-code"><span className="table-icon">{r.status==='occupied'?'♟♟':'▱'}</span>{r.code.padStart(2,'0')}</div><div className="card-meta">{r.currentTab?<><span>◷ {mins(r.occupiedAt||r.currentTab.openedAt)} min</span><span>{brl(r.currentTab.total)}</span></>:null}<span>Capacidade: {r.capacity}</span>{r.area?<span>{r.area}</span>:null}</div>{r.currentTab?<a className="card-link" href="/comandas">Comanda {r.currentTab.code}</a>:null}</article>)}</div>{!loading&&!rows.length?<div className="restaurant-empty">Nenhuma mesa cadastrada. Crie a primeira mesa.</div>:null}</section>
 <Modal open={open} title="Nova mesa" description="Cadastre uma mesa real para esta empresa." submitLabel="Criar mesa" onClose={()=>setOpen(false)} onSubmit={submit}><Field label="Número/código" name="code" required/><Field label="Capacidade" name="capacity" type="number" required/><Field label="Setor/local" name="area" placeholder="Ex.: Salão frente"/></Modal></>;
}

export function TabsPage(){
 const [rows,setRows]=useState<TabRow[]>([]),[tables,setTables]=useState<TableRow[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[detail,setDetail]=useState<TabDetail|null>(null),[err,setErr]=useState('');
 const load=async()=>{setLoading(true);try{const [a,b]=await Promise.all([api.get<{data:TabRow[]}>('/api/v1/restaurant/tabs'),api.get<{data:TableRow[]}>('/api/v1/restaurant/tables')]);setRows(a.data);setTables(b.data)}catch(e:any){setErr(e.message||'Erro ao carregar comandas')}finally{setLoading(false)}};
 useEffect(()=>{void load();const t=setInterval(()=>void load(),15000);return()=>clearInterval(t)},[]);
 const active=useMemo(()=>rows.filter(r=>r.status!=='closed'&&r.status!=='cancelled'),[rows]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api.post('/api/v1/restaurant/tabs',{code:f.get('code')||undefined,tableId:f.get('tableId')||null,channel:f.get('channel')||'table'});setOpen(false);await load()}catch(x:any){setErr(x.message)}};
 const show=async(id:string)=>{try{setDetail((await api.get<{data:TabDetail}>(`/api/v1/restaurant/tabs/${id}`)).data)}catch(x:any){setErr(x.message)}};
 const closure=async()=>{if(!detail)return;await api.post(`/api/v1/restaurant/tabs/${detail.id}/request-closure`);setDetail(null);await load()};
 const pay=async()=>{if(!detail)return;const amount=prompt('Valor recebido',String(detail.total));if(!amount)return;const method=prompt('Forma de pagamento (dinheiro, pix, debito, credito)','dinheiro')||'dinheiro';try{await api.post(`/api/v1/restaurant/tabs/${detail.id}/payments`,{amount:Number(amount.replace(',','.')),method});setDetail((await api.get<{data:TabDetail}>(`/api/v1/restaurant/tabs/${detail.id}`)).data);await load()}catch(x:any){setErr(x.message)}};
 const close=async()=>{if(!detail)return;try{await api.post(`/api/v1/restaurant/tabs/${detail.id}/close`);setDetail(null);await load()}catch(x:any){setErr(x.message)}};
 return <><div className="restaurant-head"><div><small>NEXOIO</small><h1>Comandas</h1><p>Controle e vinculação de comandas.</p></div><button className="primary-action" onClick={()=>setOpen(true)}>Nova comanda</button></div>
 <section className="restaurant-panel"><h2>Comandas cadastradas</h2><p>Consumo real integrado a mesas, pedidos, cozinha, vendas e estoque.</p>{err?<div className="restaurant-error">{err}</div>:null}<div className="tab-grid">{active.map(r=><button key={r.id} className={`restaurant-card tab-card ${tone(r.status)}`} onClick={()=>void show(r.id)}><span className={`status-chip ${tone(r.status)}`}>● {statusLabel[r.status]||r.status}</span><div className="tab-code">▤ <strong>{r.code}</strong></div><div className="card-meta"><span>{brl(r.total)}</span><span>◷ {mins(r.openedAt)} min</span><span>{r.table?`Mesa ${r.table.code}`:r.channel==='delivery'?'Delivery':'Balcão'}</span></div></button>)}</div>{!loading&&!active.length?<div className="restaurant-empty">Nenhuma comanda aberta.</div>:null}</section>
 <Modal open={open} title="Nova comanda" description="A comanda ocupará a mesa selecionada automaticamente." submitLabel="Abrir comanda" onClose={()=>setOpen(false)} onSubmit={submit}><Field label="Código" name="code" placeholder="Gerado automaticamente se vazio"/><Field label="Mesa" name="tableId"><select name="tableId"><option value="">Balcão / sem mesa</option>{tables.filter(t=>t.status==='free').map(t=><option key={t.id} value={t.id}>Mesa {t.code}{t.area?` — ${t.area}`:''}</option>)}</select></Field><Field label="Canal" name="channel"><select name="channel" defaultValue="table"><option value="table">Mesa</option><option value="counter">Balcão</option><option value="delivery">Delivery</option></select></Field></Modal>
 {detail?<div className="detail-overlay" onMouseDown={e=>e.currentTarget===e.target&&setDetail(null)}><aside className="detail-drawer"><button className="drawer-close" onClick={()=>setDetail(null)}>×</button><span className={`status-chip ${tone(detail.status)}`}>{statusLabel[detail.status]||detail.status}</span><h2>{detail.code}</h2><p>{detail.table?`Mesa ${detail.table.code}`:detail.channel}</p><div className="detail-total">{brl(detail.total)}</div><h3>Itens</h3>{detail.orders.flatMap(o=>o.items).map(i=><div className="detail-item" key={i.id}><span>{i.description} × {Number(i.quantity)}</span><b>{brl(i.total)}</b></div>)}{!detail.orders.some(o=>o.items.length)?<p className="muted">Sem itens lançados ainda.</p>:null}<h3>Pagamentos</h3>{detail.payments.map(p=><div className="detail-item" key={p.id}><span>{p.method}</span><b>{brl(p.amount)}</b></div>)}<div className="drawer-actions">{detail.status==='active'?<button onClick={()=>void closure()}>Pedir fechamento</button>:null}{detail.status!=='closed'?<button onClick={()=>void pay()}>Registrar pagamento</button>:null}{detail.payments.length?<button className="primary-action" onClick={()=>void close()}>Finalizar comanda</button>:null}</div></aside></div>:null}</>;
}