import { useCallback, useEffect, useState } from 'react';
import { Button } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { api, ApiError } from '../lib/api';
import './restaurant-flow.css';

type CommandMode='automatic'|'manual'|'table_only';
type StationType='kitchen'|'bar'|'fryer'|'grill'|'dessert'|'assembly'|'other';
type Station={id:string;code:string;name:string;station_type:StationType;printer_key?:string|null;auto_print:boolean;active:boolean;sort_order:number};
const stationTypeNames:Record<StationType,string>={kitchen:'Cozinha',bar:'Bar',fryer:'Fritadeira',grill:'Chapa / Grill',dessert:'Sobremesas',assembly:'Montagem / Expedição',other:'Outro'};
const fail=(reason:unknown,fallback:string)=>reason instanceof ApiError?reason.message:fallback;

export function RestaurantAttendanceSettings({value,onSaved}:{value:CommandMode;onSaved:(mode:CommandMode)=>void}){
 const[mode,setMode]=useState<CommandMode>(value),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>setMode(value),[value]);
 const save=async()=>{setSaving(true);setMessage('');try{await api.patch('/api/v1/restaurant/settings',{commandMode:mode});onSaved(mode);setMessage('Modo de atendimento atualizado.')}catch(reason){setMessage(fail(reason,'Não foi possível salvar o modo de atendimento.'))}finally{setSaving(false)}};
 return <ContentCard title="Modo de atendimento" description="Define como mesa e comanda identificam a mesma conta durante o atendimento."><div className="restaurant-flow-settings"><label className={mode==='automatic'?'selected':''}><input type="radio" name="attendanceCommandMode" checked={mode==='automatic'} onChange={()=>setMode('automatic')}/><div><strong>Comanda automática</strong><p>A comanda é criada automaticamente ao abrir uma mesa.</p></div></label><label className={mode==='manual'?'selected':''}><input type="radio" name="attendanceCommandMode" checked={mode==='manual'} onChange={()=>setMode('manual')}/><div><strong>Comanda manual / física</strong><p>O número da comanda física é informado ao abrir a mesa.</p></div></label><label className={mode==='table_only'?'selected':''}><input type="radio" name="attendanceCommandMode" checked={mode==='table_only'} onChange={()=>setMode('table_only')}/><div><strong>Somente mesa</strong><p>O consumo fica diretamente vinculado ao número da mesa.</p></div></label><div className="row-actions"><Button onClick={()=>void save()} disabled={saving}>{saving?'Salvando…':'Salvar modo'}</Button>{message?<span role="status">{message}</span>:null}</div></div></ContentCard>;
}

export function RestaurantProductionSettings(){
 const[stations,setStations]=useState<Station[]>([]),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const load=useCallback(async()=>{try{const result=await api.get<{data:Station[]}>('/api/v1/restaurant/production/stations');setStations(result.data)}catch(reason){setMessage(fail(reason,'Não foi possível carregar as estações.'))}},[]);
 useEffect(()=>{void load()},[load]);
 const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);setSaving(true);setMessage('');try{await api.post('/api/v1/restaurant/production/stations',{name:String(data.get('name')??'').trim(),code:String(data.get('code')??'').trim(),stationType:String(data.get('stationType')??'kitchen'),printerKey:String(data.get('printerKey')??'').trim()||undefined,autoPrint:data.get('autoPrint')==='on',sortOrder:Number(data.get('sortOrder')??0)});setOpen(false);setMessage('Estação de produção criada.');await load()}catch(reason){setMessage(fail(reason,'Não foi possível criar a estação.'))}finally{setSaving(false)}};
 const toggle=async(station:Station,patch:Partial<{active:boolean;autoPrint:boolean}>)=>{setMessage('');try{await api.patch(`/api/v1/restaurant/production/stations/${station.id}`,patch);await load()}catch(reason){setMessage(fail(reason,'Não foi possível atualizar a estação.'))}};
 return <><ContentCard title="Setores e impressão" description="Gerencie aqui os destinos da produção e a impressora usada por cada setor."><div className="production-settings-head"><div><strong>{stations.filter(x=>x.active).length} estação(ões) ativa(s)</strong><p>Itens sem rota específica seguem para Cozinha por padrão.</p></div><Button onClick={()=>setOpen(true)}>Nova estação</Button></div><div className="production-station-grid">{stations.length?stations.map(station=><article key={station.id} className={station.active?'':'disabled'}><div><span>{stationTypeNames[station.station_type]}</span><h3>{station.name}</h3><p>Código: {station.code}</p></div><div className="production-station-printer"><small>Impressora</small><strong>{station.printer_key||'Não configurada'}</strong><span>{station.auto_print?'Impressão automática':'Somente KDS / fila digital'}</span></div><div className="production-station-actions"><button onClick={()=>void toggle(station,{autoPrint:!station.auto_print})} disabled={!station.printer_key}>{station.auto_print?'Desativar auto impressão':'Ativar auto impressão'}</button><button onClick={()=>void toggle(station,{active:!station.active})}>{station.active?'Desativar estação':'Reativar estação'}</button></div></article>):<div className="restaurant-flow-banner"><strong>Nenhuma estação cadastrada</strong><span>A estação Cozinha pode ser criada automaticamente no primeiro envio; cadastre outras para separar Bar, Fritadeira e demais setores.</span></div>}</div>{message?<div className="toast" role="status">{message}</div>:null}</ContentCard><Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={submit} title="Nova estação de produção" description="Ex.: Bar, Cozinha, Fritadeira ou Sobremesas." submitLabel={saving?'Salvando…':'Criar estação'}><Field label="Nome" name="name" required/><Field label="Código" name="code"><input name="code" placeholder="bar, cozinha, fritadeira" required/></Field><Field label="Tipo" name="stationType"><select name="stationType" defaultValue="kitchen">{Object.entries(stationTypeNames).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></Field><Field label="Ordem" name="sortOrder"><input name="sortOrder" type="number" min="0" defaultValue="0"/></Field><Field label="Chave da impressora" name="printerKey"><input name="printerKey" placeholder="BAR-01 ou 192.168.1.50:9100"/></Field><label className="nx-field"><span className="nx-field-label">Impressão automática</span><span className="menu-stock-toggle"><input name="autoPrint" type="checkbox"/><span>Gerar trabalho de impressão ao receber itens deste setor</span></span></label></Modal></>;
}
