import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState } from '@nexoio/ui';
import { PageHeader } from '../components/PageHeader';
import { Field, Modal } from '../components/Modal';
import { api, ApiError } from '../lib/api';
import './restaurant-operations.css';

type TableRow={id:string;number:string;seats:number|null;status:'available'|'occupied'|'reserved'|'unavailable';created_at?:string};
type TableFilter='all'|TableRow['status'];type CommandMode='automatic'|'manual'|'table_only';
type OpenResult={mode:CommandMode;tableId:string;tableNumber:string;tabId:string|null;commandCode:string|null;reused?:boolean};
const labels:Record<TableRow['status'],string>={available:'Livre',occupied:'Ocupada',reserved:'Reservada',unavailable:'Indisponível'};

export function RestaurantTablesPage(){
  const[items,setItems]=useState<TableRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[filter,setFilter]=useState<TableFilter>('all');const[commandMode,setCommandMode]=useState<CommandMode>('automatic');const[manualTable,setManualTable]=useState<TableRow|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[result,settings]=await Promise.all([api.get<{data:TableRow[]}>('/api/v1/tables'),api.get<{data:{command_mode?:CommandMode}}>('/api/v1/restaurant/settings')]);setItems(result.data);setCommandMode(settings.data.command_mode??'automatic')}catch(cause){setError(cause instanceof ApiError?cause.message:'Não foi possível carregar as mesas.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const counts=useMemo(()=>({all:items.length,available:items.filter(x=>x.status==='available').length,occupied:items.filter(x=>x.status==='occupied').length,reserved:items.filter(x=>x.status==='reserved').length,unavailable:items.filter(x=>x.status==='unavailable').length}),[items]);
  const visible=filter==='all'?items:items.filter(x=>x.status===filter);
  const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError('');const form=new FormData(e.currentTarget);try{await api.post('/api/v1/tables',{number:String(form.get('number')??'').trim(),seats:Number(form.get('seats')??0)||undefined});setOpen(false);await load()}catch(cause){setError(cause instanceof ApiError?cause.message:'Não foi possível criar a mesa.')}finally{setSaving(false)}};
  const changeStatus=async(table:TableRow,status:TableRow['status'])=>{if(status===table.status)return;setError('');try{await api.patch(`/api/v1/tables/${table.id}/status`,{status});setItems(current=>current.map(row=>row.id===table.id?{...row,status}:row))}catch(cause){setError(cause instanceof ApiError?cause.message:'Não foi possível alterar o status da mesa.')}};
  const goOrder=(result:OpenResult)=>{const q=new URLSearchParams({tableId:result.tableId,new:'1'});if(result.tabId)q.set('tabId',result.tabId);if(result.commandCode)q.set('command',result.commandCode);history.pushState({},'',`/pedidos?${q}`);window.dispatchEvent(new PopStateEvent('popstate'))};
  const openAttendance=async(table:TableRow,commandCode?:string)=>{setError('');setSaving(true);try{const result=await api.post<{data:OpenResult}>(`/api/v1/restaurant/tables/${table.id}/open`,commandCode?{commandCode}:{ });goOrder(result.data)}catch(cause){setError(cause instanceof ApiError?cause.message:'Não foi possível abrir o atendimento.')}finally{setSaving(false);setManualTable(null)}};
  const start=(table:TableRow)=>{if(table.status==='unavailable')return;if(commandMode==='manual'&&table.status!=='occupied'){setManualTable(table);return}void openAttendance(table)};
  const submitManual=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!manualTable)return;const f=new FormData(e.currentTarget);await openAttendance(manualTable,String(f.get('commandCode')??'').trim())};
  return <>
    <PageHeader title="Mesas" description="Clique na mesa para abrir ou continuar o atendimento." action={<Button onClick={()=>setOpen(true)}>Nova mesa</Button>}/>
    <div className="restaurant-flow-banner"><strong>{commandMode==='automatic'?'Comanda automática':commandMode==='manual'?'Comanda manual':'Somente mesa'}</strong><span>{commandMode==='automatic'?'A comanda é criada ao abrir a mesa.':commandMode==='manual'?'O número da comanda física será solicitado ao abrir a mesa.':'O consumo fica vinculado diretamente ao número da mesa.'}</span></div>
    <section className="restaurant-summary" aria-label="Resumo das mesas"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}><span>Total</span><strong>{counts.all}</strong></button><button className={filter==='available'?'active':''} onClick={()=>setFilter('available')}><span>Livres</span><strong>{counts.available}</strong></button><button className={filter==='occupied'?'active':''} onClick={()=>setFilter('occupied')}><span>Ocupadas</span><strong>{counts.occupied}</strong></button><button className={filter==='reserved'?'active':''} onClick={()=>setFilter('reserved')}><span>Reservadas</span><strong>{counts.reserved}</strong></button></section>
    {error?<div className="auth-notice error" role="alert">{error} <button onClick={()=>void load()}>Tentar novamente</button></div>:null}
    {loading?<div className="restaurant-loading">Carregando mesas…</div>:visible.length?<section className="restaurant-card-grid">{visible.map(table=><article key={table.id} className={`restaurant-op-card status-${table.status}`}><div className="restaurant-card-top"><span className="restaurant-status"><i/>{labels[table.status]}</span><span className="restaurant-seat-count">{table.seats??'—'} lugares</span></div><div className="restaurant-table-number">Mesa {table.number}</div><p className="restaurant-card-copy">{table.status==='available'?'Pronta para receber clientes.':table.status==='occupied'?'Atendimento em andamento.':table.status==='reserved'?'Reservada para atendimento.':'Fora da operação no momento.'}</p><label className="restaurant-inline-field">Status<select value={table.status} onChange={e=>void changeStatus(table,e.target.value as TableRow['status'])}><option value="available">Livre</option><option value="occupied">Ocupada</option><option value="reserved">Reservada</option><option value="unavailable">Indisponível</option></select></label><div className="restaurant-card-actions"><button disabled={saving||table.status==='unavailable'} onClick={()=>start(table)}>{table.status==='occupied'?'Continuar atendimento':'Abrir atendimento'}</button></div></article>)}</section>:<EmptyState title="Nenhuma mesa cadastrada" description="Cadastre as mesas do salão para iniciar os atendimentos." action={<Button onClick={()=>setOpen(true)}>Cadastrar mesa</Button>}/>} 
    <Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={create} title="Nova mesa"><Field label="Número ou nome" name="number" required/><Field label="Quantidade de lugares" name="seats"><input name="seats" type="number" min="1" max="100" required/></Field>{saving?<div className="auth-notice">Salvando mesa…</div>:null}</Modal>
    <Modal open={Boolean(manualTable)} onClose={()=>!saving&&setManualTable(null)} onSubmit={submitManual} title={`Abrir Mesa ${manualTable?.number??''}`} description="Informe o número da comanda física entregue ao cliente."><Field label="Número/código da comanda" name="commandCode" required/><Field label="Pessoas" name="guestCount"><input name="guestCount" type="number" min="1" max="100" defaultValue="1"/></Field></Modal>
  </>;
}
