import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState } from '@nexoio/ui';
import { PageHeader } from '../components/PageHeader';
import { Field, Modal } from '../components/Modal';
import { api, ApiError } from '../lib/api';
import './restaurant-operations.css';

type CommandRow={id:string;code:string;table_id:string|null;table_number:string|null;customer_id?:string|null;customer_name:string|null;guest_count:number;status:string;total:number|string;paid?:number|string;due?:number|string;opened_at?:string;closed_at?:string|null};
type TableRow={id:string;number:string;status:string};type CustomerRow={id:string;name:string};
type CreateResult={id:string;code:string;tableId?:string|null;status:string};
const money=(value:number|string)=>Number(value??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const elapsed=(date?:string)=>{if(!date)return'Agora';const minutes=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/60000));if(minutes<60)return`${minutes} min`;const hours=Math.floor(minutes/60);return`${hours}h ${minutes%60}min`};
const navigate=(path:string)=>{history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));};

export function RestaurantCommandsPage(){
  const[items,setItems]=useState<CommandRow[]>([]);const[closed,setClosed]=useState<CommandRow[]>([]);const[tables,setTables]=useState<TableRow[]>([]);const[customers,setCustomers]=useState<CustomerRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[showClosed,setShowClosed]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[result,legacy,tableResult,customerResult]=await Promise.all([api.get<{data:CommandRow[]}>('/api/v1/restaurant/checks'),api.get<{data:CommandRow[]}>('/api/v1/commands'),api.get<{data:TableRow[]}>('/api/v1/tables'),api.get<{data:CustomerRow[]}>('/api/v1/customers')]);setItems(result.data);setClosed(legacy.data.filter(x=>x.status!=='open'));setTables(tableResult.data);setCustomers(customerResult.data)}catch(cause){setError(cause instanceof ApiError?cause.message:'Não foi possível carregar as comandas.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const totalOpen=useMemo(()=>items.reduce((sum,row)=>sum+Number(row.due??row.total??0),0),[items]);
  const openService=(row:Pick<CommandRow,'id'|'code'|'table_id'>)=>{const q=new URLSearchParams({tabId:row.id,command:row.code,from:'comandas'});if(row.table_id)q.set('tableId',row.table_id);navigate(`/atendimento?${q}`)};
  const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError('');const form=new FormData(e.currentTarget);const tableId=String(form.get('tableId')??'');const customerId=String(form.get('customerId')??'');const code=String(form.get('code')??'').trim();try{const result=await api.post<{data:CreateResult}>('/api/v1/commands',{code,tableId:tableId||undefined,customerId:customerId||undefined,guestCount:Number(form.get('guestCount')??1)||1});setOpen(false);openService({id:result.data.id,code,table_id:tableId||null})}catch(cause){setError(cause instanceof ApiError?cause.message:'Não foi possível abrir a comanda.')}finally{setSaving(false)}};
  const close=async(row:CommandRow)=>{if(!confirm(`Fechar a comanda ${row.code}?`))return;setError('');try{await api.post(`/api/v1/commands/${row.id}/close`);await load()}catch(cause){setError(cause instanceof ApiError?cause.message:'Não foi possível fechar a comanda.')}};
  const goCash=(row:CommandRow)=>{const q=new URLSearchParams({tabId:row.id});if(row.table_id)q.set('tableId',row.table_id);navigate(`/caixa?${q}`)};
  const renderCard=(row:CommandRow,isClosed=false)=><article key={row.id} className={`restaurant-op-card command-card ${isClosed?'status-available':'status-occupied'}`}><div className="restaurant-card-top"><span className="restaurant-status"><i/>{isClosed?'Fechada':'Aberta'}</span><span>{elapsed(row.opened_at)}</span></div><button type="button" className="restaurant-card-open" onClick={()=>openService(row)}><span className="restaurant-command-code">Comanda {row.code}</span><span className="restaurant-card-copy">{isClosed?'Toque para consultar o atendimento.':'Toque para adicionar itens ou consultar pedidos.'}</span></button><div className="restaurant-command-meta"><span><b>{row.table_number?`Mesa ${row.table_number}`:'Sem mesa'}</b></span><span>{row.customer_name||'Consumidor não identificado'}</span><span>{row.guest_count??1} pessoa(s)</span></div><div className="restaurant-command-total"><span>{isClosed?'Total':'Saldo em aberto'}</span><strong>{money(isClosed?row.total:Number(row.due??row.total))}</strong></div><div className="restaurant-card-actions"><button onClick={()=>openService(row)}>{isClosed?'Consultar':'Abrir atendimento'}</button>{!isClosed&&Number(row.due??0)>0?<button className="secondary" onClick={()=>goCash(row)}>Ir para o caixa</button>:null}{!isClosed&&Number(row.due??0)<=0?<button className="secondary" onClick={()=>void close(row)}>Fechar</button>:null}</div></article>;
  const visible=showClosed?closed:items;
  return <><PageHeader title="Atendimento · Comandas" description="Comandas e mesas pertencem à mesma conta de atendimento." action={<div className="row-actions"><Button secondary onClick={()=>navigate('/mesas')}>Ver mesas</Button><Button onClick={()=>setOpen(true)}>Nova comanda</Button></div>}/><section className="restaurant-summary command-summary"><div><span>Comandas abertas</span><strong>{items.length}</strong></div><div><span>Total a receber</span><strong>{money(totalOpen)}</strong></div><div><span>Fechadas</span><strong>{closed.length}</strong></div></section><div className="restaurant-toolbar"><button className={!showClosed?'active':''} onClick={()=>setShowClosed(false)}>Abertas</button><button className={showClosed?'active':''} onClick={()=>setShowClosed(true)}>Fechadas</button><button onClick={()=>void load()}>Atualizar</button></div>{error?<div className="auth-notice error" role="alert">{error}</div>:null}{loading?<div className="restaurant-loading">Carregando comandas…</div>:visible.length?<section className="restaurant-card-grid">{visible.map(row=>renderCard(row,showClosed))}</section>:<EmptyState title={showClosed?'Nenhuma comanda fechada':'Nenhuma comanda aberta'} description={showClosed?'As comandas concluídas aparecerão aqui.':'Abra uma mesa ou uma comanda para iniciar o atendimento.'} action={!showClosed?<Button onClick={()=>setOpen(true)}>Abrir comanda</Button>:undefined}/>}<Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={create} title="Nova comanda" description="Cadastro rápido. Depois de abrir, você será levado para a tela completa do atendimento."><Field label="Código da comanda" name="code" required/><Field label="Mesa" name="tableId"><select name="tableId" defaultValue=""><option value="">Sem mesa</option>{tables.filter(t=>t.status!=='unavailable').map(t=><option key={t.id} value={t.id}>Mesa {t.number}</option>)}</select></Field><Field label="Cliente" name="customerId"><select name="customerId" defaultValue=""><option value="">Sem cliente</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Quantidade de pessoas" name="guestCount"><input name="guestCount" type="number" min="1" defaultValue="1" required/></Field>{saving?<div className="auth-notice">Abrindo comanda…</div>:null}</Modal></>;
}
