import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api, ApiError } from '../lib/api';

type Sale={id:string;customer_name:string|null;status:string;total:string;created_at:string;payments:Array<{method:string;amount:string;status:string}>};
const brl=(value:string|number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function SalesPage(){
  const[items,setItems]=useState<Sale[]>([]);const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await api.get<{data:Sale[]}>('/api/v1/sales');setItems(response.data)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar as vendas.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);setSaving(true);setError('');try{await api.post('/api/v1/sales',{description:String(form.get('description')??''),total:Number(form.get('total')??0),method:String(form.get('method')??'Pix'),notes:String(form.get('notes')??'')});setOpen(false);await load()}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível registrar a venda.')}finally{setSaving(false)}};
  const cancel=async(sale:Sale)=>{const reason=prompt('Informe o motivo do cancelamento:');if(!reason?.trim())return;try{await api.post(`/api/v1/sales/${sale.id}/cancel`,{reason});await load()}catch(value){setError(value instanceof ApiError?value.message:'Não foi possível cancelar a venda.')}};
  const completed=useMemo(()=>items.filter(x=>x.status==='completed'),[items]);const total=completed.reduce((sum,item)=>sum+Number(item.total),0);const cancelled=items.filter(x=>x.status==='cancelled').length;
  return <><PageHeader title="Vendas" description="Vendas persistidas, pagamentos vinculados e cancelamentos auditados." action={<Button onClick={()=>setOpen(true)}>Nova venda</Button>}/><StatGrid items={[{label:'Vendas concluídas',value:brl(total)},{label:'Ticket médio',value:brl(completed.length?total/completed.length:0)},{label:'Concluídas',value:String(completed.length)},{label:'Canceladas',value:String(cancelled),tone:cancelled?'warning':undefined}]}/>{error?<div className="auth-notice error" role="alert">{error}</div>:null}<ContentCard title="Histórico de vendas" description="Os dados vêm do backend e ficam isolados por empresa.">{loading?<div className="empty-state"><h3>Carregando…</h3></div>:items.length?<div className="table-shell"><table><thead><tr><th>Venda</th><th>Cliente</th><th>Pagamento</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>#{x.id.slice(0,8)}</td><td>{x.customer_name||'Consumidor final'}</td><td>{x.payments?.map(p=>p.method).join(' + ')||'—'}</td><td>{brl(x.total)}</td><td><Pill tone={x.status==='completed'?'success':x.status==='cancelled'?'danger':'brand'}>{x.status==='completed'?'Concluída':x.status==='cancelled'?'Cancelada':x.status}</Pill></td><td className="row-actions">{x.status==='completed'?<button onClick={()=>void cancel(x)}>Cancelar</button>:null}</td></tr>)}</tbody></table></div>:<EmptyState title="Nenhuma venda registrada" description="As vendas concluídas aparecerão aqui automaticamente." action={<Button onClick={()=>setOpen(true)}>Registrar venda</Button>}/>}</ContentCard><Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={create} title="Registrar venda" submitLabel={saving?'Salvando…':'Concluir venda'}><Field label="Descrição" name="description" required/><Field label="Total" name="total" type="number" required/><Field label="Forma de pagamento" name="method" required><select name="method"><option>Pix</option><option>Dinheiro</option><option>Cartão</option></select></Field><Field label="Observações" name="notes"/></Modal></>;
}
