import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api } from '../lib/api';

type Payment={id:string;method:string;amount:string;status:string};
type Sale={id:string;customerId:string|null;customerName:string|null;status:string;total:string;createdAt:string;payments:Payment[]};
type Customer={id:string;name:string};
const brl=(v:unknown)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function SalesPage(){
 const[items,setItems]=useState<Sale[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const[a,b]=await Promise.all([api.get<{data:Sale[]}>('/api/v1/sales'),api.get<{data:Customer[]}>('/api/v1/customers?limit=100')]);setItems(a.data);setCustomers(b.data);setError('')}catch(e:any){setError(e.message||'Não foi possível carregar as vendas.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api.post('/api/v1/sales',{customerId:String(f.get('customerId')||'')||undefined,description:String(f.get('description')||''),total:Number(f.get('total')||0),method:String(f.get('method')||'dinheiro'),notes:String(f.get('notes')||'')||undefined});setOpen(false);await load()}catch(x:any){setError(x.message||'Não foi possível registrar a venda.')}};
 const today=new Date().toDateString(),todayItems=useMemo(()=>items.filter(x=>new Date(x.createdAt).toDateString()===today&&x.status==='completed'),[items,today]);const total=todayItems.reduce((s,x)=>s+Number(x.total),0);
 return <><PageHeader title="Vendas" description="Vendas reais integradas ao caixa quando houver sessão aberta." action={<Button onClick={()=>setOpen(true)}>Nova venda</Button>}/><StatGrid items={[{label:'Vendas hoje',value:brl(total)},{label:'Ticket médio',value:brl(todayItems.length?total/todayItems.length:0)},{label:'Concluídas',value:String(items.filter(x=>x.status==='completed').length)},{label:'Total no histórico',value:String(items.length)}]}/><ContentCard title="Histórico de vendas" description="Registros comerciais persistidos no banco da empresa.">{error?<div className="restaurant-error">{error}</div>:null}{loading&&!items.length?<div className="merchant-empty"><h3>Carregando vendas…</h3></div>:items.length?<div className="table-shell"><table><thead><tr><th>Venda</th><th>Data</th><th>Cliente</th><th>Pagamento</th><th>Total</th><th>Status</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>#{x.id.slice(0,8).toUpperCase()}</strong></td><td>{new Date(x.createdAt).toLocaleString('pt-BR')}</td><td>{x.customerName||'Consumidor'}</td><td>{x.payments[0]?.method||'—'}</td><td><strong>{brl(x.total)}</strong></td><td><Pill tone={x.status==='completed'?'success':'warning'}>{x.status==='completed'?'Concluída':x.status}</Pill></td></tr>)}</tbody></table></div>:<EmptyState title="Nenhuma venda registrada" description="As vendas de comandas e vendas diretas aparecerão aqui." action={<Button onClick={()=>setOpen(true)}>Registrar venda</Button>}/>}</ContentCard><Modal open={open} onClose={()=>setOpen(false)} onSubmit={create} title="Registrar venda" submitLabel="Concluir venda"><Field label="Cliente" name="customerId"><select name="customerId"><option value="">Consumidor</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Descrição" name="description" required/><Field label="Total" name="total" type="number" required/><Field label="Forma de pagamento" name="method"><select name="method" defaultValue="pix"><option value="pix">Pix</option><option value="dinheiro">Dinheiro</option><option value="debito">Cartão de débito</option><option value="credito">Cartão de crédito</option></select></Field><Field label="Observações" name="notes"/></Modal></>;
}
