import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api } from '../lib/api';

type Appointment={id:string;customerId:string|null;professionalId:string|null;serviceId:string|null;startsAt:string;endsAt:string;status:string;notes:string|null};
type Customer={id:string;name:string};type Service={id:string;name:string;durationMinutes:number|null};type Professional={id:string;displayName:string};
const dayKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export function SchedulePage(){
 const[items,setItems]=useState<Appointment[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[services,setServices]=useState<Service[]>([]),[professionals,setProfessionals]=useState<Professional[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const[a,b,c,d]=await Promise.all([api.get<{data:Appointment[]}>('/api/v1/appointments'),api.get<{data:Customer[]}>('/api/v1/customers?limit=100'),api.get<{data:Service[]}>('/api/v1/services'),api.get<{data:Professional[]}>('/api/v1/professionals')]);setItems(a.data);setCustomers(b.data);setServices(c.data);setProfessionals(d.data);setError('')}catch(e:any){setError(e.message||'Não foi possível carregar a agenda.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const today=dayKey(new Date()),todayItems=useMemo(()=>items.filter(x=>dayKey(new Date(x.startsAt))===today),[items,today]);
 const name=(list:Array<{id:string;name?:string;displayName?:string}>,id:string|null)=>list.find(x=>x.id===id)?.name||list.find(x=>x.id===id)?.displayName||'—';
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),service=services.find(x=>x.id===String(f.get('serviceId'))),start=new Date(String(f.get('startsAt'))),duration=Math.max(5,service?.durationMinutes||30),end=new Date(start.getTime()+duration*60000);try{await api.post('/api/v1/appointments',{customerId:String(f.get('customerId')||'')||undefined,professionalId:String(f.get('professionalId')||''),serviceId:String(f.get('serviceId')||''),startsAt:start.toISOString(),endsAt:end.toISOString(),notes:String(f.get('notes')||'')||undefined});setOpen(false);await load()}catch(x:any){setError(x.message||'Não foi possível criar o agendamento.')}};
 return <><PageHeader title="Agenda" description="Horários reais com validação de conflito por profissional." action={<Button onClick={()=>setOpen(true)}>Novo agendamento</Button>}/><StatGrid items={[{label:'Hoje',value:String(todayItems.length)},{label:'Confirmados',value:String(todayItems.filter(x=>x.status==='confirmed').length)},{label:'Pendentes',value:String(todayItems.filter(x=>x.status==='pending').length)},{label:'Profissionais',value:String(professionals.length)}]}/><ContentCard title="Agenda de hoje" description="Atendimentos salvos no banco da empresa." action={<Pill tone="brand">Hoje</Pill>}>{error?<div className="restaurant-error">{error}</div>:null}{loading&&!items.length?<div className="merchant-empty"><h3>Carregando agenda…</h3></div>:todayItems.length?<div className="table-shell"><table><thead><tr><th>Horário</th><th>Cliente</th><th>Serviço</th><th>Profissional</th><th>Status</th></tr></thead><tbody>{todayItems.sort((a,b)=>+new Date(a.startsAt)-+new Date(b.startsAt)).map(x=><tr key={x.id}><td><strong>{new Date(x.startsAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</strong></td><td>{name(customers,x.customerId)}</td><td>{name(services,x.serviceId)}</td><td>{name(professionals,x.professionalId)}</td><td><Pill tone={x.status==='confirmed'?'success':x.status==='pending'?'warning':'neutral'}>{x.status==='pending'?'Pendente':x.status==='confirmed'?'Confirmado':x.status}</Pill></td></tr>)}</tbody></table></div>:<EmptyState title="Nenhum atendimento hoje" description={professionals.length?'Crie um novo agendamento para começar.':'Cadastre ou habilite um profissional antes de agendar.'} action={professionals.length?<Button onClick={()=>setOpen(true)}>Novo agendamento</Button>:undefined}/>}</ContentCard><Modal open={open} onClose={()=>setOpen(false)} onSubmit={create} title="Novo agendamento" submitLabel="Agendar"><Field label="Cliente" name="customerId"><select name="customerId"><option value="">Sem cliente vinculado</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Serviço" name="serviceId"><select name="serviceId" required defaultValue=""><option value="" disabled>Selecione</option>{services.filter(x=>(x as any).active!==false).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Profissional" name="professionalId"><select name="professionalId" required defaultValue=""><option value="" disabled>Selecione</option>{professionals.map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></Field><Field label="Data e horário" name="startsAt" type="datetime-local" required/><Field label="Observações" name="notes"/></Modal></>;
}
