import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { useSession } from '../auth/SessionProvider';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api, ApiError } from '../lib/api';

type Service={id:string;name:string;description?:string|null;price:string|number;durationMinutes?:number|null;duration_minutes?:number|null;active?:boolean};const duration=(x:Service)=>x.durationMinutes??x.duration_minutes??0;const brl=(value:string|number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function ServicesPage(){
 const session=useSession();const canWrite=session.permissions.has('services.write');const[items,setItems]=useState<Service[]>([]);const[editing,setEditing]=useState<Service|null>(null);const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const load=useCallback(async(force=false)=>{setLoading(items.length===0);setError('');try{const response=await api.get<{data:Service[]}>('/api/v1/services',{force});setItems(response.data)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar os serviços.')}finally{setLoading(false)}},[items.length]);useEffect(()=>{void load()},[load]);
 const activeItems=items.filter(x=>x.active!==false);const average=useMemo(()=>activeItems.length?activeItems.reduce((s,x)=>s+Number(x.price),0)/activeItems.length:0,[activeItems]);const avgDuration=useMemo(()=>activeItems.length?Math.round(activeItems.reduce((s,x)=>s+duration(x),0)/activeItems.length):0,[activeItems]);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const payload={name:String(f.get('name')??'').trim(),description:String(f.get('description')??'').trim()||undefined,price:Number(f.get('price')??0),durationMinutes:String(f.get('durationMinutes')??'')===''?undefined:Number(f.get('durationMinutes'))};setSaving(true);setError('');try{if(editing)await api.patch(`/api/v1/services/${editing.id}`,payload);else await api.post('/api/v1/services',payload);setOpen(false);setEditing(null);setNotice(editing?'Serviço atualizado.':'Serviço cadastrado.');await load(true)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível salvar o serviço.')}finally{setSaving(false)}};
 const toggle=async(s:Service)=>{if(!canWrite)return;try{await api.patch(`/api/v1/services/${s.id}`,{active:s.active===false});setNotice(s.active===false?'Serviço reativado.':'Serviço inativado sem apagar o histórico.');await load(true)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível alterar o serviço.')}};
 return <><PageHeader title="Serviços" description="Catálogo único de serviços usado por agenda, vendas e fluxos especializados." action={canWrite?<Button onClick={()=>{setEditing(null);setOpen(true)}}>Novo serviço</Button>:undefined}/><StatGrid items={[{label:'Serviços ativos',value:String(activeItems.length)},{label:'Preço médio',value:brl(average)},{label:'Duração média',value:avgDuration?`${avgDuration} min`:'—'},{label:'Inativos',value:String(items.length-activeItems.length)}]}/>{error?<div className="auth-notice error" role="alert">{error} <button onClick={()=>void load(true)}>Tentar novamente</button></div>:null}{notice?<div className="auth-notice success" role="status">{notice}</div>:null}<ContentCard title="Catálogo de serviços" description="Persistido no Neon e compartilhado por todos os módulos." action={<button onClick={()=>void load(true)}>Atualizar</button>}>{loading?<div className="empty-state"><h3>Carregando serviços…</h3></div>:items.length?<div className="public-cards">{items.map(x=><article className="service-card" key={x.id}><Pill tone={x.active===false?'warning':'success'}>{x.active===false?'Inativo':'Ativo'}</Pill><h3>{x.name}</h3><p>{x.description||'Sem descrição'}{duration(x)?` · ${duration(x)} min`:''}</p><div className="service-price">{brl(x.price)}</div>{canWrite?<div className="row-actions"><button onClick={()=>{setEditing(x);setOpen(true)}}>Editar</button><button onClick={()=>void toggle(x)}>{x.active===false?'Reativar':'Inativar'}</button></div>:null}</article>)}</div>:<div className="catalog-grid"><EmptyState title="Nenhum serviço cadastrado" description="Cadastre o primeiro serviço para usá-lo em agenda e vendas." action={canWrite?<Button onClick={()=>setOpen(true)}>Novo serviço</Button>:undefined}/></div>}</ContentCard><Modal open={open} onClose={()=>!saving&&(setOpen(false),setEditing(null))} onSubmit={submit} title={editing?'Editar serviço':'Novo serviço'} description="Este serviço fica disponível para os módulos habilitados." submitLabel={saving?'Salvando…':'Salvar serviço'}><Field label="Nome" name="name" required><input name="name" defaultValue={editing?.name??''} required/></Field><Field label="Descrição" name="description"><input name="description" defaultValue={editing?.description??''}/></Field><Field label="Preço" name="price" type="number" required><input name="price" type="number" step="0.01" defaultValue={editing?.price??''} required/></Field><Field label="Duração (minutos)" name="durationMinutes" type="number"><input name="durationMinutes" type="number" defaultValue={editing?duration(editing):''}/></Field></Modal></>;
}
