import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { StatGrid } from '../components/StatGrid';
import { api, ApiError } from '../lib/api';

type Service={id:string;name:string;description?:string|null;price:string|number;durationMinutes?:number|null;duration_minutes?:number|null;active?:boolean};
const duration=(x:Service)=>x.durationMinutes??x.duration_minutes??0;
const brl=(value:string|number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export function ServicesPage(){
 const[items,setItems]=useState<Service[]>([]);const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 const load=useCallback(async(force=false)=>{setLoading(items.length===0);setError('');try{const response=await api.get<{data:Service[]}>('/api/v1/services',{force});setItems(response.data)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível carregar os serviços.')}finally{setLoading(false)}},[items.length]);
 useEffect(()=>{void load()},[load]);
 const average=useMemo(()=>items.length?items.reduce((s,x)=>s+Number(x.price),0)/items.length:0,[items]);const avgDuration=useMemo(()=>items.length?Math.round(items.reduce((s,x)=>s+duration(x),0)/items.length):0,[items]);
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);setError('');try{await api.post('/api/v1/services',{name:String(f.get('name')??'').trim(),description:String(f.get('description')??'').trim()||undefined,price:Number(f.get('price')??0),durationMinutes:String(f.get('durationMinutes')??'')===''?undefined:Number(f.get('durationMinutes'))});setOpen(false);await load(true)}catch(reason){setError(reason instanceof ApiError?reason.message:'Não foi possível criar o serviço.')}finally{setSaving(false)}};
 return <><PageHeader title="Serviços" description="Catálogo único de serviços usado por agenda, vendas e fluxos especializados." action={<Button onClick={()=>setOpen(true)}>Novo serviço</Button>}/><StatGrid items={[{label:'Serviços cadastrados',value:String(items.length)},{label:'Preço médio',value:brl(average)},{label:'Duração média',value:avgDuration?`${avgDuration} min`:'—'},{label:'Disponíveis',value:String(items.filter(x=>x.active!==false).length)}]}/>{error?<div className="auth-notice error" role="alert">{error} <button onClick={()=>void load(true)}>Tentar novamente</button></div>:null}<ContentCard title="Catálogo de serviços" description="Persistido no Neon e compartilhado por todos os módulos." action={<button onClick={()=>void load(true)}>Atualizar</button>}>{loading?<div className="empty-state"><h3>Carregando serviços…</h3></div>:items.length?<div className="public-cards">{items.map(x=><article className="service-card" key={x.id}><Pill tone={x.active===false?'warning':'success'}>{x.active===false?'Inativo':'Ativo'}</Pill><h3>{x.name}</h3><p>{x.description||'Sem descrição'}{duration(x)?` · ${duration(x)} min`:''}</p><div className="service-price">{brl(x.price)}</div></article>)}</div>:<div className="catalog-grid"><EmptyState title="Nenhum serviço cadastrado" description="Cadastre o primeiro serviço para usá-lo em agenda e vendas." action={<Button onClick={()=>setOpen(true)}>Novo serviço</Button>}/></div>}</ContentCard><Modal open={open} onClose={()=>!saving&&setOpen(false)} onSubmit={create} title="Novo serviço" description="Este serviço ficará disponível para todos os módulos habilitados." submitLabel={saving?'Salvando…':'Salvar serviço'}><Field label="Nome" name="name" required/><Field label="Descrição" name="description"/><Field label="Preço" name="price" type="number" required/><Field label="Duração (minutos)" name="durationMinutes" type="number"/></Modal></>}
