import { useEffect, useState } from 'react';
import { Pill } from '@nexoio/ui';
import { ContentCard } from '../components/ContentCard';
import { Field, Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { api, ApiError } from '../lib/api';
type ModuleRow={key:string;name:string;description:string;dependencies:string[];enabled:boolean|null;source:string|null};
const moduleNames:Record<string,string>={overview:'Visão geral',customers:'Clientes',sales:'Vendas',cash:'Caixa',finance:'Financeiro',team:'Equipe',settings:'Configurações',schedule:'Agenda',products:'Produtos',services:'Serviços',inventory:'Estoque',orders:'Pedidos',tables:'Mesas',commands:'Comandas',menu:'Cardápio',kitchen:'Cozinha',delivery:'Entrega',service_orders:'Ordens de serviço',equipment:'Equipamentos',quotes:'Orçamentos',suppliers:'Fornecedores',classes:'Turmas',checkin:'Controle de entrada',plans:'Planos',patients:'Pacientes',procedures:'Procedimentos',professionals:'Profissionais'};

export function SettingsPage(){
  const[modules,setModules]=useState<ModuleRow[]>([]);const[dialog,setDialog]=useState<'password'|'email'|'mfa'|''>('');const[message,setMessage]=useState('');const[backupCodes,setBackupCodes]=useState<string[]>([]);
  useEffect(()=>{api.get<{data:ModuleRow[]}>('/api/v1/platform/business/modules').then(result=>setModules(result.data.filter(row=>row.enabled))).catch(reason=>setMessage(reason instanceof ApiError?reason.message:'Falha ao carregar recursos'))},[]);
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);try{if(dialog==='password')await api.post('/api/auth/change-password',{currentPassword:data.get('currentPassword'),newPassword:data.get('newPassword'),revokeOtherSessions:true});if(dialog==='email')await api.post('/api/auth/change-email',{newEmail:data.get('email'),callbackURL:'/configuracoes'});if(dialog==='mfa'){const result=await api.post<{backupCodes?:string[]}>('/api/auth/two-factor/enable',{password:data.get('currentPassword'),method:'totp'});setBackupCodes(result.backupCodes??[])}setMessage('Solicitação concluída com segurança.');setDialog('')}catch(reason){setMessage(reason instanceof ApiError?reason.message:'Não foi possível concluir')}};
  const revoke=async()=>{await api.post('/api/auth/revoke-other-sessions');setMessage('As outras sessões foram encerradas.')};
  return <><PageHeader title="Configurações" description="Recursos do segmento, identidade e segurança da conta."/><div className="merchant-two-columns"><ContentCard title="Recursos da empresa" description="Estes recursos são definidos pelo segmento e mantêm a operação consistente."><div className="settings-list">{modules.map(row=><div className="switch" key={row.key}><div><strong>{moduleNames[row.key]??row.name}</strong><p>Disponível para esta empresa</p></div><Pill tone="success">Ativo</Pill></div>)}</div></ContentCard><ContentCard title="Segurança da conta" description="Ações sensíveis exigem confirmação."><div className="settings-list"><button onClick={()=>setDialog('password')}><div><strong>Trocar senha</strong><p>Encerra as outras sessões ao concluir.</p></div><Pill>Abrir</Pill></button><button onClick={()=>setDialog('email')}><div><strong>Alterar e-mail</strong><p>O novo endereço precisa ser confirmado.</p></div><Pill>Abrir</Pill></button><button onClick={()=>setDialog('mfa')}><div><strong>Ativar verificação em duas etapas</strong><p>Use um aplicativo autenticador e códigos de recuperação.</p></div><Pill tone="brand">Recomendado</Pill></button><button onClick={()=>void revoke()}><div><strong>Encerrar outras sessões</strong><p>Mantém somente este dispositivo conectado.</p></div><Pill tone="warning">Encerrar</Pill></button></div></ContentCard></div>{message?<div className="toast" role="status">{message}</div>:null}{backupCodes.length?<ContentCard title="Códigos de recuperação" description="Guarde estes códigos em local seguro; eles não serão exibidos novamente."><pre>{backupCodes.join('\n')}</pre></ContentCard>:null}<Modal open={Boolean(dialog)} onClose={()=>setDialog('')} onSubmit={submit} title={dialog==='password'?'Trocar senha':dialog==='email'?'Alterar e-mail':'Ativar verificação em duas etapas'}>{dialog==='email'?<Field label="Novo e-mail" name="email" type="email" required/>:<><Field label="Senha atual" name="currentPassword" type="password" required/>{dialog==='password'?<Field label="Nova senha" name="newPassword" type="password" required/>:null}</>}</Modal></>;
}
