import { sql } from 'drizzle-orm';
import { createDb } from '@nexoio/db';
import type { Bindings } from './types';

type OutboxRow={id:string;business_id:string;user_id:string|null;customer_id:string|null;event_code:string;channel:string;destination:string|null;payload:Record<string,unknown>;attempts:number};
const rows=(r:any)=>r?.rows??r??[];
const render=(template:string,payload:Record<string,unknown>)=>template.replace(/{{\s*([\w.-]+)\s*}}/g,(_,key)=>{const value=key.split('.').reduce<any>((acc:string|number|boolean|Record<string,unknown>|null|undefined,part:string)=>acc&&typeof acc==='object'?(acc as any)[part]:undefined,payload);return value==null?'':String(value)});
function sender(value:string|undefined){const raw=(value??'Nexoio <no-reply@nexoio.com.br>').trim();const match=raw.match(/^(.*?)\s*<([^>]+)>$/);return match?{name:match[1].trim()||'Nexoio',email:match[2].trim()}:{name:'Nexoio',email:raw};}

async function resolveDestination(db:any,item:OutboxRow){if(item.destination)return item.destination;if(item.customer_id){const result=rows(await db.execute(sql`select email,phone from customers where id=${item.customer_id}::uuid and business_id=${item.business_id}::uuid limit 1`))[0] as any;if(item.channel==='email')return result?.email??null;return result?.phone??null;}if(item.user_id){const result=rows(await db.execute(sql`select email from users where id=${item.user_id}::uuid limit 1`))[0] as any;return result?.email??null;}return null;}
async function loadTemplate(db:any,item:OutboxRow){const result=rows(await db.execute(sql`select subject_template,body_template,name from notification_templates where event_code=${item.event_code} and channel=${item.channel} and active=true and (business_id=${item.business_id}::uuid or business_id is null) order by business_id nulls last limit 1`))[0] as any;return result??null;}

async function sendEmail(env:Bindings,to:string,subject:string,html:string){if(!env.BREVO_API_KEY)throw new Error('BREVO_API_KEY_NOT_CONFIGURED');const response=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'content-type':'application/json','api-key':env.BREVO_API_KEY},body:JSON.stringify({sender:sender(env.EMAIL_FROM),to:[{email:to}],subject,htmlContent:html,textContent:html.replace(/<[^>]+>/g,' ')})});if(!response.ok)throw new Error(`BREVO_${response.status}:${(await response.text()).slice(0,500)}`);}
async function sendWebhook(env:Bindings,item:OutboxRow,destination:string,subject:string,body:string){if(!env.NOTIFICATION_WEBHOOK_URL)throw new Error('NOTIFICATION_WEBHOOK_URL_NOT_CONFIGURED');const response=await fetch(env.NOTIFICATION_WEBHOOK_URL,{method:'POST',headers:{'content-type':'application/json',...(env.NOTIFICATION_WEBHOOK_SECRET?{'x-nexoio-notification-secret':env.NOTIFICATION_WEBHOOK_SECRET}:{})},body:JSON.stringify({id:item.id,businessId:item.business_id,eventCode:item.event_code,channel:item.channel,destination,subject,body,payload:item.payload})});if(!response.ok)throw new Error(`NOTIFICATION_WEBHOOK_${response.status}:${(await response.text()).slice(0,500)}`);}

export async function dispatchNotificationOutbox(env:Bindings,limit=50){const db=createDb(env.DATABASE_URL);const claimed=rows(await db.execute(sql`with picked as (select id from notification_outbox where status='pending' and next_attempt_at<=now() order by created_at for update skip locked limit ${limit}) update notification_outbox o set status='processing',attempts=o.attempts+1 from picked where o.id=picked.id returning o.*`)) as OutboxRow[];let sent=0,failed=0;
for(const item of claimed){try{const destination=await resolveDestination(db,item);if(!destination)throw new Error('DESTINATION_REQUIRED');const template=await loadTemplate(db,item);if(!template)throw new Error('TEMPLATE_NOT_FOUND');const subject=render(template.subject_template??template.name??item.event_code,item.payload);const body=render(template.body_template,item.payload);if(item.channel==='email')await sendEmail(env,destination,subject,body);else if(['whatsapp','sms','push'].includes(item.channel))await sendWebhook(env,item,destination,subject,body);else if(item.channel==='internal'){await db.execute(sql`insert into notifications(id,business_id,user_id,event_code,channel,template,payload,status,sent_at) values(gen_random_uuid(),${item.business_id}::uuid,${item.user_id??null}::uuid,${item.event_code},'internal',${item.event_code},${JSON.stringify(item.payload)}::jsonb,'sent',now())`);}else throw new Error('UNSUPPORTED_CHANNEL');await db.execute(sql`update notification_outbox set status='sent',sent_at=now(),last_error=null where id=${item.id}::uuid`);sent++;}catch(err){const message=(err instanceof Error?err.message:String(err)).slice(0,2000);await db.execute(sql`update notification_outbox set status=case when attempts>=5 then 'failed' else 'pending' end,last_error=${message},next_attempt_at=now()+(least(60,power(2,greatest(0,attempts-1)))::text||' minutes')::interval where id=${item.id}::uuid`);failed++;}}
return {claimed:claimed.length,sent,failed};}
