import type { BlockType, SiteBlock, SiteDesign } from './types';
export const BLOCK_LABELS:Record<BlockType,string>={hero:'Capa',text:'Texto',image:'Imagem',gallery:'Galeria',services:'Serviços',products:'Produtos',menu:'Cardápio',team:'Equipe',testimonials:'Depoimentos',faq:'Perguntas frequentes',map:'Mapa',contact:'Contato',whatsapp:'WhatsApp',form:'Formulário',video:'Vídeo',banner:'Banner',promotion:'Promoção',counter:'Contador',partners:'Logos de parceiros',social:'Redes sociais',schedule:'Agendamento',online_order:'Pedido online',pricing:'Tabela de preços',plans:'Planos',reviews:'Avaliações',hours:'Horários'};
export const DYNAMIC_BLOCKS=new Set<BlockType>(['services','products','menu','team','plans','reviews','hours']);
export const TEMPLATES=[
 {id:'beauty-01',name:'Elegância',category:'Beleza',version:1,colors:['#9b5de5','#f7e9ff']},{id:'beauty-02',name:'Editorial',category:'Beleza',version:1,colors:['#2f243a','#f5e6d3']},{id:'barber-01',name:'Barbearia clássica',category:'Beleza',version:1,colors:['#191919','#c49a5a']},
 {id:'restaurant-01',name:'Bistrô',category:'Alimentação',version:2,colors:['#8c2f1b','#fff1da']},{id:'restaurant-02',name:'Urbano',category:'Alimentação',version:2,colors:['#171717','#ff6b35']},{id:'restaurant-03',name:'Delivery direto',category:'Alimentação',version:1,colors:['#e5383b','#fff']},
 {id:'store-01',name:'Vitrine',category:'Varejo',version:2,colors:['#31572c','#f7f5ef']},{id:'store-02',name:'Catálogo minimalista',category:'Varejo',version:1,colors:['#111','#eee']},{id:'service-01',name:'Profissional',category:'Serviços',version:2,colors:['#1357c4','#eff6ff']},{id:'service-02',name:'Portfólio',category:'Serviços',version:1,colors:['#3c096c','#f3e8ff']},
 {id:'clinic-01',name:'Clínica leve',category:'Saúde',version:2,colors:['#168aad','#e9f8fb']},{id:'clinic-02',name:'Especialidades',category:'Saúde',version:1,colors:['#2d6a4f','#edf7f1']},{id:'gym-01',name:'Energia',category:'Fitness',version:1,colors:['#101010','#d4ff00']},{id:'studio-01',name:'Movimento',category:'Fitness',version:1,colors:['#5a189a','#f3e8ff']},{id:'generic-01',name:'Essencial',category:'Geral',version:2,colors:['#6548e8','#f5f1ff']},{id:'premium-01',name:'Premium',category:'Geral',version:2,colors:['#171222','#d5b36a']},
] as const;
export const DEFAULT_DESIGN:SiteDesign={fontFamily:'Inter',contentWidth:1180,spacing:56,titleSize:52,radius:18,buttonStyle:'rounded',background:'#ffffff',gradient:'',alignment:'left',columns:3,animation:'fade',stickyHeader:true,transparentHeader:false,showMenu:true,showFooter:true};
export const makeBlock=(type:BlockType,title=BLOCK_LABELS[type]):SiteBlock=>({id:crypto.randomUUID(),type,enabled:true,favorite:false,title,text:'',buttonText:type==='hero'?'Falar no WhatsApp':'',buttonUrl:'',mediaUrl:'',dataSource:DYNAMIC_BLOCKS.has(type)?'all':'manual',dataFilter:'',visibility:'all',style:{}});
export const createSegmentBlocks=(segment:string,name:string)=>{const specific:BlockType[]=segment.includes('restaurant')||segment.includes('snack')?['menu','online_order']:segment.includes('salon')||segment.includes('beauty')||segment.includes('barber')?['services','team','schedule']:segment.includes('retail')||segment.includes('market')?['products','promotion']:segment.includes('gym')||segment.includes('studio')?['plans','schedule']:['services','contact'];return [makeBlock('hero',name),...specific.map(type=>makeBlock(type)),makeBlock('testimonials'),makeBlock('hours'),makeBlock('map'),makeBlock('whatsapp')]};
