import type { BlockType, SiteBlock, SiteDesign } from './types';
export const BLOCK_LABELS:Record<BlockType,string>={hero:'Capa',text:'Texto',image:'Imagem',gallery:'Galeria',services:'Serviços',products:'Produtos',menu:'Cardápio',team:'Equipe',testimonials:'Depoimentos',faq:'Perguntas frequentes',map:'Mapa',contact:'Contato',whatsapp:'WhatsApp',form:'Formulário',video:'Vídeo',banner:'Banner',promotion:'Promoção',counter:'Contador',partners:'Logos de parceiros',social:'Redes sociais',schedule:'Agendamento',online_order:'Pedido online',pricing:'Tabela de preços',plans:'Planos',reviews:'Avaliações',hours:'Horários'};
export const DYNAMIC_BLOCKS=new Set<BlockType>(['services','products','menu','team','plans','reviews','hours']);
export const DEFAULT_DESIGN:SiteDesign={fontFamily:'Inter',contentWidth:1180,spacing:56,titleSize:52,radius:18,buttonStyle:'rounded',background:'#ffffff',gradient:'',alignment:'left',columns:3,animation:'fade',stickyHeader:true,transparentHeader:false,showMenu:true,showFooter:true};
type TemplatePreset={id:string;name:string;category:string;version:number;colors:readonly [string,string];description:string;design:Partial<SiteDesign>};
export const TEMPLATES:readonly TemplatePreset[]=[
 {id:'beauty-01',name:'Elegância',category:'Beleza',version:2,colors:['#9b5de5','#fff7fb'],description:'Delicado, sofisticado e visual.',design:{fontFamily:'Playfair Display',background:'#fffafc',radius:26,titleSize:62,spacing:74,alignment:'left',columns:3,buttonStyle:'pill'}},
 {id:'beauty-02',name:'Editorial',category:'Beleza',version:2,colors:['#3b2d43','#f6eadf'],description:'Editorial, artístico e premium.',design:{fontFamily:'Playfair Display',background:'#fbf5ef',radius:4,titleSize:68,spacing:88,alignment:'center',columns:2,buttonStyle:'square'}},
 {id:'barber-01',name:'Barbearia clássica',category:'Beleza',version:2,colors:['#c49a5a','#151515'],description:'Escuro, masculino e tradicional.',design:{fontFamily:'Montserrat',background:'#171717',radius:8,titleSize:58,spacing:68,alignment:'left',columns:3,buttonStyle:'square'}},
 {id:'restaurant-01',name:'Bistrô',category:'Alimentação',version:3,colors:['#8c2f1b','#fff1da'],description:'Aconchegante, gastronômico e elegante.',design:{fontFamily:'Playfair Display',background:'#fff8ec',radius:16,titleSize:64,spacing:78,alignment:'left',columns:2,buttonStyle:'rounded'}},
 {id:'restaurant-02',name:'Urbano',category:'Alimentação',version:3,colors:['#ff6b35','#171717'],description:'Impactante, moderno e noturno.',design:{fontFamily:'Montserrat',background:'#181818',radius:10,titleSize:60,spacing:62,alignment:'left',columns:3,buttonStyle:'square'}},
 {id:'restaurant-03',name:'Delivery direto',category:'Alimentação',version:2,colors:['#e5383b','#fff7f2'],description:'Rápido, comercial e focado em pedidos.',design:{fontFamily:'Poppins',background:'#fff7f2',radius:22,titleSize:54,spacing:52,alignment:'left',columns:3,buttonStyle:'pill'}},
 {id:'store-01',name:'Vitrine',category:'Varejo',version:3,colors:['#31572c','#f7f5ef'],description:'Catálogo sofisticado com foco em produto.',design:{fontFamily:'Inter',background:'#faf9f4',radius:18,titleSize:56,spacing:66,alignment:'left',columns:4,buttonStyle:'rounded'}},
 {id:'store-02',name:'Catálogo minimalista',category:'Varejo',version:2,colors:['#111111','#f1f1f1'],description:'Minimalista e editorial.',design:{fontFamily:'Inter',background:'#ffffff',radius:0,titleSize:60,spacing:82,alignment:'center',columns:4,buttonStyle:'square'}},
 {id:'service-01',name:'Profissional',category:'Serviços',version:3,colors:['#1357c4','#eff6ff'],description:'Confiável, direto e corporativo.',design:{fontFamily:'Inter',background:'#f8fbff',radius:18,titleSize:56,spacing:64,alignment:'left',columns:3,buttonStyle:'rounded'}},
 {id:'service-02',name:'Portfólio',category:'Serviços',version:2,colors:['#6d28d9','#f5efff'],description:'Criativo e focado em apresentação.',design:{fontFamily:'Poppins',background:'#fcf9ff',radius:28,titleSize:64,spacing:76,alignment:'center',columns:2,buttonStyle:'pill'}},
 {id:'clinic-01',name:'Clínica leve',category:'Saúde',version:3,colors:['#168aad','#eefbfc'],description:'Calmo, confiável e acolhedor.',design:{fontFamily:'Inter',background:'#f8fdfd',radius:24,titleSize:54,spacing:70,alignment:'left',columns:3,buttonStyle:'rounded'}},
 {id:'clinic-02',name:'Especialidades',category:'Saúde',version:2,colors:['#2d6a4f','#edf7f1'],description:'Institucional com foco em especialidades.',design:{fontFamily:'Montserrat',background:'#f7fbf8',radius:14,titleSize:58,spacing:72,alignment:'left',columns:3,buttonStyle:'rounded'}},
 {id:'gym-01',name:'Energia',category:'Fitness',version:2,colors:['#d4ff00','#101010'],description:'Alto contraste e energia.',design:{fontFamily:'Montserrat',background:'#111111',radius:6,titleSize:70,spacing:66,alignment:'left',columns:3,buttonStyle:'square'}},
 {id:'studio-01',name:'Movimento',category:'Fitness',version:2,colors:['#7b2cbf','#f3e8ff'],description:'Fluido, moderno e expressivo.',design:{fontFamily:'Poppins',background:'#fcf8ff',radius:30,titleSize:62,spacing:78,alignment:'center',columns:3,buttonStyle:'pill'}},
 {id:'generic-01',name:'Essencial',category:'Geral',version:3,colors:['#6548e8','#f5f1ff'],description:'Versátil, limpo e profissional.',design:{fontFamily:'Inter',background:'#ffffff',radius:18,titleSize:56,spacing:64,alignment:'left',columns:3,buttonStyle:'rounded'}},
 {id:'premium-01',name:'Premium',category:'Geral',version:3,colors:['#d5b36a','#171222'],description:'Luxuoso, escuro e marcante.',design:{fontFamily:'Playfair Display',background:'#171222',radius:8,titleSize:72,spacing:88,alignment:'center',columns:2,buttonStyle:'square'}},
] as const;
export const getTemplatePreset=(id:string)=>TEMPLATES.find(template=>template.id===id)??TEMPLATES[TEMPLATES.length-2]!;
export const applyTemplateDesign=(current:SiteDesign,id:string):SiteDesign=>({...current,...getTemplatePreset(id).design});
export const makeBlock=(type:BlockType,title=BLOCK_LABELS[type]):SiteBlock=>({id:crypto.randomUUID(),type,enabled:true,favorite:false,title,text:'',buttonText:type==='hero'?'Falar no WhatsApp':'',buttonUrl:'',mediaUrl:'',dataSource:DYNAMIC_BLOCKS.has(type)?'all':'manual',dataFilter:'',visibility:'all',style:{}});
export const createSegmentBlocks=(segment:string,name:string)=>{const specific:BlockType[]=segment.includes('restaurant')||segment.includes('snack')?['menu','online_order']:segment.includes('salon')||segment.includes('beauty')||segment.includes('barber')?['services','team','schedule']:segment.includes('retail')||segment.includes('market')?['products','promotion']:segment.includes('gym')||segment.includes('studio')?['plans','schedule']:['services','contact'];return [makeBlock('hero',name),...specific.map(type=>makeBlock(type)),makeBlock('testimonials'),makeBlock('hours'),makeBlock('map'),makeBlock('whatsapp')]};
