import { useEffect, useState } from 'react';
import { Button, Pill } from '@nexoio/ui';
import { api, ApiError } from '../lib/api';

type Integrations={googleAnalyticsId:string;metaPixelId:string;googleMapsUrl:string;whatsappUrl:string;instagramUrl:string;leadNotificationsEnabled:boolean;bookingAutoConfirm:boolean};
type Lead={id:string;name:string;phone?:string|null;email?:string|null;message?:string|null;status:string;created_at:string};
type Booking={id:string;customer_name?:string;customer_phone?:string;service_name?:string;professional_name?:string;requested_start:string;status:string};
type Summary={page_views:number;visitors:number;lead_submits:number;booking_submits:number;days:number};
const empty:Integrations={googleAnalyticsId:'',metaPixelId:'',googleMapsUrl:'',whatsappUrl:'',instagramUrl:'',leadNotificationsEnabled:true,bookingAutoConfirm:false};

export function SiteGrowthPanel(){
 const[data,setData]=useState<Integrations>(empty),[leads,setLeads]=useState<Lead[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[summary,setSummary]=useState<Summary|null>(null),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 const load=()=>Promise.all([api.get<{data:Integrations}>('/api/v1/site/integrations'),api.get<{data:Lead[]}>('/api/v1/site/leads'),api.get<{data:Booking[]}>('/api/v1/site/bookings'),api.get<{data:Summary}>('/api/v1/site/analytics/summary?days=30')]).then(([i,l,b,s])=>{setData(i.data);setLeads(l.data);setBookings(b.data);setSummary(s.data)}).catch(e=>setMessage(e instanceof ApiError?e.message:'Não foi possível carregar integrações.'));
 useEffect(()=>{void load()},[]);
 const save=async()=>{setSaving(true);setMessage('');try{await api.put('/api/v1/site/integrations',data);setMessage('Integrações salvas.')}catch(e){setMessage(e instanceof ApiError?e.message:'Não foi possível salvar.')}finally{setSaving(false)}};
 const leadStatus=async(id:string,status:string)=>{await api.patch(`/api/v1/site/leads/${id}`,{status});await load()};
 const bookingDecision=async(id:string,decision:'confirm'|'reject')=>{try{await api.post(`/api/v1/site/bookings/${id}/decision`,{decision});await load()}catch(e){setMessage(e instanceof ApiError?e.message:'Não foi possível atualizar o agendamento.')}};
 return <section style={{display:'grid',gap:16,margin:'16px 0'}}>
  <div className="card" style={{padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><strong>Conversão do site · 30 dias</strong><div style={{display:'flex',gap:16,marginTop:8,flexWrap:'wrap'}}><span>{summary?.page_views??0} visualizações</span><span>{summary?.visitors??0} visitantes</span><span>{summary?.lead_submits??0} leads</span><span>{summary?.booking_submits??0} agendamentos</span></div></div><Button ghost onClick={()=>void load()}>Atualizar</Button></div></div>
  <details className="card" style={{padding:18}}><summary style={{cursor:'pointer',fontWeight:800}}>Integrações, mapa e pixels</summary><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginTop:16}}><label>Google Analytics 4<input value={data.googleAnalyticsId} placeholder="G-XXXXXXXXXX" onChange={e=>setData(v=>({...v,googleAnalyticsId:e.target.value}))}/></label><label>Meta Pixel<input value={data.metaPixelId} placeholder="ID numérico" onChange={e=>setData(v=>({...v,metaPixelId:e.target.value}))}/></label><label>Google Maps<input value={data.googleMapsUrl} placeholder="https://maps.google.com/..." onChange={e=>setData(v=>({...v,googleMapsUrl:e.target.value}))}/></label><label>WhatsApp<input value={data.whatsappUrl} placeholder="https://wa.me/..." onChange={e=>setData(v=>({...v,whatsappUrl:e.target.value}))}/></label><label>Instagram<input value={data.instagramUrl} placeholder="https://instagram.com/..." onChange={e=>setData(v=>({...v,instagramUrl:e.target.value}))}/></label></div><div style={{display:'flex',gap:20,marginTop:14,flexWrap:'wrap'}}><label><input type="checkbox" checked={data.leadNotificationsEnabled} onChange={e=>setData(v=>({...v,leadNotificationsEnabled:e.target.checked}))}/> Notificar novos leads</label><label><input type="checkbox" checked={data.bookingAutoConfirm} onChange={e=>setData(v=>({...v,bookingAutoConfirm:e.target.checked}))}/> Confirmar agendamento automaticamente quando possível</label></div><div style={{marginTop:14}}><Button onClick={()=>void save()}>{saving?'Salvando…':'Salvar integrações'}</Button></div></details>
  <details className="card" style={{padding:18}}><summary style={{cursor:'pointer',fontWeight:800}}>Leads do site ({leads.filter(x=>x.status==='new').length} novos)</summary><div style={{display:'grid',gap:10,marginTop:14}}>{leads.length?leads.slice(0,50).map(lead=><div key={lead.id} style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',borderBottom:'1px solid #eee',paddingBottom:10}}><div><strong>{lead.name}</strong><div>{lead.phone||lead.email||'Sem contato'}</div>{lead.message?<small>{lead.message}</small>:null}</div><div style={{display:'flex',gap:8,alignItems:'center'}}><Pill>{lead.status}</Pill>{lead.status==='new'?<Button ghost onClick={()=>void leadStatus(lead.id,'contacted')}>Marcar contatado</Button>:null}</div></div>):<span>Nenhum lead ainda.</span>}</div></details>
  <details className="card" style={{padding:18}}><summary style={{cursor:'pointer',fontWeight:800}}>Solicitações de agendamento ({bookings.filter(x=>x.status==='pending').length} pendentes)</summary><div style={{display:'grid',gap:10,marginTop:14}}>{bookings.length?bookings.slice(0,50).map(b=><div key={b.id} style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',borderBottom:'1px solid #eee',paddingBottom:10}}><div><strong>{b.customer_name||'Cliente'}</strong><div>{b.service_name||'Serviço'} · {new Date(b.requested_start).toLocaleString('pt-BR')}</div><small>{b.professional_name||b.customer_phone||''}</small></div><div style={{display:'flex',gap:8,alignItems:'center'}}><Pill>{b.status}</Pill>{b.status==='pending'?<><Button ghost onClick={()=>void bookingDecision(b.id,'reject')}>Recusar</Button><Button onClick={()=>void bookingDecision(b.id,'confirm')}>Confirmar</Button></>:null}</div></div>):<span>Nenhuma solicitação ainda.</span>}</div></details>
  {message?<div className="toast" role="status">{message}</div>:null}
 </section>;
}
