import { useEffect, useState } from 'react';
import { Button, Pill } from '@nexoio/ui';
import { api, ApiError } from '../lib/api';

type Domain={id:string;hostname:string;verification_status:string;ssl_status:string;dns_target:string|null;validation_json:Record<string,unknown>};
type Media={id:string;original_name:string;mime_type:string;size_bytes:number;visibility:string;purpose:string;created_at:string};
export function SiteInfrastructurePanel({onMediaSelected}:{onMediaSelected:(url:string)=>void}){
 const[domains,setDomains]=useState<Domain[]>([]),[media,setMedia]=useState<Media[]>([]),[hostname,setHostname]=useState(''),[message,setMessage]=useState(''),[working,setWorking]=useState(false);
 const load=async()=>{try{const[d,m]=await Promise.all([api.get<{data:Domain[]}>('/api/v1/domains'),api.get<{data:Media[]}>('/api/v1/media')]);setDomains(d.data);setMedia(m.data)}catch(reason){setMessage(reason instanceof ApiError?reason.message:'Não foi possível carregar domínio e mídia.')}};
 useEffect(()=>{void load()},[]);
 const addDomain=async()=>{if(!hostname.trim())return;setWorking(true);setMessage('');try{await api.post('/api/v1/domains',{hostname});setHostname('');await load();setMessage('Domínio cadastrado. Siga a validação DNS exibida abaixo.')}catch(reason){setMessage(reason instanceof ApiError?reason.message:'Não foi possível cadastrar o domínio.')}finally{setWorking(false)}};
 const refresh=async(id:string)=>{setWorking(true);try{await api.post(`/api/v1/domains/${id}/refresh`,{});await load()}catch(reason){setMessage(reason instanceof ApiError?reason.message:'Falha ao validar domínio.')}finally{setWorking(false)}};
 const remove=async(id:string)=>{if(!confirm('Remover este domínio do site?'))return;setWorking(true);try{await api.delete(`/api/v1/domains/${id}`);await load()}catch(reason){setMessage(reason instanceof ApiError?reason.message:'Falha ao remover domínio.')}finally{setWorking(false)}};
 const upload=async(file:File)=>{setWorking(true);setMessage('');try{const form=new FormData();form.set('file',file);form.set('purpose','site');form.set('visibility','public');const result=await api.upload<{data:{url:string}}>('/api/v1/media',form);onMediaSelected(result.data.url);await load();setMessage('Imagem enviada para o R2 e aplicada ao bloco selecionado.')}catch(reason){setMessage(reason instanceof ApiError?reason.message:'Não foi possível enviar a imagem.')}finally{setWorking(false)}};
 return <section className="site-infra-panel"><div className="site-infra-card"><h3>Domínio próprio</h3><p>Cadastre o domínio, valide o DNS e acompanhe o SSL sem configuração manual por cliente.</p><div className="site-infra-row"><input value={hostname} onChange={e=>setHostname(e.target.value)} placeholder="www.seudominio.com.br"/><Button onClick={()=>void addDomain()} disabled={working||!hostname.trim()}>Adicionar</Button></div>{domains.map(domain=><div className="site-domain" key={domain.id}><div><strong>{domain.hostname}</strong><div className="site-infra-badges"><Pill tone={domain.verification_status==='verified'?'success':'warning'}>{domain.verification_status}</Pill><Pill tone={domain.ssl_status==='active'?'success':'warning'}>SSL {domain.ssl_status}</Pill></div></div><div className="site-domain-instructions">{domain.dns_target?<span>DNS/CNAME: <code>{domain.dns_target}</code></span>:<span>Aguardando alvo DNS do ambiente.</span>}</div><div className="row-actions"><button onClick={()=>void refresh(domain.id)} disabled={working}>Verificar</button><button onClick={()=>void remove(domain.id)} disabled={working}>Remover</button></div></div>)}</div><div className="site-infra-card"><h3>Mídia do site</h3><p>Logo, banners e fotos ficam no R2 com validação de tipo, tamanho e quota.</p><label className="site-upload"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" disabled={working} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);event.currentTarget.value=''}}/><span>{working?'Enviando…':'Enviar imagem e usar no bloco'}</span></label>{media.length?<small>{media.length} arquivo(s) armazenado(s) para este negócio.</small>:<small>Nenhuma mídia enviada.</small>}</div>{message?<div className="auth-notice" role="status">{message}</div>:null}</section>;
}
