import { Hono } from 'hono';
import { createMiddleware } from 'hono/factory';
import { eq, sql } from 'drizzle-orm';
import { z } from 'zod';
import { platformAdmins, users } from '@nexoio/db';
import { uuidv7 } from '@nexoio/core';
import { error, requireSession } from '../middleware';
import type { ApiEnv } from '../types';

const rows=(r:any)=>r?.rows??r??[];
const masterGuard=createMiddleware<ApiEnv>(async(c,next)=>{const row=(await c.get('db').select({status:platformAdmins.status,mfaRequired:platformAdmins.mfaRequired}).from(platformAdmins).innerJoin(users,eq(users.id,platformAdmins.userId)).where(eq(users.authUserId,c.get('sessionUser').id)).limit(1))[0];if(!row||row.status!=='active')return error(c,403,'FORBIDDEN','Acesso exclusivo do Master Admin');if(row.mfaRequired&&!c.get('sessionUser').twoFactorEnabled)return error(c,403,'MFA_REQUIRED','MFA obrigatório para esta ação');await next()});
async function audit(c:any,action:string,entityType:string,entityId:string|null,beforeJson:any,afterJson:any){await c.get('db').execute(sql`insert into audit_logs(id,user_id,action,entity_type,entity_id,before_json,after_json,request_id,ip_address,user_agent,created_at) values(${uuidv7()},${c.get('sessionUser').profileId??null}::uuid,${action},${entityType},${entityId},${beforeJson?JSON.stringify(beforeJson):null}::jsonb,${afterJson?JSON.stringify(afterJson):null}::jsonb,${c.get('requestId')},${c.req.header('cf-connecting-ip')??null},${c.req.header('user-agent')?.slice(0,500)??null},now())`)}

export const adminMasterRoutes=new Hono<ApiEnv>();
adminMasterRoutes.use('*',requireSession,masterGuard);

adminMasterRoutes.get('/dashboard/master',async c=>{const r=await c.get('db').execute(sql`
select
 (select count(*) from businesses) businesses_total,
 (select count(*) from businesses where status='active') businesses_active,
 (select count(*) from subscriptions where status in ('active','trialing')) subscriptions_active,
 (select count(*) from subscriptions where status='past_due') subscriptions_past_due,
 (select coalesce(sum(p.price_monthly),0) from subscriptions s join plans p on p.id=s.plan_id where s.status in ('active','trialing')) mrr,
 (select count(*) from business_domains where verification_status='verified') domains_verified,
 (select count(*) from business_domains where verification_status<>'verified') domains_pending,
 (select count(*) from platform_support_tickets where status not in ('resolved','closed')) support_open,
 (select count(*) from platform_incidents where status<>'resolved') incidents_open,
 (select coalesce(sum(size_bytes),0) from files where deleted_at is null) storage_bytes
`);return c.json({data:rows(r)[0]})});

adminMasterRoutes.get('/businesses/:id/detail',async c=>{const id=c.req.param('id');const r=await c.get('db').execute(sql`
select b.*,coalesce(jsonb_build_object('id',s.id,'status',s.status,'planId',s.plan_id,'planName',p.name,'planCode',p.code,'priceMonthly',p.price_monthly,'currentPeriodEnd',s.current_period_end,'provider',s.provider),'{}'::jsonb) subscription,
 coalesce((select jsonb_agg(jsonb_build_object('metric',u.metric,'period',u.period,'value',u.value) order by u.period desc) from usage_counters u where u.business_id=b.id),'[]'::jsonb) usage,
 coalesce((select jsonb_agg(jsonb_build_object('hostname',d.hostname,'verificationStatus',d.verification_status,'sslStatus',d.ssl_status) order by d.created_at desc) from business_domains d where d.business_id=b.id),'[]'::jsonb) domains,
 coalesce((select jsonb_build_object('storageLimitBytes',q.storage_limit_bytes,'updatedAt',q.updated_at) from business_quotas q where q.business_id=b.id),'{}'::jsonb) quota,
 coalesce((select sum(f.size_bytes) from files f where f.business_id=b.id and f.deleted_at is null),0) storage_used_bytes
from businesses b left join subscriptions s on s.business_id=b.id left join plans p on p.id=s.plan_id where b.id=${id}::uuid limit 1`);const item=rows(r)[0];return item?c.json({data:item}):error(c,404,'BUSINESS_NOT_FOUND','Empresa não encontrada')});

adminMasterRoutes.patch('/businesses/:id/quota',async c=>{const parsed=z.object({storageLimitBytes:z.number().int().min(10485760).max(1099511627776)}).safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,422,'VALIDATION_ERROR','Quota inválida');const id=c.req.param('id');const before=rows(await c.get('db').execute(sql`select storage_limit_bytes from business_quotas where business_id=${id}::uuid limit 1`))[0]??null;const r=await c.get('db').execute(sql`insert into business_quotas(business_id,storage_limit_bytes,updated_at) values(${id}::uuid,${parsed.data.storageLimitBytes},now()) on conflict(business_id) do update set storage_limit_bytes=excluded.storage_limit_bytes,updated_at=now() returning *`);await audit(c,'admin.business.quota.update','business',id,before,rows(r)[0]);return c.json({data:rows(r)[0]})});

adminMasterRoutes.get('/support',async c=>{const r=await c.get('db').execute(sql`select t.*,b.display_name business_name from platform_support_tickets t left join businesses b on b.id=t.business_id order by case t.priority when 'urgent' then 0 when 'high' then 1 when 'normal' then 2 else 3 end,t.created_at desc limit 500`);return c.json({data:rows(r)})});
adminMasterRoutes.post('/support',async c=>{const p=z.object({businessId:z.uuid().optional(),subject:z.string().min(3).max(200),description:z.string().min(3).max(5000),priority:z.enum(['low','normal','high','urgent']).default('normal'),category:z.string().max(80).optional()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Chamado inválido');const id=uuidv7();await c.get('db').execute(sql`insert into platform_support_tickets(id,business_id,subject,description,priority,category,status) values(${id},${p.data.businessId??null}::uuid,${p.data.subject},${p.data.description},${p.data.priority},${p.data.category??null},'open')`);await audit(c,'admin.support.create','support_ticket',id,null,p.data);return c.json({data:{id,...p.data,status:'open'}},201)});
adminMasterRoutes.patch('/support/:id',async c=>{const p=z.object({status:z.enum(['open','in_progress','waiting_customer','resolved','closed']).optional(),priority:z.enum(['low','normal','high','urgent']).optional()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Atualização inválida');const id=c.req.param('id');const before=rows(await c.get('db').execute(sql`select * from platform_support_tickets where id=${id}::uuid limit 1`))[0];if(!before)return error(c,404,'NOT_FOUND','Chamado não encontrado');const r=await c.get('db').execute(sql`update platform_support_tickets set status=coalesce(${p.data.status??null},status),priority=coalesce(${p.data.priority??null},priority),resolved_at=case when ${p.data.status??null} in ('resolved','closed') then now() else resolved_at end,updated_at=now() where id=${id}::uuid returning *`);await audit(c,'admin.support.update','support_ticket',id,before,rows(r)[0]);return c.json({data:rows(r)[0]})});

adminMasterRoutes.get('/incidents/master',async c=>{const r=await c.get('db').execute(sql`select * from platform_incidents order by started_at desc limit 300`);return c.json({data:rows(r)})});
adminMasterRoutes.post('/incidents/master',async c=>{const p=z.object({title:z.string().min(3).max(200),description:z.string().max(5000).optional(),severity:z.enum(['minor','major','critical']).default('minor'),service:z.string().max(100).optional(),publicMessage:z.string().max(1000).optional()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Incidente inválido');const id=uuidv7();await c.get('db').execute(sql`insert into platform_incidents(id,title,description,severity,status,service,public_message) values(${id},${p.data.title},${p.data.description??null},${p.data.severity},'investigating',${p.data.service??null},${p.data.publicMessage??null})`);await audit(c,'admin.incident.create','incident',id,null,p.data);return c.json({data:{id,...p.data,status:'investigating'}},201)});
adminMasterRoutes.patch('/incidents/master/:id',async c=>{const p=z.object({status:z.enum(['investigating','identified','monitoring','resolved']),publicMessage:z.string().max(1000).optional()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Atualização inválida');const id=c.req.param('id'),before=rows(await c.get('db').execute(sql`select * from platform_incidents where id=${id}::uuid limit 1`))[0];if(!before)return error(c,404,'NOT_FOUND','Incidente não encontrado');const r=await c.get('db').execute(sql`update platform_incidents set status=${p.data.status},public_message=coalesce(${p.data.publicMessage??null},public_message),resolved_at=case when ${p.data.status}='resolved' then now() else null end,updated_at=now() where id=${id}::uuid returning *`);await audit(c,'admin.incident.update','incident',id,before,rows(r)[0]);return c.json({data:rows(r)[0]})});

adminMasterRoutes.get('/templates/master',async c=>c.json({data:rows(await c.get('db').execute(sql`select * from site_templates order by category,name`))}));
adminMasterRoutes.patch('/templates/master/:id',async c=>{const p=z.object({status:z.enum(['active','inactive']),name:z.string().min(2).max(120).optional()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Template inválido');const id=c.req.param('id'),before=rows(await c.get('db').execute(sql`select * from site_templates where id=${id}::uuid limit 1`))[0];if(!before)return error(c,404,'NOT_FOUND','Template não encontrado');const r=await c.get('db').execute(sql`update site_templates set status=${p.data.status},name=coalesce(${p.data.name??null},name),updated_at=now() where id=${id}::uuid returning *`);await audit(c,'admin.template.update','site_template',id,before,rows(r)[0]);return c.json({data:rows(r)[0]})});

adminMasterRoutes.get('/finance/master',async c=>{const r=await c.get('db').execute(sql`select date_trunc('month',coalesce(si.paid_at,si.created_at)) month,coalesce(sum(si.amount) filter(where si.status='paid'),0) received,coalesce(sum(si.amount) filter(where si.status in ('pending','overdue')),0) outstanding,count(*) invoices from subscription_invoices si group by 1 order by 1 desc limit 24`);const entries=await c.get('db').execute(sql`select * from platform_finance_entries order by competence_date desc,created_at desc limit 500`);return c.json({data:{monthly:rows(r),entries:rows(entries)}})});
adminMasterRoutes.post('/finance/master/entries',async c=>{const p=z.object({kind:z.enum(['income','expense']),category:z.string().min(2).max(120),description:z.string().min(2).max(300),amount:z.number().positive(),competenceDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),paid:z.boolean().default(false)}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Lançamento inválido');const id=uuidv7();await c.get('db').execute(sql`insert into platform_finance_entries(id,kind,category,description,amount,competence_date,paid_at,status) values(${id},${p.data.kind},${p.data.category},${p.data.description},${p.data.amount},${p.data.competenceDate}::date,${p.data.paid?new Date():null},${p.data.paid?'paid':'pending'})`);await audit(c,'admin.finance.entry.create','platform_finance_entry',id,null,p.data);return c.json({data:{id,...p.data}},201)});
