import { Hono } from 'hono';
import { createMiddleware } from 'hono/factory';
import { eq, sql } from 'drizzle-orm';
import { z } from 'zod';
import { platformAdmins, users } from '@nexoio/db';
import { uuidv7 } from '@nexoio/core';
import { error, requireSession } from '../middleware';
import type { ApiEnv } from '../types';

const rows=(r:any)=>r?.rows??r??[];
const masterGuard=createMiddleware<ApiEnv>(async(c,next)=>{const row=(await c.get('db').select({status:platformAdmins.status,mfaRequired:platformAdmins.mfaRequired}).from(platformAdmins).innerJoin(users,eq(users.id,platformAdmins.userId)).where(eq(users.authUserId,c.get('sessionUser').id)).limit(1))[0];if(!row||row.status!=='active')return error(c,403,'FORBIDDEN','Acesso exclusivo do Master Admin');if(row.mfaRequired&&!c.get('sessionUser').twoFactorEnabled)return error(c,403,'MFA_REQUIRED','MFA obrigatório para esta ação');await next()});
async function audit(c:any,action:string,entityType:string,entityId:string|null,beforeJson:unknown,afterJson:unknown){await c.get('db').execute(sql`insert into audit_logs(id,user_id,action,entity_type,entity_id,before_json,after_json,request_id,ip_address,user_agent,created_at) values(${uuidv7()},${c.get('sessionUser').profileId??null}::uuid,${action},${entityType},${entityId},${beforeJson?JSON.stringify(beforeJson):null}::jsonb,${afterJson?JSON.stringify(afterJson):null}::jsonb,${c.get('requestId')},${c.req.header('cf-connecting-ip')??null},${c.req.header('user-agent')?.slice(0,500)??null},now())`)}
function billingConfig(c:any){if((c.env.BILLING_PROVIDER??'').toLowerCase()!=='asaas'||!c.env.BILLING_API_URL||!c.env.BILLING_API_KEY)return null;return{base:String(c.env.BILLING_API_URL).replace(/\/$/,''),key:String(c.env.BILLING_API_KEY)}}
async function asaas(c:any,path:string,init:RequestInit={}){const cfg=billingConfig(c);if(!cfg)throw new Error('BILLING_NOT_CONFIGURED');const response=await fetch(`${cfg.base}${path}`,{...init,headers:{accept:'application/json','content-type':'application/json',access_token:cfg.key,'user-agent':'Nexoio-Admin/1.0',...(init.headers??{})}});const body:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.errors?.[0]?.description??body?.message??`Asaas ${response.status}`);return body;}
async function cloudflare(c:any,path:string,init:RequestInit={}){if(!c.env.CLOUDFLARE_API_TOKEN||!c.env.CLOUDFLARE_ZONE_ID)throw new Error('CLOUDFLARE_NOT_CONFIGURED');const response=await fetch(`https://api.cloudflare.com/client/v4/zones/${c.env.CLOUDFLARE_ZONE_ID}${path}`,{...init,headers:{Authorization:`Bearer ${c.env.CLOUDFLARE_API_TOKEN}`,'content-type':'application/json',...(init.headers??{})}});const body:any=await response.json().catch(()=>({}));if(!response.ok||body?.success===false)throw new Error(body?.errors?.[0]?.message??`Cloudflare ${response.status}`);return body?.result;}

export const adminOperationsRoutes=new Hono<ApiEnv>();
adminOperationsRoutes.use('*',requireSession,masterGuard);

adminOperationsRoutes.get('/operations/subscriptions',async c=>{const r=await c.get('db').execute(sql`select s.id,s.business_id,b.display_name business_name,s.plan_id,p.name plan_name,p.price_monthly,s.status,s.current_period_start,s.current_period_end,s.provider,s.provider_customer_id,s.provider_subscription_id,s.cancel_at_period_end,s.updated_at,coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'amount',i.amount,'status',i.status,'dueDate',i.due_date,'paidAt',i.paid_at) order by i.created_at desc) from subscription_invoices i where i.subscription_id=s.id),'[]'::jsonb) invoices from subscriptions s join businesses b on b.id=s.business_id join plans p on p.id=s.plan_id order by s.updated_at desc limit 500`);return c.json({data:rows(r)})});
adminOperationsRoutes.patch('/operations/subscriptions/:id',async c=>{const id=z.uuid().safeParse(c.req.param('id'));const parsed=z.object({planId:z.uuid().optional(),status:z.enum(['pending','trialing','active','past_due','cancelled','paused']).optional(),currentPeriodEnd:z.iso.datetime().nullable().optional(),cancelAtPeriodEnd:z.boolean().optional()}).refine(v=>Object.keys(v).length>0).safeParse(await c.req.json().catch(()=>null));if(!id.success||!parsed.success)return error(c,422,'VALIDATION_ERROR','Atualização de assinatura inválida');const before=rows(await c.get('db').execute(sql`select s.*,p.price_monthly from subscriptions s join plans p on p.id=s.plan_id where s.id=${id.data}::uuid limit 1`))[0] as any;if(!before)return error(c,404,'NOT_FOUND','Assinatura não encontrada');if(parsed.data.planId){const plan=rows(await c.get('db').execute(sql`select id,price_monthly,name from plans where id=${parsed.data.planId}::uuid limit 1`))[0] as any;if(!plan)return error(c,404,'PLAN_NOT_FOUND','Plano não encontrado');if(before.provider==='asaas'&&before.provider_subscription_id&&billingConfig(c)){try{await asaas(c,`/subscriptions/${encodeURIComponent(before.provider_subscription_id)}`,{method:'PUT',body:JSON.stringify({value:Number(plan.price_monthly),description:`Nexoio - ${plan.name}`})});}catch(reason){return error(c,502,'BILLING_PROVIDER_ERROR',reason instanceof Error?reason.message:'Falha ao atualizar assinatura no provedor')}}}
if(parsed.data.status==='cancelled'&&before.provider==='asaas'&&before.provider_subscription_id&&billingConfig(c)&&parsed.data.cancelAtPeriodEnd===false){try{await asaas(c,`/subscriptions/${encodeURIComponent(before.provider_subscription_id)}`,{method:'DELETE'});}catch(reason){return error(c,502,'BILLING_PROVIDER_ERROR',reason instanceof Error?reason.message:'Falha ao cancelar assinatura no provedor')}}
const r=await c.get('db').execute(sql`update subscriptions set plan_id=coalesce(${parsed.data.planId??null}::uuid,plan_id),status=coalesce(${parsed.data.status??null},status),current_period_end=case when ${parsed.data.currentPeriodEnd===undefined?'__KEEP__':parsed.data.currentPeriodEnd}='__KEEP__' then current_period_end else ${parsed.data.currentPeriodEnd??null}::timestamptz end,cancel_at_period_end=coalesce(${parsed.data.cancelAtPeriodEnd??null},cancel_at_period_end),cancelled_at=case when ${parsed.data.status??null}='cancelled' then now() else cancelled_at end,updated_at=now() where id=${id.data}::uuid returning *`);await audit(c,'admin.subscription.update','subscription',id.data,before,rows(r)[0]);return c.json({data:rows(r)[0]})});

adminOperationsRoutes.get('/operations/domains',async c=>c.json({data:rows(await c.get('db').execute(sql`select d.*,b.display_name business_name from business_domains d join businesses b on b.id=d.business_id order by d.updated_at desc,d.created_at desc limit 500`))}));
adminOperationsRoutes.post('/operations/domains/:id/refresh',async c=>{const id=z.uuid().safeParse(c.req.param('id'));if(!id.success)return error(c,422,'VALIDATION_ERROR','Domínio inválido');const domain=rows(await c.get('db').execute(sql`select * from business_domains where id=${id.data}::uuid limit 1`))[0] as any;if(!domain)return error(c,404,'NOT_FOUND','Domínio não encontrado');if(!domain.provider_hostname_id)return error(c,409,'DOMAIN_PROVIDER_NOT_LINKED','Domínio sem vínculo com Cloudflare');try{const provider:any=await cloudflare(c,`/custom_hostnames/${encodeURIComponent(domain.provider_hostname_id)}`);const verificationStatus=provider?.status==='active'&&provider?.ssl?.status==='active'?'verified':provider?.status??'pending';const validation={ownership:provider?.ownership_verification??null,ownershipHttp:provider?.ownership_verification_http??null,ssl:provider?.ssl?.validation_records??[],providerStatus:provider?.status??null};const r=await c.get('db').execute(sql`update business_domains set verification_status=${verificationStatus},ssl_status=${provider?.ssl?.status??'pending'},validation_json=${JSON.stringify(validation)}::jsonb,updated_at=now() where id=${id.data}::uuid returning *`);await audit(c,'admin.domain.refresh','business_domain',id.data,domain,rows(r)[0]);return c.json({data:rows(r)[0]})}catch(reason){return error(c,502,'DOMAIN_PROVIDER_ERROR',reason instanceof Error?reason.message:'Falha ao consultar domínio')}});
adminOperationsRoutes.delete('/operations/domains/:id',async c=>{const id=z.uuid().safeParse(c.req.param('id'));if(!id.success)return error(c,422,'VALIDATION_ERROR','Domínio inválido');const domain=rows(await c.get('db').execute(sql`select * from business_domains where id=${id.data}::uuid limit 1`))[0] as any;if(!domain)return error(c,404,'NOT_FOUND','Domínio não encontrado');if(domain.provider_hostname_id){try{await cloudflare(c,`/custom_hostnames/${encodeURIComponent(domain.provider_hostname_id)}`,{method:'DELETE'})}catch(reason){return error(c,502,'DOMAIN_PROVIDER_ERROR',reason instanceof Error?reason.message:'Falha ao remover domínio no provedor')}}await c.get('db').execute(sql`delete from business_domains where id=${id.data}::uuid`);await audit(c,'admin.domain.delete','business_domain',id.data,domain,{deleted:true});return c.json({data:{id:id.data,deleted:true}})});

adminOperationsRoutes.get('/operations/usage',async c=>{const r=await c.get('db').execute(sql`select b.id business_id,b.display_name business_name,coalesce(q.storage_limit_bytes,104857600) storage_limit_bytes,coalesce((select sum(f.size_bytes) from files f where f.business_id=b.id and f.deleted_at is null),0) storage_used_bytes,coalesce((select jsonb_agg(jsonb_build_object('metric',u.metric,'period',u.period,'value',u.value) order by u.period desc,u.metric) from usage_counters u where u.business_id=b.id),'[]'::jsonb) usage from businesses b left join business_quotas q on q.business_id=b.id order by b.display_name`);return c.json({data:rows(r)})});
adminOperationsRoutes.patch('/operations/businesses/:id/quota',async c=>{const id=z.uuid().safeParse(c.req.param('id'));const parsed=z.object({storageLimitBytes:z.number().int().min(10485760).max(1099511627776)}).safeParse(await c.req.json().catch(()=>null));if(!id.success||!parsed.success)return error(c,422,'VALIDATION_ERROR','Quota inválida');const before=rows(await c.get('db').execute(sql`select * from business_quotas where business_id=${id.data}::uuid`))[0]??null;const r=await c.get('db').execute(sql`insert into business_quotas(business_id,storage_limit_bytes,updated_at) values(${id.data}::uuid,${parsed.data.storageLimitBytes},now()) on conflict(business_id) do update set storage_limit_bytes=excluded.storage_limit_bytes,updated_at=now() returning *`);await audit(c,'admin.business.quota.update','business',id.data,before,rows(r)[0]);return c.json({data:rows(r)[0]})});

adminOperationsRoutes.get('/operations/users',async c=>{const r=await c.get('db').execute(sql`select u.id,u.auth_user_id,u.name,u.email,u.status,u.last_login_at,au.email_verified,au.two_factor_enabled,u.created_at,coalesce((select jsonb_agg(jsonb_build_object('businessId',bm.business_id,'businessName',b.display_name,'role',r.name,'status',bm.status)) from business_memberships bm join businesses b on b.id=bm.business_id join roles r on r.id=bm.role_id where bm.user_id=u.id),'[]'::jsonb) memberships from users u join auth_users au on au.id=u.auth_user_id order by u.created_at desc limit 500`);return c.json({data:rows(r)})});
adminOperationsRoutes.patch('/operations/users/:id/status',async c=>{const id=z.uuid().safeParse(c.req.param('id'));const parsed=z.object({status:z.enum(['active','suspended'])}).safeParse(await c.req.json().catch(()=>null));if(!id.success||!parsed.success)return error(c,422,'VALIDATION_ERROR','Status inválido');const before=rows(await c.get('db').execute(sql`select * from users where id=${id.data}::uuid limit 1`))[0] as any;if(!before)return error(c,404,'NOT_FOUND','Usuário não encontrado');if(before.auth_user_id===c.get('sessionUser').id&&parsed.data.status==='suspended')return error(c,409,'SELF_SUSPEND_BLOCKED','Não é possível suspender a própria conta Master');const r=await c.get('db').execute(sql`update users set status=${parsed.data.status},updated_at=now() where id=${id.data}::uuid returning *`);if(parsed.data.status==='suspended')await c.get('db').execute(sql`delete from auth_sessions where user_id=${before.auth_user_id}`);await audit(c,'admin.user.status.update','user',id.data,before,rows(r)[0]);return c.json({data:rows(r)[0]})});

adminOperationsRoutes.get('/operations/modules',async c=>{const businessId=c.req.query('businessId');if(businessId){const parsed=z.uuid().safeParse(businessId);if(!parsed.success)return error(c,422,'VALIDATION_ERROR','Empresa inválida');const r=await c.get('db').execute(sql`select m.key,m.name,m.description,m.core,m.active,m.dependencies_json,coalesce(bm.enabled,false) enabled,bm.source from modules m left join business_modules bm on bm.module_code=m.key and bm.business_id=${parsed.data}::uuid order by m.core desc,m.name`);return c.json({data:rows(r)})}const r=await c.get('db').execute(sql`select m.*,coalesce((select count(*) from business_modules bm where bm.module_code=m.key and bm.enabled=true),0)::int enabled_businesses from modules m order by m.core desc,m.name`);return c.json({data:rows(r)})});
adminOperationsRoutes.patch('/operations/businesses/:businessId/modules/:moduleCode',async c=>{const businessId=z.uuid().safeParse(c.req.param('businessId'));const moduleCode=c.req.param('moduleCode');const parsed=z.object({enabled:z.boolean()}).safeParse(await c.req.json().catch(()=>null));if(!businessId.success||!parsed.success)return error(c,422,'VALIDATION_ERROR','Alteração de módulo inválida');const module=rows(await c.get('db').execute(sql`select * from modules where key=${moduleCode} limit 1`))[0] as any;if(!module)return error(c,404,'MODULE_NOT_FOUND','Módulo não encontrado');const before=rows(await c.get('db').execute(sql`select * from business_modules where business_id=${businessId.data}::uuid and module_code=${moduleCode}`))[0]??null;if(!parsed.data.enabled&&module.core)return error(c,409,'CORE_MODULE_REQUIRED','Módulo essencial não pode ser desativado');if(parsed.data.enabled){const deps=Array.isArray(module.dependencies_json)?module.dependencies_json:[];for(const dep of deps){await c.get('db').execute(sql`insert into business_modules(id,business_id,module_code,enabled,source,updated_at) values(${uuidv7()},${businessId.data}::uuid,${String(dep)},true,'admin_override',now()) on conflict(business_id,module_code) do update set enabled=true,source='admin_override',updated_at=now()`)}}else{const dependent=rows(await c.get('db').execute(sql`select m.key,m.name from modules m join business_modules bm on bm.module_code=m.key and bm.business_id=${businessId.data}::uuid and bm.enabled=true where m.dependencies_json @> ${JSON.stringify([moduleCode])}::jsonb limit 1`))[0] as any;if(dependent)return error(c,409,'MODULE_DEPENDENCY_ACTIVE',`${dependent.name} depende deste módulo`)}const r=await c.get('db').execute(sql`insert into business_modules(id,business_id,module_code,enabled,source,updated_at) values(${uuidv7()},${businessId.data}::uuid,${moduleCode},${parsed.data.enabled},'admin_override',now()) on conflict(business_id,module_code) do update set enabled=excluded.enabled,source='admin_override',updated_at=now() returning *`);await audit(c,'admin.business.module.update','business',businessId.data,before,{moduleCode,enabled:parsed.data.enabled});return c.json({data:rows(r)[0]})});

adminOperationsRoutes.get('/operations/sites',async c=>c.json({data:rows(await c.get('db').execute(sql`select b.id business_id,b.display_name business_name,b.public_slug,p.headline,p.published,p.updated_at,coalesce((select count(*) from business_domains d where d.business_id=b.id and d.verification_status='verified'),0)::int verified_domains from businesses b left join business_public_profiles p on p.business_id=b.id order by p.updated_at desc nulls last,b.display_name`))}));
adminOperationsRoutes.patch('/operations/sites/:businessId',async c=>{const businessId=z.uuid().safeParse(c.req.param('businessId'));const parsed=z.object({published:z.boolean()}).safeParse(await c.req.json().catch(()=>null));if(!businessId.success||!parsed.success)return error(c,422,'VALIDATION_ERROR','Publicação inválida');const before=rows(await c.get('db').execute(sql`select * from business_public_profiles where business_id=${businessId.data}::uuid limit 1`))[0] as any;if(!before)return error(c,404,'NOT_FOUND','Site público não configurado');const r=await c.get('db').execute(sql`update business_public_profiles set published=${parsed.data.published},updated_at=now() where business_id=${businessId.data}::uuid returning *`);await audit(c,'admin.site.publish.update','business_public_profile',businessId.data,before,rows(r)[0]);return c.json({data:rows(r)[0]})});

adminOperationsRoutes.patch('/operations/plans/:id',async c=>{const id=z.uuid().safeParse(c.req.param('id'));const parsed=z.object({name:z.string().trim().min(2).max(120).optional(),priceMonthly:z.number().min(0).max(1000000).optional(),active:z.boolean().optional()}).refine(v=>Object.keys(v).length>0).safeParse(await c.req.json().catch(()=>null));if(!id.success||!parsed.success)return error(c,422,'VALIDATION_ERROR','Plano inválido');const before=rows(await c.get('db').execute(sql`select * from plans where id=${id.data}::uuid limit 1`))[0] as any;if(!before)return error(c,404,'NOT_FOUND','Plano não encontrado');const r=await c.get('db').execute(sql`update plans set name=coalesce(${parsed.data.name??null},name),price_monthly=coalesce(${parsed.data.priceMonthly??null},price_monthly),active=coalesce(${parsed.data.active??null},active) where id=${id.data}::uuid returning *`);await audit(c,'admin.plan.update','plan',id.data,before,rows(r)[0]);return c.json({data:rows(r)[0]})});
