import { sql } from 'drizzle-orm';
import { Hono } from 'hono';
import { z } from 'zod';
import { uuidv7 } from '@nexoio/core';
import { error, requirePermission } from '../middleware';
import type { ApiEnv } from '../types';

export const billingLifecycleRoutes=new Hono<ApiEnv>();
const rows=(r:any)=>r?.rows??r??[];
function config(c:any){if((c.env.BILLING_PROVIDER??'').toLowerCase()!=='asaas'||!c.env.BILLING_API_URL||!c.env.BILLING_API_KEY)return null;return{base:String(c.env.BILLING_API_URL).replace(/\/$/,''),key:String(c.env.BILLING_API_KEY)}}
async function asaas(c:any,path:string,init:RequestInit={}){const cfg=config(c);if(!cfg)throw new Error('BILLING_NOT_CONFIGURED');const res=await fetch(`${cfg.base}${path}`,{...init,headers:{accept:'application/json','content-type':'application/json',access_token:cfg.key,'user-agent':'Nexoio/1.0',...(init.headers??{})}});const body:any=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body?.errors?.[0]?.description??body?.message??`Asaas ${res.status}`);return body;}

billingLifecycleRoutes.get('/billing/plans',requirePermission('settings.read'),async c=>{const result=await c.get('db').execute(sql`select p.id,p.code,p.name,p.description,p.price_monthly,p.active,p.trial_days,coalesce((select jsonb_agg(jsonb_build_object('feature',pf.feature_code,'enabled',pf.enabled,'limit',pf.limit_value) order by pf.feature_code) from plan_features pf where pf.plan_id=p.id),'[]'::jsonb) features from plans p where p.active=true order by p.price_monthly asc,p.name`);return c.json({data:rows(result)});});

billingLifecycleRoutes.get('/billing/invoices',requirePermission('settings.read'),async c=>{const result=await c.get('db').execute(sql`select si.id,si.amount,si.status,si.due_date,si.paid_at,si.invoice_url,si.pix_copy_paste,si.pix_qr_code_image,si.billing_type,si.created_at from subscription_invoices si join subscriptions s on s.id=si.subscription_id and s.business_id=si.business_id where si.business_id=${c.get('auth').businessId}::uuid order by si.due_date desc,si.created_at desc limit 100`);return c.json({data:rows(result)});});

billingLifecycleRoutes.post('/billing/reactivate',requirePermission('settings.update'),async c=>{const p=z.object({billingType:z.enum(['PIX','BOLETO','UNDEFINED']).default('PIX')}).safeParse(await c.req.json().catch(()=>({})));if(!p.success)return error(c,422,'VALIDATION_ERROR','Reativação inválida');const result=await c.get('db').execute(sql`select s.id,s.status,s.cancel_at_period_end,s.current_period_end,s.provider,s.provider_customer_id,s.provider_subscription_id,p.id plan_id,p.code plan_code,p.name plan_name,p.price_monthly from subscriptions s join plans p on p.id=s.plan_id where s.business_id=${c.get('auth').businessId}::uuid limit 1`);const s:any=rows(result)[0];if(!s)return error(c,404,'SUBSCRIPTION_NOT_FOUND','Assinatura não encontrada');if(s.cancel_at_period_end&&s.status!=='cancelled'){await c.get('db').execute(sql`update subscriptions set cancel_at_period_end=false,cancellation_reason=null,updated_at=now() where id=${s.id}::uuid`);await c.get('db').execute(sql`insert into subscription_events(id,business_id,subscription_id,event_type,payload_json) values(${uuidv7()},${c.get('auth').businessId}::uuid,${s.id}::uuid,'subscription.reactivated_before_period_end','{}'::jsonb)`);return c.json({data:{id:s.id,status:s.status,providerSubscriptionId:s.provider_subscription_id,reused:true}});}if(s.provider!=='asaas'||!s.provider_customer_id)return error(c,409,'CHECKOUT_REQUIRED','É necessário iniciar um novo checkout para reativar esta assinatura',{planCode:s.plan_code});if(!config(c))return error(c,503,'BILLING_NOT_CONFIGURED','Cobrança não configurada neste ambiente');try{const nextDueDate=new Date().toISOString().slice(0,10);const provider=await asaas(c,'/subscriptions',{method:'POST',body:JSON.stringify({customer:s.provider_customer_id,billingType:p.data.billingType,value:Number(s.price_monthly),nextDueDate,cycle:'MONTHLY',description:`Nexoio - ${s.plan_name}`,externalReference:s.id})});if(!provider?.id)throw new Error('Assinatura não criada no provedor');await c.get('db').execute(sql`update subscriptions set status='pending',provider_subscription_id=${provider.id},billing_type=${p.data.billingType},next_due_date=${nextDueDate}::date,cancel_at_period_end=false,cancelled_at=null,cancellation_reason=null,past_due_since=null,updated_at=now() where id=${s.id}::uuid`);await c.get('db').execute(sql`insert into subscription_events(id,business_id,subscription_id,event_type,payload_json) values(${uuidv7()},${c.get('auth').businessId}::uuid,${s.id}::uuid,'subscription.reactivated',${JSON.stringify({providerSubscriptionId:provider.id,billingType:p.data.billingType})}::jsonb)`);return c.json({data:{id:s.id,status:'pending',providerSubscriptionId:provider.id,reused:false}});}catch(reason){return error(c,502,'BILLING_PROVIDER_ERROR',reason instanceof Error?reason.message:'Não foi possível reativar a assinatura');}});
