import { sql } from 'drizzle-orm';
import { Hono } from 'hono';
import { z } from 'zod';
import { uuidv7 } from '@nexoio/core';
import { error, requirePermission } from '../middleware';
import type { ApiEnv } from '../types';

export const domainDetailRoutes=new Hono<ApiEnv>();const rows=(r:any)=>r?.rows??r??[];const id=z.uuid();const money=z.coerce.number().finite().nonnegative();const qty=z.coerce.number().finite().positive();

domainDetailRoutes.get('/professionals',requirePermission('appointments.read'),async c=>{const r=await c.get('db').execute(sql`select * from professionals where business_id=${c.get('auth').businessId}::uuid order by active desc,display_name`);return c.json({data:rows(r)});});
domainDetailRoutes.post('/professionals',requirePermission('appointments.write'),async c=>{const p=z.object({displayName:z.string().trim().min(2).max(180),userId:id.nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Profissional inválido');const recordId=uuidv7();await c.get('db').execute(sql`insert into professionals(id,business_id,user_id,display_name,active) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.userId??null}::uuid,${p.data.displayName},true)`);return c.json({data:{id:recordId,...p.data,active:true}},201);});

domainDetailRoutes.get('/checkins',requirePermission('customers.read'),async c=>{const r=await c.get('db').execute(sql`select ch.*,cu.name customer_name,mp.name plan_name,sc.name class_name from checkins ch join enrollments e on e.id=ch.enrollment_id and e.business_id=ch.business_id join customers cu on cu.id=e.customer_id and cu.business_id=e.business_id join membership_plans mp on mp.id=e.plan_id left join studio_classes sc on sc.id=ch.class_id where ch.business_id=${c.get('auth').businessId}::uuid order by ch.checked_in_at desc limit 300`);return c.json({data:rows(r)});});

domainDetailRoutes.get('/membership-installments',requirePermission('finance.read'),async c=>{const r=await c.get('db').execute(sql`select mi.*,cu.name customer_name,mp.name plan_name from membership_installments mi join enrollments e on e.id=mi.enrollment_id and e.business_id=mi.business_id join customers cu on cu.id=e.customer_id and cu.business_id=e.business_id join membership_plans mp on mp.id=e.plan_id where mi.business_id=${c.get('auth').businessId}::uuid order by mi.due_date desc limit 500`);return c.json({data:rows(r)});});
domainDetailRoutes.post('/membership-installments',requirePermission('finance.create'),async c=>{const p=z.object({enrollmentId:id,dueDate:z.iso.date(),amount:money}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Mensalidade inválida');const installmentId=uuidv7(),receivableId=uuidv7();const r=await c.get('db').execute(sql`with enrollment_ok as (select e.id,cu.id customer_id,cu.name customer_name from enrollments e join customers cu on cu.id=e.customer_id and cu.business_id=e.business_id where e.id=${p.data.enrollmentId}::uuid and e.business_id=${c.get('auth').businessId}::uuid),rec as (insert into receivables(id,business_id,customer_id,description,amount,due_date,status) select ${receivableId},${c.get('auth').businessId}::uuid,customer_id,'Mensalidade - '||customer_name,${p.data.amount},${p.data.dueDate}::date,'pending' from enrollment_ok returning id) insert into membership_installments(id,business_id,enrollment_id,due_date,amount,status,receivable_id) select ${installmentId},${c.get('auth').businessId}::uuid,id,${p.data.dueDate}::date,${p.data.amount},'pending',(select id from rec) from enrollment_ok returning id`);if(!rows(r).length)return error(c,404,'NOT_FOUND','Matrícula não encontrada');return c.json({data:{id:installmentId,receivableId,status:'pending'}},201);});

domainDetailRoutes.get('/clinical-procedures/catalog',requirePermission('patients.read'),async c=>{const r=await c.get('db').execute(sql`select * from clinical_procedure_catalog where business_id=${c.get('auth').businessId}::uuid order by active desc,name`);return c.json({data:rows(r)});});
domainDetailRoutes.post('/clinical-procedures/catalog',requirePermission('patients.write'),async c=>{const p=z.object({name:z.string().trim().min(2).max(180),description:z.string().max(2000).nullish(),durationMinutes:z.coerce.number().int().positive().max(1440).nullish(),price:money.default(0),preparation:z.string().max(3000).nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Procedimento inválido');const recordId=uuidv7();await c.get('db').execute(sql`insert into clinical_procedure_catalog(id,business_id,name,description,duration_minutes,price,preparation) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.name},${p.data.description??null},${p.data.durationMinutes??null},${p.data.price},${p.data.preparation??null})`);return c.json({data:{id:recordId,...p.data}},201);});

domainDetailRoutes.get('/medical-records',requirePermission('patients.sensitive.read'),async c=>{const r=await c.get('db').execute(sql`select cr.id,cr.patient_id,pa.name patient_name,cr.professional_id,p.display_name professional_name,cr.record_type,cr.title,cr.content_json,cr.locked_at,cr.created_at,cr.updated_at from clinical_records cr join patients pa on pa.id=cr.patient_id and pa.business_id=cr.business_id left join professionals p on p.id=cr.professional_id where cr.business_id=${c.get('auth').businessId}::uuid order by cr.created_at desc limit 300`);await c.get('db').execute(sql`insert into audit_logs(id,business_id,actor_user_id,action,entity_type,request_id,after_json) values(${uuidv7()},${c.get('auth').businessId}::uuid,${c.get('auth').userId}::uuid,'clinical_records.list.read','clinical_record',${c.get('requestId')},${JSON.stringify({count:rows(r).length})}::jsonb)`);return c.json({data:rows(r)});});
domainDetailRoutes.post('/medical-records',requirePermission('patients.write'),async c=>{const p=z.object({patientId:id,professionalId:id.nullish(),recordType:z.string().trim().min(1).max(80).default('evolution'),title:z.string().trim().min(1).max(300),notes:z.string().trim().min(1).max(20000)}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Prontuário inválido');const recordId=uuidv7();const r=await c.get('db').execute(sql`insert into clinical_records(id,business_id,patient_id,professional_id,record_type,title,content_json,created_by) select ${recordId},${c.get('auth').businessId}::uuid,pa.id,${p.data.professionalId??null}::uuid,${p.data.recordType},${p.data.title},${JSON.stringify({notes:p.data.notes})}::jsonb,${c.get('auth').userId}::uuid from patients pa where pa.id=${p.data.patientId}::uuid and pa.business_id=${c.get('auth').businessId}::uuid returning id`);if(!rows(r).length)return error(c,404,'NOT_FOUND','Paciente não encontrado');return c.json({data:{id:recordId}},201);});

domainDetailRoutes.get('/service-order-parts',requirePermission('service_orders.read'),async c=>{const r=await c.get('db').execute(sql`select sop.*,so.number service_order_number,p.name product_name from service_order_parts sop join service_orders so on so.id=sop.service_order_id and so.business_id=sop.business_id left join products p on p.id=sop.product_id where sop.business_id=${c.get('auth').businessId}::uuid order by sop.id desc limit 300`);return c.json({data:rows(r)});});
domainDetailRoutes.post('/service-order-parts',requirePermission('service_orders.write'),async c=>{const p=z.object({serviceOrderId:id,productId:id.nullish(),description:z.string().trim().min(1).max(300),quantity:qty,unitCost:money.nullish(),unitPrice:money}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Peça inválida');const recordId=uuidv7(),total=p.data.quantity*p.data.unitPrice;const r=await c.get('db').execute(sql`insert into service_order_parts(id,business_id,service_order_id,product_id,description,quantity,unit_cost,unit_price,total) select ${recordId},${c.get('auth').businessId}::uuid,so.id,${p.data.productId??null}::uuid,${p.data.description},${p.data.quantity},${p.data.unitCost??null},${p.data.unitPrice},${total} from service_orders so where so.id=${p.data.serviceOrderId}::uuid and so.business_id=${c.get('auth').businessId}::uuid returning id`);if(!rows(r).length)return error(c,404,'NOT_FOUND','OS não encontrada');return c.json({data:{id:recordId,total}},201);});
