import { sql } from 'drizzle-orm';
import { Hono } from 'hono';
import { z } from 'zod';
import { uuidv7 } from '@nexoio/core';
import { error, requirePermission } from '../middleware';
import type { ApiEnv } from '../types';

export const financeCashRoutes=new Hono<ApiEnv>();
const rows=(result:any)=>result?.rows??result??[];
const id=z.uuid();
const positive=z.coerce.number().finite().positive();

financeCashRoutes.get('/finance/accounts',requirePermission('finance.read'),async c=>{
  const result=await c.get('db').execute(sql`
    select id,'payable' kind,description,amount,paid_amount settled_amount,due_date,status,category_id,payment_method_id,notes,created_at from payables where business_id=${c.get('auth').businessId}::uuid
    union all
    select id,'receivable' kind,description,amount,received_amount settled_amount,due_date,status,category_id,payment_method_id,notes,created_at from receivables where business_id=${c.get('auth').businessId}::uuid
    order by due_date asc,created_at desc limit 500
  `);return c.json({data:rows(result)});
});

financeCashRoutes.get('/finance/categories',requirePermission('finance.read'),async c=>{const result=await c.get('db').execute(sql`select * from financial_categories where business_id=${c.get('auth').businessId}::uuid and active=true order by kind,name`);return c.json({data:rows(result)});});
financeCashRoutes.post('/finance/categories',requirePermission('finance.create'),async c=>{const p=z.object({name:z.string().trim().min(1).max(120),kind:z.enum(['income','expense','both'])}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Categoria inválida');const categoryId=uuidv7();await c.get('db').execute(sql`insert into financial_categories(id,business_id,name,kind) values(${categoryId},${c.get('auth').businessId}::uuid,${p.data.name},${p.data.kind})`);return c.json({data:{id:categoryId,...p.data}},201);});
financeCashRoutes.get('/payment-methods',requirePermission('finance.read'),async c=>{const result=await c.get('db').execute(sql`select * from payment_methods where business_id=${c.get('auth').businessId}::uuid and active=true order by name`);return c.json({data:rows(result)});});
financeCashRoutes.post('/payment-methods',requirePermission('settings.update'),async c=>{const p=z.object({code:z.string().trim().min(1).max(40),name:z.string().trim().min(1).max(100),type:z.string().trim().min(1).max(50),feePercent:z.coerce.number().min(0).max(100).default(0),settlementDays:z.coerce.number().int().min(0).max(365).default(0)}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Forma de pagamento inválida');const methodId=uuidv7();await c.get('db').execute(sql`insert into payment_methods(id,business_id,code,name,type,fee_percent,settlement_days) values(${methodId},${c.get('auth').businessId}::uuid,${p.data.code},${p.data.name},${p.data.type},${p.data.feePercent},${p.data.settlementDays})`);return c.json({data:{id:methodId,...p.data}},201);});

financeCashRoutes.post('/finance/payables/:id/settle',requirePermission('finance.create'),async c=>{const accountId=id.safeParse(c.req.param('id'));const p=z.object({amount:positive,paymentMethodId:id.nullish()}).safeParse(await c.req.json().catch(()=>null));if(!accountId.success||!p.success)return error(c,422,'VALIDATION_ERROR','Liquidação inválida');const before=await c.get('db').execute(sql`select amount,paid_amount,status from payables where id=${accountId.data}::uuid and business_id=${c.get('auth').businessId}::uuid limit 1`);const row:any=rows(before)[0];if(!row)return error(c,404,'NOT_FOUND','Conta não encontrada');const remaining=Math.max(0,Number(row.amount)-Number(row.paid_amount));if(p.data.amount>remaining+0.001)return error(c,409,'AMOUNT_EXCEEDS_BALANCE','Valor supera o saldo em aberto',{remaining});const next=Number(row.paid_amount)+p.data.amount;const status=next>=Number(row.amount)?'paid':'partial';await c.get('db').execute(sql`update payables set paid_amount=${next},payment_method_id=coalesce(${p.data.paymentMethodId??null}::uuid,payment_method_id),status=${status},paid_at=case when ${status}='paid' then now() else paid_at end where id=${accountId.data}::uuid and business_id=${c.get('auth').businessId}::uuid`);await c.get('db').execute(sql`insert into audit_logs(id,business_id,actor_user_id,action,entity_type,entity_id,request_id,before_json,after_json) values(${uuidv7()},${c.get('auth').businessId}::uuid,${c.get('auth').userId}::uuid,'finance.payable.settled','payable',${accountId.data}::uuid,${c.get('requestId')},${JSON.stringify(row)}::jsonb,${JSON.stringify({paidAmount:next,status})}::jsonb)`);return c.json({data:{id:accountId.data,paidAmount:next,status}});});

financeCashRoutes.post('/finance/receivables/:id/settle',requirePermission('finance.create'),async c=>{const accountId=id.safeParse(c.req.param('id'));const p=z.object({amount:positive,paymentMethodId:id.nullish()}).safeParse(await c.req.json().catch(()=>null));if(!accountId.success||!p.success)return error(c,422,'VALIDATION_ERROR','Recebimento inválido');const before=await c.get('db').execute(sql`select amount,received_amount,status from receivables where id=${accountId.data}::uuid and business_id=${c.get('auth').businessId}::uuid limit 1`);const row:any=rows(before)[0];if(!row)return error(c,404,'NOT_FOUND','Conta não encontrada');const remaining=Math.max(0,Number(row.amount)-Number(row.received_amount));if(p.data.amount>remaining+0.001)return error(c,409,'AMOUNT_EXCEEDS_BALANCE','Valor supera o saldo em aberto',{remaining});const next=Number(row.received_amount)+p.data.amount;const status=next>=Number(row.amount)?'received':'partial';await c.get('db').execute(sql`update receivables set received_amount=${next},payment_method_id=coalesce(${p.data.paymentMethodId??null}::uuid,payment_method_id),status=${status},received_at=case when ${status}='received' then now() else received_at end where id=${accountId.data}::uuid and business_id=${c.get('auth').businessId}::uuid`);await c.get('db').execute(sql`insert into audit_logs(id,business_id,actor_user_id,action,entity_type,entity_id,request_id,before_json,after_json) values(${uuidv7()},${c.get('auth').businessId}::uuid,${c.get('auth').userId}::uuid,'finance.receivable.settled','receivable',${accountId.data}::uuid,${c.get('requestId')},${JSON.stringify(row)}::jsonb,${JSON.stringify({receivedAmount:next,status})}::jsonb)`);return c.json({data:{id:accountId.data,receivedAmount:next,status}});});

financeCashRoutes.get('/cash/current',requirePermission('cash.read'),async c=>{const sessions=await c.get('db').execute(sql`select cs.*,u.name opened_by_name from cash_sessions cs join users u on u.id=cs.opened_by where cs.business_id=${c.get('auth').businessId}::uuid and cs.opened_by=${c.get('auth').userId}::uuid and cs.status='open' order by cs.opened_at desc limit 1`);const session:any=rows(sessions)[0];if(!session)return c.json({data:null});const movements=await c.get('db').execute(sql`select id,movement_type,amount,reference_type,reference_id,description,created_at from cash_movements where business_id=${c.get('auth').businessId}::uuid and cash_session_id=${session.id}::uuid order by created_at desc`);return c.json({data:{...session,movements:rows(movements)}});});
