import { and, eq, inArray } from 'drizzle-orm';
import { deleteCookie, getCookie, setCookie } from 'hono/cookie';
import { Hono } from 'hono';
import { z } from 'zod';
import { BUSINESS_TYPES, isAllowedSlug, MODULE_DEPENDENCIES, MODULES, SEGMENT_MODULES, uuidv7 } from '@nexoio/core';
import { PERMISSIONS } from '@nexoio/permissions';
import { businessMemberships, businessModules, businesses, memberInvitations, modules, onboardingProgress, rolePermissions, roles, users } from '@nexoio/db';
import { error, requireAuth, requirePermission, requireSession } from '../middleware';
import type { ApiEnv } from '../types';

const onboardingSchema = z.object({ displayName:z.string().trim().min(2).max(150),legalName:z.string().trim().max(180).optional(),segment:z.enum(BUSINESS_TYPES),documentNumber:z.string().max(30).optional(),phone:z.string().max(30).optional(),email:z.email().optional(),city:z.string().max(100),state:z.string().length(2),timezone:z.string().default('America/Sao_Paulo'),slug:z.string().min(2).max(63),moduleKeys:z.array(z.enum(MODULES)).optional() }).strict();
const moduleSchema = z.object({ moduleKey:z.enum(MODULES),enabled:z.boolean() }).strict();
const inviteSchema = z.object({ email:z.email(),roleId:z.uuid() }).strict();
const digest = async (value:string) => [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');

export const platformRoutes = new Hono<ApiEnv>();
platformRoutes.use('*',requireSession);
platformRoutes.get('/context',async c=>{
  const db=c.get('db'); const profile=(await db.select().from(users).where(eq(users.authUserId,c.get('sessionUser').id)).limit(1))[0]; if(!profile)return error(c,409,'PROFILE_NOT_READY','Perfil ainda não foi provisionado');
  const memberships=await db.select({businessId:businessMemberships.businessId,businessName:businesses.displayName,segment:businesses.businessType,status:businessMemberships.status,roleId:businessMemberships.roleId,roleCode:roles.code}).from(businessMemberships).innerJoin(businesses,eq(businesses.id,businessMemberships.businessId)).innerJoin(roles,eq(roles.id,businessMemberships.roleId)).where(and(eq(businessMemberships.userId,profile.id),eq(businessMemberships.status,'active')));
  const activeBusinessId=getCookie(c,'nexoio_business'); const membership=memberships.find(x=>x.businessId===activeBusinessId); let grants:string[]=[];let activeModules:string[]=[];
  if(membership){const [permissionRows,moduleRows]=await Promise.all([db.select({code:rolePermissions.permissionCode}).from(rolePermissions).where(eq(rolePermissions.roleId,membership.roleId)),db.select({key:businessModules.moduleCode}).from(businessModules).where(and(eq(businessModules.businessId,membership.businessId),eq(businessModules.enabled,true)))]);grants=permissionRows.map(x=>x.code);activeModules=moduleRows.map(x=>x.key)}
  return c.json({data:{user:profile,memberships,activeBusiness:membership??null,permissions:grants,modules:activeModules,onboardingRequired:memberships.length===0}});
});
platformRoutes.post('/businesses/select',async c=>{const parsed=z.object({businessId:z.uuid()}).safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,422,'VALIDATION_ERROR','Empresa inválida');const profile=(await c.get('db').select({id:users.id}).from(users).where(eq(users.authUserId,c.get('sessionUser').id)).limit(1))[0];if(!profile)return error(c,404,'BUSINESS_NOT_FOUND','Empresa não encontrada');const membership=(await c.get('db').select({id:businessMemberships.id}).from(businessMemberships).where(and(eq(businessMemberships.userId,profile.id),eq(businessMemberships.businessId,parsed.data.businessId),eq(businessMemberships.status,'active'))).limit(1))[0];if(!membership)return error(c,404,'BUSINESS_NOT_FOUND','Empresa não encontrada');setCookie(c,'nexoio_business',parsed.data.businessId,{httpOnly:true,secure:c.env.AUTH_URL.startsWith('https'),sameSite:'Lax',path:'/',maxAge:60*60*24*30});return c.json({data:{selected:true}})});
platformRoutes.post('/businesses/clear',c=>{deleteCookie(c,'nexoio_business',{path:'/'});return c.json({data:{selected:false}})});
platformRoutes.post('/onboarding/business',async c=>{const parsed=onboardingSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,422,'VALIDATION_ERROR','Dados inválidos',parsed.error.flatten());if(!isAllowedSlug(parsed.data.slug))return error(c,422,'VALIDATION_ERROR','Slug inválido ou reservado');const db=c.get('db');const profile=(await db.select().from(users).where(eq(users.authUserId,c.get('sessionUser').id)).limit(1))[0];if(!profile)return error(c,409,'PROFILE_NOT_READY','Perfil ainda não foi provisionado');const businessId=uuidv7();const roleId=uuidv7();const moduleKeys=[...new Set(parsed.data.moduleKeys??SEGMENT_MODULES[parsed.data.segment])];for(const key of moduleKeys){for(const dependency of MODULE_DEPENDENCIES[key]??[])if(!moduleKeys.includes(dependency))return error(c,422,'MODULE_DEPENDENCY_REQUIRED',`${key} depende de ${dependency}`)}await db.insert(businesses).values({id:businessId,displayName:parsed.data.displayName,legalName:parsed.data.legalName,publicSlug:parsed.data.slug,businessType:parsed.data.segment,documentNumber:parsed.data.documentNumber,phone:parsed.data.phone,email:parsed.data.email,timezone:parsed.data.timezone});await db.insert(roles).values({id:roleId,businessId,code:'owner',name:'Proprietário',isSystem:true});await db.insert(rolePermissions).values(PERMISSIONS.map(permissionCode=>({roleId,permissionCode})));await db.insert(businessMemberships).values({id:uuidv7(),businessId,userId:profile.id,roleId,status:'active',acceptedAt:new Date()});await db.insert(businessModules).values(moduleKeys.map(moduleCode=>({id:uuidv7(),businessId,moduleCode,enabled:true,source:'segment_default'})));await db.insert(onboardingProgress).values({userId:profile.id,businessId,step:'finish',completedAt:new Date(),dataJson:parsed.data}).onConflictDoUpdate({target:onboardingProgress.userId,set:{businessId,step:'finish',completedAt:new Date(),dataJson:parsed.data,updatedAt:new Date()}});setCookie(c,'nexoio_business',businessId,{httpOnly:true,secure:c.env.AUTH_URL.startsWith('https'),sameSite:'Lax',path:'/'});return c.json({data:{businessId}},201)});

platformRoutes.use('/business/*',requireAuth);
platformRoutes.get('/business/modules',requirePermission('modules.read'),async c=>c.json({data:await c.get('db').select({key:modules.key,name:modules.name,description:modules.description,dependencies:modules.dependenciesJson,enabled:businessModules.enabled,source:businessModules.source}).from(modules).leftJoin(businessModules,and(eq(businessModules.moduleCode,modules.key),eq(businessModules.businessId,c.get('auth').businessId))).where(eq(modules.active,true))}));
platformRoutes.patch('/business/modules',requirePermission('modules.update'),async c=>{const parsed=moduleSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,422,'VALIDATION_ERROR','Módulo inválido');const db=c.get('db');if(parsed.data.enabled){const required=MODULE_DEPENDENCIES[parsed.data.moduleKey]??[];if(required.length){const enabled=await db.select({key:businessModules.moduleCode}).from(businessModules).where(and(eq(businessModules.businessId,c.get('auth').businessId),eq(businessModules.enabled,true),inArray(businessModules.moduleCode,required)));if(enabled.length!==required.length)return error(c,422,'MODULE_DEPENDENCY_REQUIRED',`Ative primeiro: ${required.join(', ')}`)}}else{const dependents=Object.entries(MODULE_DEPENDENCIES).filter(([,deps])=>deps?.includes(parsed.data.moduleKey)).map(([key])=>key);if(dependents.length){const active=await db.select({key:businessModules.moduleCode}).from(businessModules).where(and(eq(businessModules.businessId,c.get('auth').businessId),eq(businessModules.enabled,true),inArray(businessModules.moduleCode,dependents)));if(active.length)return error(c,422,'MODULE_HAS_DEPENDENTS',`Desative primeiro: ${active.map(x=>x.key).join(', ')}`)}}await db.insert(businessModules).values({id:uuidv7(),businessId:c.get('auth').businessId,moduleCode:parsed.data.moduleKey,enabled:parsed.data.enabled,source:'manual'}).onConflictDoUpdate({target:[businessModules.businessId,businessModules.moduleCode],set:{enabled:parsed.data.enabled,source:'manual',updatedAt:new Date()}});return c.json({data:parsed.data})});
platformRoutes.post('/business/invitations',requirePermission('team.invite'),async c=>{const parsed=inviteSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,422,'VALIDATION_ERROR','Convite inválido',parsed.error.flatten());const token=crypto.randomUUID()+crypto.randomUUID();const id=uuidv7();await c.get('db').insert(memberInvitations).values({id,businessId:c.get('auth').businessId,email:parsed.data.email.toLowerCase(),roleId:parsed.data.roleId,tokenHash:await digest(token),invitedBy:c.get('auth').userId,expiresAt:new Date(Date.now()+7*86400000)});return c.json({data:{id,acceptUrl:`${c.env.APP_URL}/aceitar-convite?token=${encodeURIComponent(token)}`}},201)});
platformRoutes.post('/invitations/accept',async c=>{const parsed=z.object({token:z.string().min(40)}).safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,422,'VALIDATION_ERROR','Token inválido');const db=c.get('db');const invitation=(await db.select().from(memberInvitations).where(and(eq(memberInvitations.tokenHash,await digest(parsed.data.token)),eq(memberInvitations.status,'pending'))).limit(1))[0];if(!invitation||invitation.expiresAt<new Date())return error(c,410,'INVITATION_EXPIRED','Convite inválido ou expirado');if(invitation.email!==c.get('sessionUser').email.toLowerCase())return error(c,403,'FORBIDDEN','Este convite pertence a outro e-mail');const profile=(await db.select().from(users).where(eq(users.authUserId,c.get('sessionUser').id)).limit(1))[0];if(!profile)return error(c,409,'PROFILE_NOT_READY','Perfil indisponível');await db.insert(businessMemberships).values({id:uuidv7(),businessId:invitation.businessId,userId:profile.id,roleId:invitation.roleId,status:'active',invitedAt:invitation.createdAt,acceptedAt:new Date()}).onConflictDoUpdate({target:[businessMemberships.businessId,businessMemberships.userId],set:{status:'active',roleId:invitation.roleId,acceptedAt:new Date(),updatedAt:new Date()}});await db.update(memberInvitations).set({status:'accepted',acceptedAt:new Date()}).where(eq(memberInvitations.id,invitation.id));return c.json({data:{businessId:invitation.businessId}})});
