import { sql } from 'drizzle-orm';
import { Hono } from 'hono';
import { z } from 'zod';
import { error, requirePermission } from '../middleware';
import type { ApiEnv } from '../types';

export const salesRoutes=new Hono<ApiEnv>();
const rows=(r:any)=>r?.rows??r??[];
const id=z.uuid();
const itemSchema=z.object({itemType:z.enum(['product','service','other']),productId:id.nullish(),serviceId:id.nullish(),professionalId:id.nullish(),description:z.string().trim().min(1).max(300),quantity:z.coerce.number().positive(),unitPrice:z.coerce.number().nonnegative(),discount:z.coerce.number().nonnegative().default(0)}).strict();
const paymentSchema=z.object({method:z.string().trim().min(1).max(50),amount:z.coerce.number().positive(),provider:z.string().trim().max(80).nullish(),externalReference:z.string().trim().max(180).nullish()}).strict();
const saleSchema=z.object({customerId:id.nullish(),unitId:id.nullish(),notes:z.string().max(2000).nullish(),items:z.array(itemSchema).min(1).max(200),payments:z.array(paymentSchema).min(1).max(20)}).strict();
const legacySchema=z.object({customerId:id.nullish(),description:z.string().trim().min(1).max(500),total:z.coerce.number().positive(),method:z.string().trim().min(1).max(50),notes:z.string().max(2000).nullish()}).strict();
const errorMessage=(reason:unknown)=>{let current:any=reason;const seen=new Set<unknown>();const parts:string[]=[];for(let i=0;i<6&&current&&!seen.has(current);i++){seen.add(current);if(typeof current?.message==='string')parts.push(current.message);current=current?.cause}return parts.join(' | ')||String(reason)};

salesRoutes.get('/sales',requirePermission('sales.read'),async c=>{const result=await c.get('db').execute(sql`select s.*,cu.name customer_name,coalesce((select jsonb_agg(jsonb_build_object('id',si.id,'itemType',si.item_type,'productId',si.product_id,'serviceId',si.service_id,'professionalId',si.professional_id,'description',si.description,'quantity',si.quantity,'unitPrice',si.unit_price,'discount',si.discount,'total',si.total)) from sale_items si where si.sale_id=s.id and si.business_id=s.business_id),'[]'::jsonb) items,coalesce((select jsonb_agg(jsonb_build_object('method',sp.method,'amount',sp.amount,'status',sp.status)) from sale_payments sp where sp.sale_id=s.id and sp.business_id=s.business_id),'[]'::jsonb) payments,coalesce((select jsonb_agg(jsonb_build_object('amount',pr.amount,'status',pr.status,'reason',pr.reason)) from payment_refunds pr join sale_payments sp on sp.id=pr.sale_payment_id where sp.sale_id=s.id and pr.business_id=s.business_id),'[]'::jsonb) refunds from sales s left join customers cu on cu.id=s.customer_id and cu.business_id=s.business_id where s.business_id=${c.get('auth').businessId}::uuid order by s.created_at desc limit 300`);return c.json({data:rows(result)});});

salesRoutes.post('/sales',requirePermission('sales.create'),async c=>{
  const raw=await c.req.json().catch(()=>null);const modern=saleSchema.safeParse(raw);const legacy=modern.success?null:legacySchema.safeParse(raw);
  if(!modern.success&&(!legacy||!legacy.success))return error(c,422,'VALIDATION_ERROR','Venda inválida',modern.error.flatten());
  const data=modern.success?modern.data:{customerId:legacy!.data.customerId,notes:legacy!.data.notes,unitId:null,items:[{itemType:'other' as const,productId:null,serviceId:null,professionalId:null,description:legacy!.data.description,quantity:1,unitPrice:legacy!.data.total,discount:0}],payments:[{method:legacy!.data.method,amount:legacy!.data.total,provider:null,externalReference:null}]};
  const subtotal=data.items.reduce((sum,item)=>sum+item.quantity*item.unitPrice,0),discount=data.items.reduce((sum,item)=>sum+item.discount,0);const max=c.get('auth').policyLimits.get('sales.max_discount_percent');if(typeof max==='number'&&subtotal>0&&(discount/subtotal)*100>max)return error(c,403,'POLICY_LIMIT_EXCEEDED','Desconto acima do limite permitido para seu perfil',{limitPercent:max});
  try{const result=await c.get('db').execute(sql`select * from create_sale_transactional(${c.get('auth').businessId}::uuid,${c.get('auth').userId}::uuid,${data.unitId??null}::uuid,${data.customerId??null}::uuid,${data.notes??null},${JSON.stringify(data.items)}::jsonb,${JSON.stringify(data.payments)}::jsonb)`);const row:any=rows(result)[0];if(!row)return error(c,500,'SALE_CREATE_FAILED','Venda não retornou resultado');return c.json({data:{id:row.sale_id,status:'completed',subtotal:row.subtotal,discount:row.discount,total:row.total}},201)}catch(reason){const message=errorMessage(reason);if(message.includes('CUSTOMER_NOT_FOUND'))return error(c,404,'CUSTOMER_NOT_FOUND','Cliente não encontrado');if(message.includes('PRODUCT_NOT_FOUND'))return error(c,404,'PRODUCT_NOT_FOUND','Produto não encontrado ou inativo');if(message.includes('SERVICE_NOT_FOUND'))return error(c,404,'SERVICE_NOT_FOUND','Serviço não encontrado ou inativo');if(message.includes('PROFESSIONAL_NOT_FOUND'))return error(c,404,'PROFESSIONAL_NOT_FOUND','Profissional não encontrado ou inativo');if(message.includes('INVENTORY_LOCATION_REQUIRED'))return error(c,409,'INVENTORY_LOCATION_REQUIRED','Configure um local de estoque antes de vender este produto');if(message.includes('INSUFFICIENT_STOCK'))return error(c,409,'INSUFFICIENT_STOCK','Estoque insuficiente para concluir a venda');if(message.includes('OPEN_CASH_REQUIRED'))return error(c,409,'OPEN_CASH_REQUIRED','Abra o caixa antes de receber uma venda em dinheiro');if(message.includes('PAYMENT_TOTAL_MISMATCH'))return error(c,409,'PAYMENT_TOTAL_MISMATCH','A soma dos pagamentos deve ser igual ao total da venda');if(message.includes('INVALID_PAYMENT'))return error(c,422,'INVALID_PAYMENT','Forma ou valor de pagamento inválido');throw reason;}
});

async function refund(c:any,saleId:string,reason:string){try{const result=await c.get('db').execute(sql`select * from refund_sale_transactional(${c.get('auth').businessId}::uuid,${saleId}::uuid,${c.get('auth').userId}::uuid,${reason})`);const row:any=rows(result)[0];return c.json({data:{id:saleId,status:Number(row?.pending_provider_refunds??0)>0?'refund_pending':'refunded',refundedAmount:row?.refunded_amount??0,pendingProviderRefunds:Number(row?.pending_provider_refunds??0)}})}catch(value){const message=errorMessage(value);if(message.includes('SALE_NOT_FOUND'))return error(c,404,'NOT_FOUND','Venda não encontrada');if(message.includes('SALE_ALREADY_REFUNDED'))return error(c,409,'SALE_ALREADY_REFUNDED','Venda já estornada');if(message.includes('OPEN_CASH_REQUIRED_FOR_CASH_REFUND'))return error(c,409,'OPEN_CASH_REQUIRED','Abra um caixa antes de fazer estorno em dinheiro');throw value;}}
salesRoutes.post('/sales/:id/refund',requirePermission('sales.cancel'),async c=>{const saleId=id.safeParse(c.req.param('id'));const p=z.object({reason:z.string().trim().min(3).max(1000)}).safeParse(await c.req.json().catch(()=>null));if(!saleId.success||!p.success)return error(c,422,'VALIDATION_ERROR','Estorno inválido');return refund(c,saleId.data,p.data.reason);});
salesRoutes.post('/sales/:id/cancel',requirePermission('sales.cancel'),async c=>{const saleId=id.safeParse(c.req.param('id'));const p=z.object({reason:z.string().trim().min(3).max(1000)}).safeParse(await c.req.json().catch(()=>null));if(!saleId.success||!p.success)return error(c,422,'VALIDATION_ERROR','Cancelamento inválido');return refund(c,saleId.data,p.data.reason);});
