import { sql } from 'drizzle-orm';
import { Hono } from 'hono';
import { z } from 'zod';
import { uuidv7 } from '@nexoio/core';
import { error, requirePermission } from '../middleware';
import type { ApiEnv } from '../types';

export const siteGrowthRoutes=new Hono<ApiEnv>();
const rows=(r:any)=>r?.rows??r??[];const uuid=z.uuid();
const integrationsSchema=z.object({googleAnalyticsId:z.union([z.string().trim().regex(/^G-[A-Z0-9]+$/i),z.literal('')]).default(''),metaPixelId:z.union([z.string().trim().regex(/^\d{5,30}$/),z.literal('')]).default(''),googleMapsUrl:z.union([z.url(),z.literal('')]).default(''),whatsappUrl:z.union([z.url(),z.literal('')]).default(''),instagramUrl:z.union([z.url(),z.literal('')]).default(''),leadNotificationsEnabled:z.boolean().default(true),bookingAutoConfirm:z.boolean().default(false)}).strict();

async function audit(c:any,action:string,entityType:string,entityId:string|null,beforeJson:unknown,afterJson:unknown){await c.get('db').execute(sql`insert into audit_logs(id,business_id,actor_user_id,action,entity_type,entity_id,request_id,user_agent,before_json,after_json) values(${uuidv7()},${c.get('auth').businessId}::uuid,${c.get('auth').userId}::uuid,${action},${entityType},${entityId}::uuid,${c.get('requestId')},${c.req.header('user-agent')?.slice(0,500)??null},${JSON.stringify(beforeJson??null)}::jsonb,${JSON.stringify(afterJson??null)}::jsonb)`);}

siteGrowthRoutes.get('/site/integrations',requirePermission('public_site.read'),async c=>{const r=await c.get('db').execute(sql`select google_analytics_id,meta_pixel_id,google_maps_url,whatsapp_url,instagram_url,lead_notifications_enabled,booking_auto_confirm,updated_at from public_site_integrations where business_id=${c.get('auth').businessId}::uuid limit 1`);const x:any=rows(r)[0]??{};return c.json({data:{googleAnalyticsId:x.google_analytics_id??'',metaPixelId:x.meta_pixel_id??'',googleMapsUrl:x.google_maps_url??'',whatsappUrl:x.whatsapp_url??'',instagramUrl:x.instagram_url??'',leadNotificationsEnabled:x.lead_notifications_enabled??true,bookingAutoConfirm:x.booking_auto_confirm??false,updatedAt:x.updated_at??null}});});
siteGrowthRoutes.put('/site/integrations',requirePermission('public_site.update'),async c=>{const p=integrationsSchema.safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Integrações inválidas',p.error.flatten());const before=await c.get('db').execute(sql`select * from public_site_integrations where business_id=${c.get('auth').businessId}::uuid limit 1`);await c.get('db').execute(sql`insert into public_site_integrations(business_id,google_analytics_id,meta_pixel_id,google_maps_url,whatsapp_url,instagram_url,lead_notifications_enabled,booking_auto_confirm,updated_at) values(${c.get('auth').businessId}::uuid,${p.data.googleAnalyticsId||null},${p.data.metaPixelId||null},${p.data.googleMapsUrl||null},${p.data.whatsappUrl||null},${p.data.instagramUrl||null},${p.data.leadNotificationsEnabled},${p.data.bookingAutoConfirm},now()) on conflict(business_id) do update set google_analytics_id=excluded.google_analytics_id,meta_pixel_id=excluded.meta_pixel_id,google_maps_url=excluded.google_maps_url,whatsapp_url=excluded.whatsapp_url,instagram_url=excluded.instagram_url,lead_notifications_enabled=excluded.lead_notifications_enabled,booking_auto_confirm=excluded.booking_auto_confirm,updated_at=now()`);await audit(c,'public_site.integrations.updated','public_site',c.get('auth').businessId,rows(before)[0]??null,p.data);return c.json({data:p.data});});

siteGrowthRoutes.get('/site/leads',requirePermission('public_site.read'),async c=>{const status=c.req.query('status');const r=await c.get('db').execute(sql`select id,source,name,email,phone,message,status,metadata_json,created_at,updated_at from public_site_leads where business_id=${c.get('auth').businessId}::uuid and (${status??null}::text is null or status=${status??null}) order by created_at desc limit 300`);return c.json({data:rows(r)});});
siteGrowthRoutes.patch('/site/leads/:id',requirePermission('public_site.update'),async c=>{const leadId=uuid.safeParse(c.req.param('id'));const p=z.object({status:z.enum(['new','contacted','qualified','won','lost','archived'])}).strict().safeParse(await c.req.json().catch(()=>null));if(!leadId.success||!p.success)return error(c,422,'VALIDATION_ERROR','Lead inválido');const before=await c.get('db').execute(sql`select status from public_site_leads where id=${leadId.data}::uuid and business_id=${c.get('auth').businessId}::uuid limit 1`);if(!rows(before).length)return error(c,404,'NOT_FOUND','Lead não encontrado');const r=await c.get('db').execute(sql`update public_site_leads set status=${p.data.status},updated_at=now() where id=${leadId.data}::uuid and business_id=${c.get('auth').businessId}::uuid returning *`);await audit(c,'public_site.lead.status_changed','public_site_lead',leadId.data,rows(before)[0],{status:p.data.status});return c.json({data:rows(r)[0]});});

siteGrowthRoutes.get('/site/bookings',requirePermission('appointments.read'),async c=>{const r=await c.get('db').execute(sql`select br.*,cu.name customer_name,cu.phone customer_phone,s.name service_name,p.display_name professional_name from public_booking_requests br left join customers cu on cu.id=br.customer_id and cu.business_id=br.business_id left join services s on s.id=br.service_id and s.business_id=br.business_id left join professionals p on p.id=br.professional_id and p.business_id=br.business_id where br.business_id=${c.get('auth').businessId}::uuid order by br.requested_start desc limit 300`);return c.json({data:rows(r)});});
siteGrowthRoutes.post('/site/bookings/:id/decision',requirePermission('appointments.write'),async c=>{const requestId=uuid.safeParse(c.req.param('id'));const p=z.object({decision:z.enum(['confirm','reject']),startsAt:z.iso.datetime().optional(),professionalId:uuid.nullish(),reason:z.string().max(1000).optional()}).strict().safeParse(await c.req.json().catch(()=>null));if(!requestId.success||!p.success)return error(c,422,'VALIDATION_ERROR','Solicitação inválida');const db=c.get('db'),b=c.get('auth').businessId;const found=await db.execute(sql`select * from public_booking_requests where id=${requestId.data}::uuid and business_id=${b}::uuid and status='pending' limit 1`);const booking:any=rows(found)[0];if(!booking)return error(c,404,'NOT_FOUND','Solicitação pendente não encontrada');if(p.data.decision==='reject'){await db.execute(sql`update public_booking_requests set status='rejected',notes=concat_ws(E'\n',notes,${p.data.reason??'Recusado pelo estabelecimento'}),updated_at=now() where id=${requestId.data}::uuid and business_id=${b}::uuid`);await audit(c,'public_site.booking.rejected','booking_request',requestId.data,{status:booking.status},{status:'rejected',reason:p.data.reason??null});return c.json({data:{id:requestId.data,status:'rejected'}});}const startsAt=new Date(p.data.startsAt??booking.requested_start),professionalId=p.data.professionalId??booking.professional_id;const service=await db.execute(sql`select duration_minutes from services where id=${booking.service_id}::uuid and business_id=${b}::uuid limit 1`);const duration=Math.max(5,Number((rows(service)[0] as any)?.duration_minutes??60)),endsAt=new Date(startsAt.getTime()+duration*60000);if(professionalId){const conflict=await db.execute(sql`select 1 from appointments where business_id=${b}::uuid and professional_id=${professionalId}::uuid and status not in ('cancelled','no_show') and starts_at<${endsAt} and ends_at>${startsAt} limit 1`);if(rows(conflict).length)return error(c,409,'TIME_UNAVAILABLE','Horário indisponível');}const appointmentId=uuidv7();await db.execute(sql`insert into appointments(id,business_id,customer_id,professional_id,service_id,starts_at,ends_at,status,notes,created_by) values(${appointmentId},${b}::uuid,${booking.customer_id}::uuid,${professionalId}::uuid,${booking.service_id}::uuid,${startsAt},${endsAt},'confirmed',${booking.notes??'Solicitado pelo site'},${c.get('auth').userId}::uuid)`);await db.execute(sql`update public_booking_requests set status='confirmed',appointment_id=${appointmentId}::uuid,professional_id=${professionalId}::uuid,requested_start=${startsAt},requested_end=${endsAt},updated_at=now() where id=${requestId.data}::uuid and business_id=${b}::uuid`);await audit(c,'public_site.booking.confirmed','booking_request',requestId.data,{status:booking.status},{status:'confirmed',appointmentId,startsAt:startsAt.toISOString()});return c.json({data:{id:requestId.data,status:'confirmed',appointmentId}});});

siteGrowthRoutes.get('/site/analytics/summary',requirePermission('public_site.read'),async c=>{const days=Math.min(90,Math.max(1,Number(c.req.query('days')??30)));const r=await c.get('db').execute(sql`select count(*) filter(where event_name='page_view')::int page_views,count(distinct visitor_hash) filter(where event_name='page_view')::int visitors,count(*) filter(where event_name='lead_submit')::int lead_submits,count(*) filter(where event_name='booking_submit')::int booking_submits from public_site_events where business_id=${c.get('auth').businessId}::uuid and created_at>=now()-(${days}::text||' days')::interval`);return c.json({data:{...(rows(r)[0]??{}),days}});});
