import { sql } from 'drizzle-orm';
import { Hono } from 'hono';
import { z } from 'zod';
import { uuidv7 } from '@nexoio/core';
import { error, requirePermission } from '../middleware';
import type { ApiEnv } from '../types';

export const specializedResourceRoutes=new Hono<ApiEnv>();
const rows=(r:any)=>r?.rows??r??[];const id=z.uuid();const money=z.coerce.number().finite().nonnegative();const qty=z.coerce.number().finite().positive();

specializedResourceRoutes.get('/tables',requirePermission('orders.read'),async c=>{const r=await c.get('db').execute(sql`select * from restaurant_tables where business_id=${c.get('auth').businessId}::uuid order by number`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/tables',requirePermission('orders.write'),async c=>{const p=z.object({number:z.string().trim().min(1).max(40),seats:z.coerce.number().int().min(1).max(100).optional(),unitId:id.nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Mesa inválida');const recordId=uuidv7();await c.get('db').execute(sql`insert into restaurant_tables(id,business_id,unit_id,number,seats,status) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.unitId??null}::uuid,${p.data.number},${p.data.seats??null},'available')`);return c.json({data:{id:recordId,...p.data,status:'available'}},201);});
specializedResourceRoutes.patch('/tables/:id/status',requirePermission('orders.write'),async c=>{const record=id.safeParse(c.req.param('id'));const p=z.object({status:z.enum(['available','occupied','reserved','unavailable'])}).safeParse(await c.req.json().catch(()=>null));if(!record.success||!p.success)return error(c,422,'VALIDATION_ERROR','Mesa inválida');const r=await c.get('db').execute(sql`update restaurant_tables set status=${p.data.status} where id=${record.data}::uuid and business_id=${c.get('auth').businessId}::uuid returning *`);if(!rows(r).length)return error(c,404,'NOT_FOUND','Mesa não encontrada');return c.json({data:rows(r)[0]});});

specializedResourceRoutes.get('/commands',requirePermission('orders.read'),async c=>{const r=await c.get('db').execute(sql`select t.*,rt.number table_number,cu.name customer_name,coalesce((select sum(o.total) from orders o where o.tab_id=t.id and o.business_id=t.business_id and o.status<>'cancelled'),0) total from order_tabs t left join restaurant_tables rt on rt.id=t.table_id left join customers cu on cu.id=t.customer_id where t.business_id=${c.get('auth').businessId}::uuid order by t.opened_at desc`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/commands',requirePermission('orders.write'),async c=>{const p=z.object({code:z.string().trim().min(1).max(80),tableId:id.nullish(),customerId:id.nullish(),guestCount:z.coerce.number().int().min(1).max(200).default(1),unitId:id.nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Comanda inválida');const recordId=uuidv7();await c.get('db').execute(sql`insert into order_tabs(id,business_id,unit_id,table_id,customer_id,code,guest_count,status,opened_by) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.unitId??null}::uuid,${p.data.tableId??null}::uuid,${p.data.customerId??null}::uuid,${p.data.code},${p.data.guestCount},'open',${c.get('auth').userId}::uuid)`);if(p.data.tableId)await c.get('db').execute(sql`update restaurant_tables set status='occupied' where id=${p.data.tableId}::uuid and business_id=${c.get('auth').businessId}::uuid`);return c.json({data:{id:recordId,...p.data,status:'open'}},201);});
specializedResourceRoutes.post('/commands/:id/close',requirePermission('orders.write'),async c=>{const record=id.safeParse(c.req.param('id'));if(!record.success)return error(c,422,'VALIDATION_ERROR','Comanda inválida');const pending=await c.get('db').execute(sql`select count(*)::int count from orders where business_id=${c.get('auth').businessId}::uuid and tab_id=${record.data}::uuid and status not in ('closed','cancelled')`);if(Number((rows(pending)[0] as any)?.count)>0)return error(c,409,'OPEN_ORDERS','Finalize os pedidos da comanda antes de fechá-la');const r=await c.get('db').execute(sql`update order_tabs set status='closed',closed_by=${c.get('auth').userId}::uuid,closed_at=now() where id=${record.data}::uuid and business_id=${c.get('auth').businessId}::uuid and status='open' returning table_id`);const tab:any=rows(r)[0];if(!tab)return error(c,404,'NOT_FOUND','Comanda aberta não encontrada');if(tab.table_id)await c.get('db').execute(sql`update restaurant_tables set status='available' where id=${tab.table_id}::uuid and business_id=${c.get('auth').businessId}::uuid`);return c.json({data:{id:record.data,status:'closed'}});});

specializedResourceRoutes.get('/kitchen',requirePermission('orders.read'),async c=>{const r=await c.get('db').execute(sql`select kt.*,o.channel,o.table_id,rt.number table_number,coalesce((select jsonb_agg(jsonb_build_object('description',oi.description,'quantity',oi.quantity,'notes',oi.notes,'status',oi.status) order by oi.created_at) from order_items oi where oi.order_id=o.id and oi.business_id=o.business_id),'[]'::jsonb) items from kitchen_tickets kt join orders o on o.id=kt.order_id and o.business_id=kt.business_id left join restaurant_tables rt on rt.id=o.table_id where kt.business_id=${c.get('auth').businessId}::uuid and kt.status not in ('completed','cancelled') order by kt.priority desc,kt.queued_at asc`);return c.json({data:rows(r)});});

specializedResourceRoutes.get('/delivery',requirePermission('orders.read'),async c=>{const r=await c.get('db').execute(sql`select d.*,o.total,o.payment_status,o.fulfillment_status,cu.name customer_name from delivery_fulfillments d join orders o on o.id=d.order_id and o.business_id=d.business_id left join customers cu on cu.id=o.customer_id where d.business_id=${c.get('auth').businessId}::uuid order by d.created_at desc`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/orders/:id/delivery',requirePermission('orders.write'),async c=>{const orderId=id.safeParse(c.req.param('id'));const p=z.object({address:z.record(z.string(),z.unknown()),recipientName:z.string().max(180).nullish(),recipientPhone:z.string().max(40).nullish(),courierName:z.string().max(180).nullish(),deliveryFee:money.default(0),estimatedAt:z.iso.datetime().nullish()}).safeParse(await c.req.json().catch(()=>null));if(!orderId.success||!p.success)return error(c,422,'VALIDATION_ERROR','Entrega inválida');const recordId=uuidv7();const r=await c.get('db').execute(sql`insert into delivery_fulfillments(id,business_id,order_id,address_json,recipient_name,recipient_phone,courier_name,delivery_fee,status,estimated_at) select ${recordId},${c.get('auth').businessId}::uuid,o.id,${JSON.stringify(p.data.address)}::jsonb,${p.data.recipientName??null},${p.data.recipientPhone??null},${p.data.courierName??null},${p.data.deliveryFee},'waiting',${p.data.estimatedAt?new Date(p.data.estimatedAt):null} from orders o where o.id=${orderId.data}::uuid and o.business_id=${c.get('auth').businessId}::uuid returning id`);if(!rows(r).length)return error(c,404,'NOT_FOUND','Pedido não encontrado');await c.get('db').execute(sql`update orders set channel='delivery',delivery_fee=${p.data.deliveryFee},total=subtotal-discount+${p.data.deliveryFee},updated_at=now() where id=${orderId.data}::uuid and business_id=${c.get('auth').businessId}::uuid`);return c.json({data:{id:recordId,orderId:orderId.data,status:'waiting'}},201);});
specializedResourceRoutes.patch('/delivery/:id/status',requirePermission('orders.write'),async c=>{const deliveryId=id.safeParse(c.req.param('id'));const p=z.object({status:z.enum(['waiting','preparing','ready','dispatched','delivered','cancelled']),courierName:z.string().max(180).nullish()}).safeParse(await c.req.json().catch(()=>null));if(!deliveryId.success||!p.success)return error(c,422,'VALIDATION_ERROR','Entrega inválida');const r=await c.get('db').execute(sql`update delivery_fulfillments set status=${p.data.status},courier_name=coalesce(${p.data.courierName??null},courier_name),dispatched_at=case when ${p.data.status}='dispatched' then coalesce(dispatched_at,now()) else dispatched_at end,delivered_at=case when ${p.data.status}='delivered' then coalesce(delivered_at,now()) else delivered_at end,updated_at=now() where id=${deliveryId.data}::uuid and business_id=${c.get('auth').businessId}::uuid returning *`);if(!rows(r).length)return error(c,404,'NOT_FOUND','Entrega não encontrada');return c.json({data:rows(r)[0]});});

specializedResourceRoutes.get('/categories',requirePermission('products.read'),async c=>{const r=await c.get('db').execute(sql`select * from product_categories where business_id=${c.get('auth').businessId}::uuid order by sort_order,name`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/categories',requirePermission('products.write'),async c=>{const p=z.object({name:z.string().trim().min(1).max(120),description:z.string().max(1000).nullish(),sortOrder:z.coerce.number().int().default(0)}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Categoria inválida');const recordId=uuidv7();await c.get('db').execute(sql`insert into product_categories(id,business_id,name,description,sort_order) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.name},${p.data.description??null},${p.data.sortOrder})`);return c.json({data:{id:recordId,...p.data}},201);});

specializedResourceRoutes.get('/variations',requirePermission('products.read'),async c=>{const r=await c.get('db').execute(sql`select v.*,p.name product_name from product_variants v join products p on p.id=v.product_id and p.business_id=v.business_id where v.business_id=${c.get('auth').businessId}::uuid order by p.name,v.name`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/variations',requirePermission('products.write'),async c=>{const p=z.object({productId:id,name:z.string().trim().min(1).max(120),sku:z.string().max(80).nullish(),barcode:z.string().max(80).nullish(),salePrice:money.nullish(),costPrice:money.nullish(),attributes:z.record(z.string(),z.unknown()).default({})}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Variação inválida');const recordId=uuidv7();const r=await c.get('db').execute(sql`insert into product_variants(id,business_id,product_id,sku,barcode,name,attributes_json,cost_price,sale_price) select ${recordId},${c.get('auth').businessId}::uuid,p.id,${p.data.sku??null},${p.data.barcode??null},${p.data.name},${JSON.stringify(p.data.attributes)}::jsonb,${p.data.costPrice??null},${p.data.salePrice??null} from products p where p.id=${p.data.productId}::uuid and p.business_id=${c.get('auth').businessId}::uuid returning id`);if(!rows(r).length)return error(c,404,'NOT_FOUND','Produto não encontrado');return c.json({data:{id:recordId,...p.data}},201);});

specializedResourceRoutes.get('/addons',requirePermission('products.read'),async c=>{const r=await c.get('db').execute(sql`select * from menu_addons where business_id=${c.get('auth').businessId}::uuid order by name`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/addons',requirePermission('products.write'),async c=>{const p=z.object({name:z.string().trim().min(1).max(120),price:money.default(0)}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Adicional inválido');const recordId=uuidv7();await c.get('db').execute(sql`insert into menu_addons(id,business_id,name,price) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.name},${p.data.price})`);return c.json({data:{id:recordId,...p.data}},201);});

specializedResourceRoutes.get('/combos',requirePermission('products.read'),async c=>{const r=await c.get('db').execute(sql`select pc.*,coalesce((select jsonb_agg(jsonb_build_object('productId',pci.product_id,'quantity',pci.quantity,'productName',p.name)) from product_combo_items pci join products p on p.id=pci.product_id where pci.combo_id=pc.id and pci.business_id=pc.business_id),'[]'::jsonb) items from product_combos pc where pc.business_id=${c.get('auth').businessId}::uuid order by pc.name`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/combos',requirePermission('products.write'),async c=>{const p=z.object({name:z.string().trim().min(1).max(160),description:z.string().max(1000).nullish(),salePrice:money,items:z.array(z.object({productId:id,quantity:qty})).min(1)}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Combo inválido');const comboId=uuidv7();await c.get('db').execute(sql`insert into product_combos(id,business_id,name,description,sale_price) values(${comboId},${c.get('auth').businessId}::uuid,${p.data.name},${p.data.description??null},${p.data.salePrice})`);for(const item of p.data.items)await c.get('db').execute(sql`insert into product_combo_items(id,business_id,combo_id,product_id,quantity) values(${uuidv7()},${c.get('auth').businessId}::uuid,${comboId}::uuid,${item.productId}::uuid,${item.quantity})`);return c.json({data:{id:comboId,...p.data}},201);});

specializedResourceRoutes.get('/coupons',requirePermission('sales.read'),async c=>{const r=await c.get('db').execute(sql`select * from coupons where business_id=${c.get('auth').businessId}::uuid order by created_at desc`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/coupons',requirePermission('sales.create'),async c=>{const p=z.object({code:z.string().trim().min(2).max(50),discountType:z.enum(['percent','fixed']),discountValue:money,minimumAmount:money.nullish(),startsAt:z.iso.datetime().nullish(),expiresAt:z.iso.datetime().nullish(),usageLimit:z.coerce.number().int().positive().nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Cupom inválido');if(p.data.discountType==='percent'&&p.data.discountValue>100)return error(c,422,'VALIDATION_ERROR','Percentual de desconto inválido');const max=c.get('auth').policyLimits.get('sales.max_discount_percent');if(p.data.discountType==='percent'&&typeof max==='number'&&p.data.discountValue>max)return error(c,403,'POLICY_LIMIT_EXCEEDED','Desconto acima do limite permitido',{limit:max});const recordId=uuidv7();await c.get('db').execute(sql`insert into coupons(id,business_id,code,discount_type,discount_value,minimum_amount,starts_at,expires_at,usage_limit) values(${recordId},${c.get('auth').businessId}::uuid,upper(${p.data.code}),${p.data.discountType},${p.data.discountValue},${p.data.minimumAmount??null},${p.data.startsAt?new Date(p.data.startsAt):null},${p.data.expiresAt?new Date(p.data.expiresAt):null},${p.data.usageLimit??null})`);return c.json({data:{id:recordId,...p.data}},201);});

specializedResourceRoutes.get('/delivery-fees',requirePermission('orders.read'),async c=>{const r=await c.get('db').execute(sql`select * from delivery_zones where business_id=${c.get('auth').businessId}::uuid order by name`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/delivery-fees',requirePermission('orders.write'),async c=>{const p=z.object({name:z.string().trim().min(1).max(160),postalCodePrefix:z.string().max(20).nullish(),neighborhood:z.string().max(120).nullish(),fee:money,minimumAmount:money.nullish(),estimatedMinutes:z.coerce.number().int().positive().max(1440).nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Taxa inválida');const recordId=uuidv7();await c.get('db').execute(sql`insert into delivery_zones(id,business_id,name,postal_code_prefix,neighborhood,fee,minimum_amount,estimated_minutes) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.name},${p.data.postalCodePrefix??null},${p.data.neighborhood??null},${p.data.fee},${p.data.minimumAmount??null},${p.data.estimatedMinutes??null})`);return c.json({data:{id:recordId,...p.data}},201);});

specializedResourceRoutes.get('/equipment',requirePermission('service_orders.read'),async c=>{const r=await c.get('db').execute(sql`select e.*,cu.name customer_name from customer_equipment e join customers cu on cu.id=e.customer_id and cu.business_id=e.business_id where e.business_id=${c.get('auth').businessId}::uuid order by e.created_at desc`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/equipment',requirePermission('service_orders.write'),async c=>{const p=z.object({customerId:id,equipmentType:z.string().trim().min(1).max(120),brand:z.string().max(120).nullish(),model:z.string().max(120).nullish(),serialNumber:z.string().max(180).nullish(),identifier:z.string().max(180).nullish(),notes:z.string().max(2000).nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Equipamento inválido');const recordId=uuidv7();const r=await c.get('db').execute(sql`insert into customer_equipment(id,business_id,customer_id,equipment_type,brand,model,serial_number,identifier,notes) select ${recordId},${c.get('auth').businessId}::uuid,cu.id,${p.data.equipmentType},${p.data.brand??null},${p.data.model??null},${p.data.serialNumber??null},${p.data.identifier??null},${p.data.notes??null} from customers cu where cu.id=${p.data.customerId}::uuid and cu.business_id=${c.get('auth').businessId}::uuid returning id`);if(!rows(r).length)return error(c,404,'NOT_FOUND','Cliente não encontrado');return c.json({data:{id:recordId,...p.data}},201);});

specializedResourceRoutes.get('/quotes',requirePermission('service_orders.read'),async c=>{const r=await c.get('db').execute(sql`select q.*,cu.name customer_name from quotes q left join customers cu on cu.id=q.customer_id where q.business_id=${c.get('auth').businessId}::uuid order by q.created_at desc`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/quotes',requirePermission('service_orders.write'),async c=>{const p=z.object({customerId:id.nullish(),serviceOrderId:id.nullish(),title:z.string().trim().min(1).max(200),discount:money.default(0),validUntil:z.iso.date().nullish(),items:z.array(z.object({itemType:z.enum(['product','service','labor','part']),productId:id.nullish(),serviceId:id.nullish(),description:z.string().min(1).max(300),quantity:qty,unitPrice:money})).min(1)}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Orçamento inválido',p.error.flatten());const subtotal=p.data.items.reduce((s,x)=>s+x.quantity*x.unitPrice,0);if(p.data.discount>subtotal)return error(c,422,'VALIDATION_ERROR','Desconto maior que o subtotal');const n=await c.get('db').execute(sql`select coalesce(max(number),0)+1 next from quotes where business_id=${c.get('auth').businessId}::uuid`);const number=Number((rows(n)[0] as any)?.next??1);const quoteId=uuidv7();await c.get('db').execute(sql`insert into quotes(id,business_id,customer_id,service_order_id,number,title,status,subtotal,discount,total,valid_until,created_by) values(${quoteId},${c.get('auth').businessId}::uuid,${p.data.customerId??null}::uuid,${p.data.serviceOrderId??null}::uuid,${number},${p.data.title},'draft',${subtotal},${p.data.discount},${subtotal-p.data.discount},${p.data.validUntil??null}::date,${c.get('auth').userId}::uuid)`);for(const item of p.data.items)await c.get('db').execute(sql`insert into quote_items(id,business_id,quote_id,item_type,product_id,service_id,description,quantity,unit_price,total) values(${uuidv7()},${c.get('auth').businessId}::uuid,${quoteId}::uuid,${item.itemType},${item.productId??null}::uuid,${item.serviceId??null}::uuid,${item.description},${item.quantity},${item.unitPrice},${item.quantity*item.unitPrice})`);return c.json({data:{id:quoteId,number,total:subtotal-p.data.discount,status:'draft'}},201);});

specializedResourceRoutes.get('/warranties',requirePermission('service_orders.read'),async c=>{const r=await c.get('db').execute(sql`select w.*,so.number service_order_number,cu.name customer_name from service_warranties w join service_orders so on so.id=w.service_order_id left join customers cu on cu.id=w.customer_id where w.business_id=${c.get('auth').businessId}::uuid order by w.expires_on desc`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/warranties',requirePermission('service_orders.write'),async c=>{const p=z.object({serviceOrderId:id,customerId:id.nullish(),startsOn:z.iso.date(),expiresOn:z.iso.date(),coverage:z.string().max(3000).nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Garantia inválida');const recordId=uuidv7();await c.get('db').execute(sql`insert into service_warranties(id,business_id,service_order_id,customer_id,starts_on,expires_on,coverage) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.serviceOrderId}::uuid,${p.data.customerId??null}::uuid,${p.data.startsOn}::date,${p.data.expiresOn}::date,${p.data.coverage??null})`);return c.json({data:{id:recordId,...p.data,status:'active'}},201);});

specializedResourceRoutes.get('/suppliers',requirePermission('inventory.read'),async c=>{const r=await c.get('db').execute(sql`select * from suppliers where business_id=${c.get('auth').businessId}::uuid order by name`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/suppliers',requirePermission('inventory.write'),async c=>{const p=z.object({name:z.string().trim().min(1).max(180),documentNumber:z.string().max(40).nullish(),phone:z.string().max(40).nullish(),email:z.email().nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Fornecedor inválido');const recordId=uuidv7();await c.get('db').execute(sql`insert into suppliers(id,business_id,name,document_number,phone,email) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.name},${p.data.documentNumber??null},${p.data.phone??null},${p.data.email??null})`);return c.json({data:{id:recordId,...p.data}},201);});

specializedResourceRoutes.get('/inventory/locations',requirePermission('inventory.read'),async c=>{const r=await c.get('db').execute(sql`select * from inventory_locations where business_id=${c.get('auth').businessId}::uuid and active=true order by name`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/inventory/locations',requirePermission('inventory.write'),async c=>{const p=z.object({name:z.string().trim().min(1).max(120),code:z.string().max(40).nullish(),unitId:id.nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Local inválido');const recordId=uuidv7();await c.get('db').execute(sql`insert into inventory_locations(id,business_id,unit_id,name,code) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.unitId??null}::uuid,${p.data.name},${p.data.code??null})`);return c.json({data:{id:recordId,...p.data}},201);});

specializedResourceRoutes.get('/membership-plans',requirePermission('customers.read'),async c=>{const r=await c.get('db').execute(sql`select * from membership_plans where business_id=${c.get('auth').businessId}::uuid order by active desc,name`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/membership-plans',requirePermission('customers.update'),async c=>{const p=z.object({name:z.string().trim().min(1).max(160),price:money,billingCycle:z.enum(['weekly','monthly','quarterly','yearly']).default('monthly'),durationMonths:z.coerce.number().int().positive().nullish(),checkinLimit:z.coerce.number().int().positive().nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Plano inválido');const recordId=uuidv7();await c.get('db').execute(sql`insert into membership_plans(id,business_id,name,price,billing_cycle,duration_months,checkin_limit) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.name},${p.data.price},${p.data.billingCycle},${p.data.durationMonths??null},${p.data.checkinLimit??null})`);return c.json({data:{id:recordId,...p.data}},201);});
specializedResourceRoutes.get('/classes',requirePermission('appointments.read'),async c=>{const r=await c.get('db').execute(sql`select sc.*,p.display_name professional_name,coalesce((select count(*)::int from class_enrollments ce where ce.class_id=sc.id and ce.status='confirmed'),0) enrolled from studio_classes sc left join professionals p on p.id=sc.professional_id where sc.business_id=${c.get('auth').businessId}::uuid order by sc.starts_at`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/classes',requirePermission('appointments.write'),async c=>{const p=z.object({name:z.string().trim().min(1).max(160),professionalId:id.nullish(),unitId:id.nullish(),capacity:z.coerce.number().int().positive().max(1000).nullish(),startsAt:z.iso.datetime(),endsAt:z.iso.datetime()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Turma inválida');if(new Date(p.data.endsAt)<=new Date(p.data.startsAt))return error(c,422,'VALIDATION_ERROR','Término deve ser posterior ao início');const recordId=uuidv7();await c.get('db').execute(sql`insert into studio_classes(id,business_id,unit_id,name,professional_id,capacity,starts_at,ends_at) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.unitId??null}::uuid,${p.data.name},${p.data.professionalId??null}::uuid,${p.data.capacity??null},${new Date(p.data.startsAt)},${new Date(p.data.endsAt)})`);return c.json({data:{id:recordId,...p.data,status:'scheduled'}},201);});

specializedResourceRoutes.get('/commission-rules',requirePermission('finance.read'),async c=>{const r=await c.get('db').execute(sql`select cr.*,p.display_name professional_name,pr.name product_name,s.name service_name from commission_rules cr left join professionals p on p.id=cr.professional_id left join products pr on pr.id=cr.product_id left join services s on s.id=cr.service_id where cr.business_id=${c.get('auth').businessId}::uuid order by cr.created_at desc`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/commission-rules',requirePermission('finance.create'),async c=>{const p=z.object({professionalId:id.nullish(),itemType:z.enum(['product','service','all']),productId:id.nullish(),serviceId:id.nullish(),ratePercent:z.coerce.number().min(0).max(100).default(0),fixedAmount:money.default(0)}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Regra de comissão inválida');const recordId=uuidv7();await c.get('db').execute(sql`insert into commission_rules(id,business_id,professional_id,item_type,product_id,service_id,rate_percent,fixed_amount) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.professionalId??null}::uuid,${p.data.itemType},${p.data.productId??null}::uuid,${p.data.serviceId??null}::uuid,${p.data.ratePercent},${p.data.fixedAmount})`);return c.json({data:{id:recordId,...p.data}},201);});

specializedResourceRoutes.get('/business-hours',requirePermission('settings.read'),async c=>{const r=await c.get('db').execute(sql`select * from business_hours where business_id=${c.get('auth').businessId}::uuid order by weekday`);return c.json({data:rows(r)});});
specializedResourceRoutes.put('/business-hours/:weekday',requirePermission('settings.update'),async c=>{const weekday=z.coerce.number().int().min(0).max(6).safeParse(c.req.param('weekday'));const p=z.object({unitId:id.nullish(),opensAt:z.string().regex(/^\d{2}:\d{2}$/).nullish(),closesAt:z.string().regex(/^\d{2}:\d{2}$/).nullish(),breakStartsAt:z.string().regex(/^\d{2}:\d{2}$/).nullish(),breakEndsAt:z.string().regex(/^\d{2}:\d{2}$/).nullish(),closed:z.boolean().default(false)}).safeParse(await c.req.json().catch(()=>null));if(!weekday.success||!p.success)return error(c,422,'VALIDATION_ERROR','Horário inválido');const existing=await c.get('db').execute(sql`select id from business_hours where business_id=${c.get('auth').businessId}::uuid and unit_id is not distinct from ${p.data.unitId??null}::uuid and weekday=${weekday.data} limit 1`);const row:any=rows(existing)[0];const recordId=row?.id??uuidv7();if(row)await c.get('db').execute(sql`update business_hours set opens_at=${p.data.opensAt??null}::time,closes_at=${p.data.closesAt??null}::time,break_starts_at=${p.data.breakStartsAt??null}::time,break_ends_at=${p.data.breakEndsAt??null}::time,closed=${p.data.closed},updated_at=now() where id=${recordId}::uuid and business_id=${c.get('auth').businessId}::uuid`);else await c.get('db').execute(sql`insert into business_hours(id,business_id,unit_id,weekday,opens_at,closes_at,break_starts_at,break_ends_at,closed) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.unitId??null}::uuid,${weekday.data},${p.data.opensAt??null}::time,${p.data.closesAt??null}::time,${p.data.breakStartsAt??null}::time,${p.data.breakEndsAt??null}::time,${p.data.closed})`);return c.json({data:{id:recordId,weekday:weekday.data,...p.data}});});

specializedResourceRoutes.get('/insurance',requirePermission('patients.read'),async c=>{const r=await c.get('db').execute(sql`select * from insurance_providers where business_id=${c.get('auth').businessId}::uuid order by name`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/insurance',requirePermission('patients.write'),async c=>{const p=z.object({name:z.string().trim().min(1).max(160),code:z.string().max(80).nullish(),rules:z.string().max(4000).nullish()}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Convênio inválido');const recordId=uuidv7();await c.get('db').execute(sql`insert into insurance_providers(id,business_id,name,code,rules) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.name},${p.data.code??null},${p.data.rules??null})`);return c.json({data:{id:recordId,...p.data}},201);});

specializedResourceRoutes.get('/notices',requirePermission('customers.read'),async c=>{const r=await c.get('db').execute(sql`select * from announcements where business_id=${c.get('auth').businessId}::uuid order by created_at desc`);return c.json({data:rows(r)});});
specializedResourceRoutes.post('/notices',requirePermission('team.update'),async c=>{const p=z.object({title:z.string().trim().min(1).max(200),message:z.string().trim().min(1).max(5000),audience:z.enum(['all','students','team']).default('all'),publish:z.boolean().default(false)}).safeParse(await c.req.json().catch(()=>null));if(!p.success)return error(c,422,'VALIDATION_ERROR','Aviso inválido');const recordId=uuidv7();await c.get('db').execute(sql`insert into announcements(id,business_id,title,message,audience,status,published_at,created_by) values(${recordId},${c.get('auth').businessId}::uuid,${p.data.title},${p.data.message},${p.data.audience},${p.data.publish?'published':'draft'},${p.data.publish?new Date():null},${c.get('auth').userId}::uuid)`);return c.json({data:{id:recordId,...p.data,status:p.data.publish?'published':'draft'}},201);});
