import { sql } from 'drizzle-orm';
import { Hono } from 'hono';
import { z } from 'zod';
import { error, requirePermission } from '../middleware';
import type { ApiEnv } from '../types';

export const transactionalOrderRoutes=new Hono<ApiEnv>();
const rows=(r:any)=>r?.rows??r??[];
const createSchema=z.object({customerId:z.uuid().nullish(),unitId:z.uuid().nullish(),tableId:z.uuid().nullish(),tabId:z.uuid().nullish(),channel:z.enum(['counter','table','delivery','pickup','online']).default('counter'),notes:z.string().max(2000).nullish(),items:z.array(z.object({productId:z.uuid().nullish(),variantId:z.uuid().nullish(),serviceId:z.uuid().nullish(),professionalId:z.uuid().nullish(),description:z.string().min(1).max(300),quantity:z.coerce.number().positive(),unitPrice:z.coerce.number().nonnegative(),discount:z.coerce.number().nonnegative().default(0),notes:z.string().max(1000).nullish()})).min(1)}).strict();

transactionalOrderRoutes.post('/orders',requirePermission('orders.write'),async c=>{
 const parsed=createSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,422,'VALIDATION_ERROR','Pedido inválido',parsed.error.flatten());
 const subtotal=parsed.data.items.reduce((s,x)=>s+x.quantity*x.unitPrice,0),discount=parsed.data.items.reduce((s,x)=>s+x.discount,0);const max=c.get('auth').policyLimits.get('sales.max_discount_percent');if(typeof max==='number'&&subtotal>0&&(discount/subtotal)*100>max)return error(c,403,'POLICY_LIMIT_EXCEEDED','Desconto acima do limite permitido para seu perfil',{limitPercent:max});
 try{const result=await c.get('db').execute(sql`select * from create_order_transactional(${c.get('auth').businessId}::uuid,${c.get('auth').userId}::uuid,${parsed.data.unitId??null}::uuid,${parsed.data.customerId??null}::uuid,${parsed.data.tableId??null}::uuid,${parsed.data.tabId??null}::uuid,${parsed.data.channel},${parsed.data.notes??null},${JSON.stringify(parsed.data.items)}::jsonb)`);const row:any=rows(result)[0];return c.json({data:{id:row.order_id,subtotal:row.subtotal,discount:row.discount,total:row.total,status:'open'}},201)}catch(reason){const message=reason instanceof Error?reason.message:String(reason);if(message.includes('CUSTOMER_NOT_FOUND'))return error(c,404,'CUSTOMER_NOT_FOUND','Cliente não encontrado');if(message.includes('TABLE_NOT_FOUND'))return error(c,404,'TABLE_NOT_FOUND','Mesa não encontrada');if(message.includes('TAB_NOT_FOUND'))return error(c,404,'TAB_NOT_FOUND','Comanda não encontrada ou fechada');if(message.includes('PRODUCT_NOT_FOUND'))return error(c,404,'PRODUCT_NOT_FOUND','Produto não encontrado');if(message.includes('INVENTORY_LOCATION_REQUIRED'))return error(c,409,'INVENTORY_LOCATION_REQUIRED','Configure um local de estoque para produtos controlados');if(message.includes('INSUFFICIENT_STOCK'))return error(c,409,'INSUFFICIENT_STOCK','Estoque disponível insuficiente');throw reason;}
});

transactionalOrderRoutes.post('/orders/:orderId/cancel',requirePermission('orders.write'),async c=>{const orderId=z.uuid().safeParse(c.req.param('orderId'));const body=z.object({reason:z.string().trim().min(3).max(1000)}).safeParse(await c.req.json().catch(()=>null));if(!orderId.success||!body.success)return error(c,422,'VALIDATION_ERROR','Cancelamento inválido');try{await c.get('db').execute(sql`select cancel_order_transactional(${c.get('auth').businessId}::uuid,${orderId.data}::uuid,${c.get('auth').userId}::uuid,${body.data.reason})`);return c.json({data:{id:orderId.data,status:'cancelled'}})}catch(reason){const message=reason instanceof Error?reason.message:String(reason);if(message.includes('ORDER_NOT_FOUND'))return error(c,404,'NOT_FOUND','Pedido não encontrado');if(message.includes('ORDER_ALREADY_FINAL'))return error(c,409,'ORDER_ALREADY_FINAL','Pedido já foi encerrado');if(message.includes('PAID_ORDER_REQUIRES_REFUND'))return error(c,409,'PAID_ORDER_REQUIRES_REFUND','Pedido pago deve ser estornado antes do cancelamento');throw reason;}});

transactionalOrderRoutes.post('/orders/:orderId/close',requirePermission('orders.write'),async c=>{
  const orderId=z.uuid().safeParse(c.req.param('orderId'));if(!orderId.success)return error(c,422,'VALIDATION_ERROR','Pedido inválido');
  try{
    const result:any=await c.get('db').execute(sql`select * from close_order_transactional(${c.get('auth').businessId}::uuid,${orderId.data}::uuid,${c.get('auth').userId}::uuid)`);
    const row=(result?.rows??result??[])[0];if(!row)return error(c,500,'ORDER_CLOSE_FAILED','Fechamento não retornou resultado');return c.json({data:{id:row.order_id,saleId:row.sale_id,total:row.total,status:'closed'}});
  }catch(reason){const message=reason instanceof Error?reason.message:String(reason);if(message.includes('ORDER_NOT_FOUND'))return error(c,404,'NOT_FOUND','Pedido não encontrado');if(message.includes('ORDER_ALREADY_FINAL'))return error(c,409,'ORDER_ALREADY_FINAL','Pedido já foi encerrado');if(message.includes('PAYMENT_PENDING'))return error(c,409,'PAYMENT_PENDING','O pedido precisa estar totalmente pago');if(message.includes('INVENTORY_LOCATION_REQUIRED'))return error(c,409,'INVENTORY_LOCATION_REQUIRED','Configure um local de estoque antes de fechar a venda');if(message.includes('INSUFFICIENT_STOCK'))return error(c,409,'INSUFFICIENT_STOCK','Estoque insuficiente para concluir o pedido');throw reason;}
});
